### ISSUE TITLE
Do not allow restrictive access control change to content with a DOI

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1011]
---

Author Name: **ben leinfelder** (ben leinfelder)
Original Redmine Issue: 6416, https://projects.ecoinformatics.org/ecoinfo/issues/6416

Original Assignee: ben leinfelder

---

None

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2014-05-12T19:50:27Z

---

Thinking about this more, we have only CN.setAccessPolicy() in the DataONE API. So any change in the access policy would be network-wide. Do we really want to prevent changing access to be non-public if the object has a DOI and enforce this rule for all of DataONE?

We could restrict the old Metacat API to fail when setting access on a docid that maps to a DOI, but that will be a small fraction of our API calls going forward since it is deprecated.

Thoughts?

**Comment by taojing2002** [comment]
In dataone v2 nodes, the system metadata is controlled by member nodes. The rule has been added to MN.updateSystemMetadata to enforce clients not to remove public-readable rule for DOI objects.
