### ISSUE TITLE
Metacat MN.create method doesn't check if the identifier exists in CNs (dataone network)

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1070]
---

Author Name: **Dave Vieglais** (Dave Vieglais)
Original Redmine Issue: 6649, https://projects.ecoinformatics.org/ecoinfo/issues/6649
Original Date: 2015-01-19
Original Assignee: Jing Tao

---

See https://redmine.dataone.org/issues/6488

Metacat MN.create and CN.create share the code to check if the identifier exists. But it only checks two places - identifier table and systemmetadata table. It is a local check and this check may be correct for CN. But in the MN.create documenation: The pid must not exist in the DataONE system.

So MN.create should call the CN.reserveIdentifier(id) to check if the id exists in the system wide.

**Comment by taojing2002** [comment]
The issue has been fixed.
