### ISSUE TITLE
error trying updating metadata on https://knb.ecoinformatics.org/#view/knb.894.1

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1099]
---

Author Name: **Julien Brun** (Julien Brun)
Original Redmine Issue: 6952, https://projects.ecoinformatics.org/ecoinfo/issues/6952
Original Date: 2016-01-27

---

Hi guys,

When we are trying to edit this package metadata https://knb.ecoinformatics.org/#view/knb.894.1 using the KNB website (uid=pellis_knb), we are getting this error:

_Whoops!
An error occurred. Please check the list of errors below:

cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '[\s]*[\S][\s\S]*' for type 'NonEmptyStringType'.
Failed while updating._

Thank you for looking into this!
Julien

**Comment by taojing2002** [comment]
The issue has been fixed and the link works well.
