### ISSUE TITLE
Fatal processing error when updating an object with incorrect sysmeta

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1115]
---

Author Name: **Bryce Mecum** (Bryce Mecum)
Original Redmine Issue: 7022, https://projects.ecoinformatics.org/ecoinfo/issues/7022
Original Date: 2016-05-06

---

Jessica used the R package today to update an object with new bytes via the D1 REST API  call for MNStorage.update(). She received this error back from Tomcat:

```
<?xml version="1.0"?>
<error>Fatal processing error.</error>

```

She showed me what she had for her input to the call and I found that the sysmeta formatId was EML 2.1.1 instead of text/csv which was the correct format ID for the object. This was a bug in my code that she was running that I've since addressed.

I expected a more useful error that directly addressed the mismatch in format ID and the file being uploaded.

Why did this action cause a "Fatal processing error"? It seems like the sysmeta format ID being set to EML should've triggered the EML validation routine which should have returned a validation error.

**Comment by taojing2002** [comment]
This error message is from xcers. Since the format id is eml, Metacat will use to the xml parser to parse it. However, the object is not an XML document and the parser will give the error.
