### ISSUE TITLE
Remove the oracle part on documentation

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1123]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 7061, https://projects.ecoinformatics.org/ecoinfo/issues/7061
Original Date: 2016-07-21
Original Assignee: Jing Tao

---

Since Metacat 2.7.0, we have stopped the support of Oracle on Metacat. However, the documentation still mentions Oracle. We need to remove the content about Oracle.

**Comment by taojing2002** [comment]
The Oracle part has been removed.
