### ISSUE TITLE
Upgrade xerces and xalan lib

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1134]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 7092, https://projects.ecoinformatics.org/ecoinfo/issues/7092
Original Date: 2016-08-25
Original Assignee: Jing Tao

---

Currently we are using xerces and xalan 2.7 version which came out in 2005. We need to upgraded it.

**Comment by taojing2002** [comment]
The libraries have been upgraded.
