### ISSUE TITLE
Upgrade Solr Server

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1147]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 7148, https://projects.ecoinformatics.org/ecoinfo/issues/7148
Original Date: 2016-10-19
Original Assignee: Jing Tao

---

Currently, the solr server version on Metacat is 3.6.2. But the newest version is 6.*. We need to upgrade it in the near future.

**Comment by taojing2002** [comment]
Duplicate to ticket https://github.com/NCEAS/metacat/issues/1235
