### ISSUE TITLE
View service rendering EML project abstract incorrectly

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1155]
---

Author Name: **Bryce Mecum** (Bryce Mecum)
Original Redmine Issue: 7164, https://projects.ecoinformatics.org/ecoinfo/issues/7164
Original Date: 2016-12-01
Original Assignee: Bryce Mecum

---

The view service's XSLT for rendering EML is producing output that doesn't look quite right. See attached screenshot. A quick investigating revealed it's just missing a wrapping div.

**Comment by amoeba** [comment]
Here's the screenshot from the linked Redmine issue: 

![Screen Shot 2016-12-01 at 12 37 05 PM](https://user-images.githubusercontent.com/563/108121589-815cc500-704f-11eb-9b17-6c1c60c27649.png)

**Comment by amoeba** [comment]
Closed by https://github.com/NCEAS/metacat/commit/b6daceffc93a41b317c6ef67e3bc3b407b850f26.
