### ISSUE TITLE
Upgrade postgresql jdbc jar file on Metacat

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1183]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 7199, https://projects.ecoinformatics.org/ecoinfo/issues/7199
Original Date: 2017-06-02
Original Assignee: Jing Tao

---

Please see detail on this ticket:
https://redmine.dataone.org/issues/8104

**Comment by taojing2002** [comment]
Upgraded the version of the postgres jdbc library to the latest one - `42.6.0`. In their github [page](https://github.com/pgjdbc/pgjdbc), it says: 
```
The current version of the driver should be compatible with PostgreSQL 8.4 and higher using the version 3.0 of the protocol and Java 8 (JDBC 4.2) or above. Unless you have unusual requirements (running old applications or JVMs), this is the driver you should be using.
```
After the upgrading, the new library found a bug in the SystemMetadataManager class - we tried  to call `conn.commit()` when the `conn` is set `auto-commit`.
After fixing the bug,  I ran the all tests against both Postgresql Server 10 and 14. All of them passed excepted the known failures.
