### ISSUE TITLE
Add documentation to indicate and help users Metacat only runs under Java 1.8

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1186]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 7202, https://projects.ecoinformatics.org/ecoinfo/issues/7202
Original Date: 2017-06-27
Original Assignee: Jing Tao

---

We decided that this 2.9.0 release will only be running under Java 1.8. We need to make clear to the user in our documentation. We also need to help user to install open jdk in Ubuntu 14.

**Comment by taojing2002** [comment]
Metacat should support the java 17 after we remove hazelcast in the 3.0.0 release.
