### ISSUE TITLE
metacat-index missing metadata quality fields

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1195]
---

Author Name: **Peter Slaughter** (Peter Slaughter)
Original Redmine Issue: 7212, https://projects.ecoinformatics.org/ecoinfo/issues/7212
Original Date: 2017-10-03
Original Assignee: Peter Slaughter

---

The Spring context file ./metacat-index/src/main/resources/application-context-mdq.xml doesn't contain a bean definition for the quality check types 'congruency' or 'dataFormats',
although these are check types that we should record results for. There is a bean for check type 'other', but this isn't sufficient.

**Comment by gothub** [comment]
Metadata quality information is now indexed in the MetaDIG Quality Solr server.
