### ISSUE TITLE
MDQClient.saveRun doesn't obsolete existing quality documents

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1199]
---

Author Name: **Peter Slaughter** (Peter Slaughter)
Original Redmine Issue: 7216, https://projects.ecoinformatics.org/ecoinfo/issues/7216
Original Date: 2017-10-11
Original Assignee: Peter Slaughter

---

MDQClient.saveRun is called to upload a newly created quality document, in response to a metadata quality document being uploaded or updated. 

When MDQClient.saveRun is called by MNodeService.update, it does not check if a quality document has already been created
for the metadata document. saveRun should check if a previous quality document has been created for the metadata, and obsolete it
with the new quality document. This will ensure that quality statistics are accurate, as obsoleted quality reports will not be
included in statistical calculations, as they are essentially duplicates.

**Comment by mbjones** [comment]
@jeanetteclark if this is no longer relevant, can you close this issue?

**Comment by jeanetteclark** [comment]
From what I know, metadig functionality was taken out of the metacat code entirely, and it looks like MNodeService.update no longer calls saveRun, so this seems safe to close to me
