### ISSUE TITLE
EZID metadata registration doesn't seem to work with SIDs

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1206]
---

Author Name: **Bryce Mecum** (Bryce Mecum)
Original Redmine Issue: 7223, https://projects.ecoinformatics.org/ecoinfo/issues/7223
Original Date: 2017-10-24
Original Assignee: Jing Tao

---

Earlier today, a DOI was generated using R's `generateIdentifier` (which calls MNStorage.generateIdentifier()). Then the newly-minted DOI was set as the Series ID of an EML 2.1.1 Object. The DOI was successfully registered with EZID but the EZID metadata was not correctly set on the object, as shown when I logged in. See the attached screenshot.

I expected the EZID metadata to get filled in like it normally does for DOIs that get used as PIDs. I took a quick glance at the relevant part of Metacat and it doesn't look like anything special is done to handle SIDs.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Bryce Mecum** (Bryce Mecum)
Original Date: 2017-10-25T03:02:09Z

---

Chris volunteered to take a look at this and has a possible patch in place.

**Comment by taojing2002** [comment]
The DOIService only handled the case the identifier on the system metadata is an DOI. Now it has been modified to handle three cases:

- The identifier field is an DOI but the sid field is not an DOI (or not set).
- The identifier field is not an DOI but the sid field is an DOI.
- Both identifier and sid fields are DOIs.
