### ISSUE TITLE
Cache CA subjects on Metacat

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1230]
When Metacat check if a subject is a CN, it will call the method `cNode.listNode()` to get the CN nodes. Matt mentioned when the method was written, the d1_libclient_java had a cache system. Tob said the cache system doesn't exist now. So Metacat should cache CA subjects to avoid the expensive network connection.

**Comment by csjx** [comment]
Hi @taojing2002 - I don't understand why the caching functionality was removed from `d1_libclient_java`.  This is very much a D1 API interaction, al of which is handled by the library, and to remove the existing behavior is a backwards-incompatible change.  Let's discuss this before we add anything into Metacat - I'd like to revisit the reasons it was removed from the client. Thanks!

**Comment by taojing2002** [comment]
As Chris mentioned, it should be a `d1_libclient_java` feature and it has been implemented.
