### ISSUE TITLE
Upgrade Solr version on Metacat-index

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1235]
Currently Metacat is using 3.6.2 solrj and solr-core version. It is pretty out of date and we need to upgrade. 

First question, which is our target version? The current release is 7.3.0. Which we should choose? 5.x(dataone is using), 6.x, or the current release? Note: after 6.0, it requires java 1.8.
My thought is we should use the newest version if it wouldn't break dataone index.

Second question, how to upgrade the existing the index? I found a tool to upgrade existing solr index from 4.x to 7.x:
https://github.com/cominvent/solr-tools/
https://www.quora.com/How-do-I-move-4-3-1-core-to-6-5-1-core-in-Solr
I will play it a little bit.

**Comment by mbjones** [comment]
Unless there is a compelling disadvantage or incompatibility, I think moving to the most recent stable version makes the most sense and gives us the most longevity.  In general, smaller version upgrades are easier than large ones, so it would be nice to track these releases more closely in the future as we release new versions of Metacat.

**Comment by mbjones** [comment]
Could you provide a progress update, @taojing2002?

**Comment by taojing2002** [comment]
The code has been developed in a feature branch. Basically the feature 
is done but we still need a thorough testing. Another issue is it 
introduces lot of  jar files when we handle the Schema object. We plan 
to finish this feature after we release 2.10.

**Comment by vchendrix** [comment]
This will be handled by the Metacat 2.13.0 release
