### ISSUE TITLE
Project Titles not displaying properly on ADC when there are more than one

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1236]
This Issue was initially filed at https://github.com/NCEAS/metacatui/issues/565 and later moved here.

@jagoldstein wrote:

[This package](https://arcticdata.io/catalog/#view/urn:uuid:96a40678-aa0f-446e-8f1a-a70a4c2931ac) has this section of the EML:

```
<project>
   <title>Design and Initialization of an Ice-Tethered Profiler Array Contributing to the Arctic Observing System</title>
   <title>Towards an Arctic Observing Network: An array of Ice-Tethered Profilers to sample the upper ocean water properties during the International Polar Year</title>
   <title>AON: Continuation of the Ice-Tethered Profiler contribution to the Arctic Observing Network</title>
   <title>Collaborative Research: An Arctic Ocean Sea Surface pCO2 and pH Observing Network</title>
```

There are 4 different projects, each with a different title and this is valid EML.
However, in the metacatUI metadata view the Project Titles render like so:

<img width="925" alt="screen shot 2018-04-10 at 10 11 15 am" src="https://user-images.githubusercontent.com/18270215/38572297-961fc002-3ca7-11e8-984d-830d220190f6.png">

Note that the first title is repeated 4 times, instead of displaying the other 3 titles.

**Comment by amoeba** [comment]
Took a quick look at the eml project XSL and I think I see why this is happening:

```xml
<xsl:template name="projecttitle">
     <xsl:for-each select="title">
	   <div class="control-group">
	     <label class="control-label projectTitle">Title:</label>
	   	 <div class="controls controls-well">
		   <xsl:value-of select="../title" />
	   	 </div>
	   </div>
     </xsl:for-each>
  </xsl:template>
```

Specifically, the `../title` xpath. Should be an easy fix.

**Comment by jagoldstein** [comment]
This is a burden for the support team in that users are complaining about it. Please prioritize resolving this issue @laurenwalker . Thanks.

Here is another example: https://arcticdata.io/catalog/#view/doi:10.18739/A2JD4PP1H

**Comment by amoeba** [comment]
Fixed. Lemme know if you agree!

**Comment by jagoldstein** [comment]
I agree!! thank you good sir @amoeba 

take note @dmullen17
