### ISSUE TITLE
Specify internal calls to Metacat on localhost or internal domain name

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacat#1237]
ESS-DIVE deploys metacat with metacatui to a docker application stack with three containers

* db (postgres)
* metacat (tomcat)
* metacatUI (apache)

### Problem Description
ESS-DIVE experienced networking issues in Metacat UI with both upload and viewing of metadata.  
 * The metadata view would timeout with a 503 (bad gateway error) on the XSLT transformation.  It was pin pointed that calls to the XSD file were periodically failing.  
```xml
Error inserting or updating document: ess-dive-ee5c7a99a6fd8c7-20180329T200323062 since 
<?xml version="1.0"?>
<error>schema_reference.4: Failed to read schema document 'https://data-sandbox.ess-dive.lbl.gov/catalog/schema/eml-2.1.1/eml.xsd', because 
1) could not find the document; 
2) the document could not be read; 
3) the root element of the document is not 
<xsd:schema>
</error>
```
* The upload issues sometimes resulted in several retries,  were very slow and would sometimes hang never allowing the user to save their data package.

## Workaround
We made a modification to `metacat.properties` to refer to the internal docker server name and this seemed to fix the networking performance issues described above.
```
############### Server Values #################
server.name=app-metacat
server.httpPort=8080
server.httpSSLPort=8443
```

## Workaround Issues
The above workaround will suffice in the short term until `data.ess-dive.lbl.gov` registers as a DataONE member node.  There are several places in metacat where `server.name` are used to create external facing URLs.

1. Metacat api call https://data.ess-dive.lbl.gov/catalog/d1/mn: `<baseURL>http://app-metacat:8080/catalog/d1/mn</baseURL>`.  I am sure thate DataONE will expect this to be `http://data.ess-dive.lbl.gov/catalog/d1/mn`
2. Generated data package PDF references this URL
<img width="727" alt="screen shot 2018-04-11 at 11 10 09 am" src="https://user-images.githubusercontent.com/1558129/38635022-fdc09e26-3d78-11e8-827c-0ce9dce2cc6e.png">

## Enhancement Request
Provide a way to define internal vs external URLs. One possible solution would be to separate internal server name vs external in the `metacat properties`.

**Comment by mbjones** [comment]
@taojing2002 Let's discuss how this might be addressed.  The proposal above is to ensure that API and resource accesses that originate within Metacat can be configured to access things through a local interface (network or direct file access) rather than going back out through the SSL external interface.  This would probably improve performance or at least latency.  We'll have to inspect the code base to see what accesses are candidates for this change.  Maybe XSD and XSLT accesses at a minimum.

**Comment by taojing2002** [comment]
The only issue I am thinking is the redirection of localhost since metacat doesn't handle it. Here is what happen on knb:
tao@mn-ucsb-4:~$ curl http://localhost
```<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://knb.ecoinformatics.org/">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at localhost Port 80</address>
</body></html>```

**Comment by vchendrix** [comment]
@taojing2002 Wouldn't you need to specify port 8080?  That is how we are configuring the metacat properties.  
```
############### Server Values #################
server.name=app-metacat
server.httpPort=8080
server.httpSSLPort=8443
```

**Comment by csjx** [comment]
I think the point here @taojing2002 is that yes, outside traffic on port 80 should be redirected to port 443, and then forwarded to Tomcat over port AJP, but that internal calls from Metacat itself should go directly to localhost on port 8080. So I think we may need 
 `server.directName=localhost` and a `server.directPort=8080` properties that we use in direct calls, and have the servlet be configured to use the existing properties for external calls (or something similar to this).

**Comment by taojing2002** [comment]
Our best practice is to disable 8080 port on tomcat when we use Apache-Tomcat together. Fox example on KNB:
```
tao@mn-ucsb-4:~$ curl http://localhost:8080
   curl: (7) Failed to connect to localhost port 8080: Connection refused
```
But we may change the configuration.

**Comment by csjx** [comment]
Heya @vchendrix - Jing and I talked this through and are on the same page now.  We're looking at adding two new Metacat properties:
- `server.internalName`
- `server.internalPort`

We'll look through the Metacat code and find the half dozen or so places that we construct a URL with `SystemUtil.getServerURL()` and `SystemUtil.getSecureServerURL()`, and possibly other calls, and will use the internal name and port when it is configured.  We talked about falling back to the external URL if it fails - we'll see about that. But in any case, we should be able to set `server.internalName` to `localhost` or a docker network name like `app-metacat`, etc.  Jing thought we can get this into the 2.9 release.

I'm wondering if we really need the `server.internalPort` though. Hmm.

**Comment by taojing2002** [comment]
The internal port should be configurable as well.

**Comment by taojing2002** [comment]
I developed two methods `getInternalServerURL` and `getInternalContextURL` in the SystemUil class. They will test if the response of the connection to the local server is 200 (but it only tests once after a server starts). If it isn't, the method will fall back to use the external URLs. 

The code to get schema xsd files and xsl files (only for transformation in Metacat server itself, such as transforming a xml file to a html file) are using the `getInternalServerURL/getInternalContextURL` methods. The modified classes are:
```
src/edu/ucsb/nceas/metacat/service/XMLSchema.java
src/edu/ucsb/nceas/metacat/DBTransform.java
src/edu/ucsb/nceas/metacat/SchemaLocationResolver.java
src/edu/ucsb/nceas/metacat/DBUtil.java
src/edu/ucsb/nceas/metacat/DBEntityResolver.java
```

**Comment by mbjones** [comment]
@taojing2002 Awesome.  So, for an existing deployment of Metacat that doesn't need these properties, do you just fallback to the external context methods?  Seems like we should be able to determine whether to use the internal or external context URIs solely based on whether the internal properties are configured, and not require a network call at all to do so.  Does that sound feasible and/or the right approach?
