### ISSUE TITLE
Add support for EML 2.2 release

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1239]
EML 2.2.0 is planned for release soon, likely in ~~May~~ December 2018.  Plan to incorporate the schema into Metacat for validation and register it in DataONE as a new formatId.

- [x] Add 2.2 schemas
- [x] Test display of 2.2 documents in view service
- [x] Register namespace as DataONE formatId
- [ ] Point build.xml at released schema (once released)
- [ ] Bring in latest ECSO and OBOE ontologies into ontology cache once ready

**Comment by amoeba** [comment]
Indexing and view service support for EML 2.2.0 is in https://github.com/NCEAS/metacat/tree/feature-eml220-support. Task for adding the format ID is at https://redmine.dataone.org/issues/8754 and indexing support on the CNs is coded but not pushed up to the latest branches.

EML 2.2.0 hasn't been released yet so the Ant build pulls in the 2.2.0 schemas from the `BRANCH_EML_2_2` branch of https://github.com/NCEAS/eml.

**Comment by amoeba** [comment]
The schema isn't yet released, but super close. This work has been merge into the 2.11 branch and is going through integration testing by @taojing2002 for release.

I wanna leave this open because we'll still need to change the Ant build to point at the release 2.2.0 schema once it's released.
