### ISSUE TITLE
Add a Distribution table for EML in the View Service

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1241]
@laurenwalker noted that some EML documents have a `software` module which includes links to the software by URL (amongst other metadata). See if I can easily throw some of that metadata at the top of the EML XSLT.

**Comment by amoeba** [comment]
The EML document that drove this is http://cn.dataone.org/cn/v2/object/knb-lter-sbc.10.20 which has a series of `methodSteps`, which have `protocols` and `software` which are linked via `./distribution/online/url` child elements.

The EML indexer bean uses this logic to identify "services" in the EML:

- `isService`: `boolean(//software/implementation/distribution/online/url)`
- `serviceTitle`: `//software/title//text()[normalize-space()]`
- `serviceDescription`: `//software/abstract//text()[normalize-space()]`
- `serviceEndpoint`: `//software/implementation/distribution/online/url/text()`

I see decision points here:

- Should this distribution table just show software or other things in EML that have `distribution` elements?
- Since these are already rendered in their proper place, do we even need to do this?

While we're at this, it seems like we could bubble up even more `distribution` tags into a combined table, rather than just stopping at protocols and software. The only catch is that we might not want to do this for Entities unless the EML isn't part of a Data Package.

What do others think about this?

**Comment by amoeba** [comment]
Ooh. I like adding support for that. I'm also okay with letting the deeply-nested distribution sections (like in Methods) stay rendered in methods.

What do you think about tagging this is backlog and getting to it "later"?

**Comment by laurenwalker** [comment]
Works for me.

**Comment by robyngit** [comment]
Moved this issue to MetacatUI: https://github.com/NCEAS/metacatui/issues/2084
