### ISSUE TITLE
Make ant build auto-detect maven location

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1242]
`maven.home` in build.properties is currently hard-coded and it requires developers to change it to get the build running.

https://github.com/NCEAS/metacat/blob/1fbd3b87dc52cd77ee80ab376eea45db37a7cf9d/build.properties#L83

It seems like this can be refactored to automatically provide the build with the location of maven based up on the $PATH.

**Comment by amoeba** [comment]
My first idea;

```bash
$ export MAVEN_HOME="$(mvn --version | grep "Maven home" | cut -d" " -f3)"
$ echo $MAVEN_HOME
/usr/local/Cellar/maven/3.5.3/libexec
```

Gotta be something better than that.

**Comment by mbjones** [comment]
I think the algorithm should be:

1) use $MAVEN_HOME if it is set in the environment
2) if mvn is on the path, run it to find MAVEN_HOME as @amoeba proposed
3) if mvn is not in the path, see if it is in common locations (/usr/local/bin, /opt/local/bin, /opt/bin, etc), and if it is found, then extract MAVEN_HOME as in (2)
4) if still not found, fail build with message saying to do 1 ,2, or 3

**Comment by amoeba** [comment]
I figured this out and it seems to work well. I skipped your Step 3 since I didn't think it was nearly as important as Steps 1 or 2 and thought Steps 1 and 2 were good enough.

Here it is in action:

```bash
$ sh find-maven.sh
A proper MAVEN_HOME could not be found. Either:

  - Set MAVEN_HOME i.e., export MAVEN_HOME="{SOMETHING}"
  - Make your mvn executable available in your PATH

And then run this script (or ant if that's the command you just ran
when you got this error.
$ export MAVEN_HOME="/usr/local/maven/some_home"
$ sh find-maven.sh
/usr/local/maven/some_home
$ export PATH="/usr/local/bin:$PATH"
$ unset MAVEN_HOME
$ sh find-maven.sh
/usr/local/Cellar/maven/3.5.3/libexec
```

And I've tested this out locally by producing a successful ant build. I sent this as a PR in case anyone wants to have a look first: https://github.com/NCEAS/metacat/pull/1245
