### ISSUE TITLE
Packages Endpoint Displays Filesystem Path on Error

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacat#1246]
When attempting to `Download All` on a test package, there was a failure somewhere in the `packages` endpoint. This is probably an unfiltered `e.getMessage()`. 
If someone is working on #1167, this might be worth checking out because they're in the same code area.

To reproduce, visit
`https://dev.nceas.ucsb.edu/knb/d1/mn/v2/packages/application%2Fbagit-097/7074c7ba-e4b2-45a7-ab43-1d5ab74fffd2`

See 
```
<error detailCode="1030" errorCode="500" name="ServiceFailure">
<description>
/tmp/tomcat7-tomcat7-tmp/temp34745415929744280464730042430480435_dir (Is a directory)
</description>
</error>
```

**Comment by ThomasThelen** [comment]
While [testing this](https://dev.nceas.ucsb.edu/knb/d1/mn/v2/packages/application%2Fbagit-1.0/7074c7ba-e4b2-45a7-ab43-1d5ab74fffd2) with the 1.0 refactor, the download works properly; no error is received and the bag gets served. @taojing2002 feel free to close this

**Comment by taojing2002** [comment]
Hi Tommy:

Did you tag the bagit library and build the release? Do I need to increase
the version number of the library on the Metacat pom.xml file?

Thanks,

Jing

**Comment by ThomasThelen** [comment]
I didn't make any changes to the library, so this is currently in production!

**Comment by taojing2002** [comment]
Cool. So we don't need to change anything in Metacat, do we?

Thanks,

Jing

**Comment by ThomasThelen** [comment]
That's correct

**Comment by taojing2002** [comment]
Cool. Thank you, Tommy!
