### ISSUE TITLE
Add `httr` to `SSLClientVerify` directive whitelist

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1251]
As known about for some time and recently filed at https://github.com/DataONEorg/rdataone/issues/210, the R dataone package stopped working against the DataONE API when sending large request bodies due to TLS renegotiation buffering and changes in libcurl. (That was a shamefully brief summary of the issue)

We discussed this issue and potential fixes on our 20180518 dev call. Notes here: https://hpad.dataone.org/KYYwDGAmCc3AtAZhAI0vALAdgIwDZ5oUxF5hEsUAzAVh0gEMGAmZoA==

The affected section of our Apache configs is this:

```
SSLVerifyClient none

<Location "/knb/d1/mn">
        SSLOptions +OptRenegotiate
        <If " ! ( %{HTTP_USER_AGENT} =~ /(windows|chrome|mozilla|safari|webkit|httr)/i )">
                SSLVerifyClient optional
        </If>
</Location>
```

which allows us to not attempt client cert verification for most web browsers. To avoid the `Client error: (413) Request Entity Too Large` from R, we need to add the string `httr` to the whitelist.

I've tested this works by:

1. Testing a `createObject` with a ~2MB file, getting the above error on `dev.nceas`
2. Adding `httr` to the above whitelist in `dev.nceas` Apache config and reloading the config
3. Verifying the `createObject()` call works

**Comment by mbjones** [comment]
@taojing2002 Has this been deployed?

**Comment by amoeba** [comment]
Just following up. This has been deployed where needed but as of right now with current (2.4.29) Apache, we've [turned this entire thing off](https://redmine.dataone.org/issues/8823) waiting for 2.4.39 to be released.
