### ISSUE TITLE
Remove redundant Tomcat properties from build.properties and test.properties

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1259]
While attempting to run the Metacat tests, I noticed I had to set three separate properties before moving on:

1. `build.tomcat.dir` (e.g., `/usr/local/Cellar/tomcat/9.0.8/libexec/`)
2. `app.deploy.dir`: (e.g., `/usr/local/Cellar/tomcat/9.0.8/libexec/webapps`)
3. `metacat.contextDir` (e.g., /`usr/local/Cellar/tomcat/9.0.8/libexec/webapps/metacat`)

Three three properties appear redundant, at least considering how my OS is set up. I think they could be combined into one `build.tomcat.dir` and `app.deploy.dir` and `metacat.contextDir` could become optional but with conventional defaults.

This change would mean `test.properties` could be deleted/optional.

**Comment by taojing2002** [comment]
We need to `tomcat.dir` in the test.properties file since the junit test classes have no way to find the configured metacat.properties file.
