### ISSUE TITLE
"Role" field is duplicated in MetacatUI metadata view under "Project Information"

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1266]
Moved issue filed by @jagoldstein from https://github.com/NCEAS/metacatui/issues/705.

Within the `project` section of EML, the `role` field display is duplicated in the MetacatUI metadata view on arcticdata.io. 

Here is an example from https://arcticdata.io/catalog/#view/urn:uuid:dfe13582-97e1-4871-9252-319dff614fef:
<img width="701" alt="screen shot 2018-07-20 at 12 29 13 pm" src="https://user-images.githubusercontent.com/18270215/43021574-f9c8fc2a-8c18-11e8-87d5-d3287abce055.png">

**Comment by amoeba** [comment]
Looks like this is caused by this part of the personnel template:

https://github.com/NCEAS/metacat/blob/d4eb9588bc6b84c6a0afa308d3f0432265d8e2f8/lib/style/skins/metacatui/eml-2/eml-project.xsl#L92-L99

Should be a quick fix.

**Comment by amoeba** [comment]
Also, I confirmed the EML is fine in that it doesn't duplicate the role (which is invalid EML maybe?):

```xml
      <personnel id="2061576633233243">
        <individualName>
          <givenName>Kathleen</givenName>
          <surName>Stafford</surName>
        </individualName>
        <organizationName>University of Washington</organizationName>
        <positionName>Affiliate Associate Professor, Oceanography</positionName>
        <role>principalInvestigator</role>
      </personnel>
```

**Comment by jagoldstein** [comment]
@laurenwalker this is becoming burdensome for the support team and deserves priority from our POV. thanks

**Comment by amoeba** [comment]
Hey @jagoldstein 	is it burdensome because people are emailing us or another reason? I can hot-patch this now on arcticdata.io.

**Comment by amoeba** [comment]
Just hot-patched arcticdata.io.

**Comment by jagoldstein** [comment]
thanks @amoeba ! lookin good now.
Yes, because of the emails about it from users, but also because we are working hard to create quality EMLs that render accurately.

**Comment by amoeba** [comment]
👌
