### ISSUE TITLE
update DOI registrations with complete metadata

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1267]
Our current approach of registering DOIs through EZID produces an incomplete metadata record, and mangles authors and other critical information.  For this ticket, review and update our DOI library to submit complete DataCite metadata, with all authors.  Let's review our current submissions and decide what needs to be changed.

**Comment by taojing2002** [comment]
We decided to phase this issue. The first step is to handel eml objects. See this ticket:
https://github.com/NCEAS/metacat/issues/1293

**Comment by mbjones** [comment]
I just upped the priority on this DOI registration metadata to critical so we stop ignoring it.  @ThomasThelen @csjx @laurenwalker @taojing2002 this is the issue I was referring to o the call.

**Comment by jeanetteclark** [comment]
Is there a plan to fix existing mangled EZID records? I'd like to generate a bunch of citations to datasets using `rcrossref` and this issue prevents me from doing so

**Comment by ThomasThelen** [comment]
Just to chime in with an example about the authors.

It looks like we're setting `creator` to a semi-colon separated list which is valid for some citation formats, but not for others (like bibbtek).

For example, using [this](https://ezid.cdlib.org/id/doi:10.5063/F1S46Q72) identifier, generate a bibtek citation [here](https://citation.crosscite.org/).

You should get 
```
@misc{National Center For Ecological Analysis And Synthesis;Thiessen-Bock, Robyn_2019, title={Estimate of total Alaskan salmon abundance by region, 2000-2015}, url={https://knb.ecoinformatics.org/view/doi:10.5063/F1S46Q72}, DOI={10.5063/f1s46q72}, publisher={KNB Data Repository}, author={National Center For Ecological Analysis And Synthesis;Thiessen-Bock, Robyn}, year={2019} }

```

Note that the `author` field shows what was in the `creator` field at EZID, but the values aren't separated by `and` (it should be something along the lines of `National Center For Ecological Analysis And Synthesis and Thiessen-Bock, Robyn`)

**Comment by jeanetteclark** [comment]
It is also takes the `organizationName` instead of the `individualName` if both are present, for some reason.

**Comment by mbjones** [comment]
@ThomasThelen we should definitely be regenerating the DOI metadata once these bugs are fixed so that DataCite has a correct citation metadata.  @taojing2002 was working on this last I knew.

**Comment by mbjones** [comment]
@taojing2002 can you please update the status on this critical DOI registration bug? When is it expected to be in production and DataCite entries fixed?

**Comment by taojing2002** [comment]
Hi Matt:

The implementation hasn't been finished yet. But very close. It has been 
delayed by upgrading the OS. CNs OS upgrading will be done on the next 
week. So I think can I start the work on Monday, May 13. If we want this 
fix out as soon as possible, it can be on the production on the end of 
the week of May 13, I think.

Jing

**Comment by taojing2002** [comment]
Here is my understanding:

Support `datacite 3.1`
Fields will include -

`identifier`
`creators`
	`creator` - person w/o affiliated organization, w/o nameIdentifier; organization (name)
`titles `
   `title` ( with the attribute `language` -required )
`publisher`
`publicationYear`
`subjects` 
	`subject` ( with the attribute `language`)
`language `
`resourceType` - Dataset (Metadata)
`version `
`descriptions` 
	`description`( with the attribute `language`,` type`=abstract)
`size`
`formats`
	`format` - media type

In 2.10.3 release, we only support the EML objects by using the DataPakcage class from the datamanager_0.90.jar file.

However Dave suggested a new approach - get the needed information by parsing the returned result from the CN API call -  `CNDiagnostic.echoIndexdObject`.

- Using the datamanager
     pros:
         1. Local calls without involving a network

     cons:
         1. Only supporting one metadata standard. We should add new classes for new metadata standards.
         2. Not having information about - `subject`, `language`, `version`, `description` (abstract) in the 
             current datamanager release. We need to release a new version.


- Using the CN API call
       pros:
           1. Supporting multiple metadata standards. One class will support all metadata standards. We 
               can still reuse the code when the performance of local indexing dramatically improves and we 
                can get index information locally.
         cons:
            1. Performance issue since it involves a network call. I tested the call by a complete EML example 
                and it took less than one second. We may put this routine into another thread so it would not 
                block the response.
             2. Overwhelming the CN by enormous requests. Since every update, create and 
                 updateSystemmetadata request which involves DOI can trigger calling 
                 CNDiagnostic.echoIndexdObject.
              3. No `language` information

@mbjones what do you think?

**Comment by mbjones** [comment]
Thanks, Jing.

For the fields list, the other thing I would add to the DataCite list are cites/citedBy, isNewerVersionOf, and isDerivedFrom properties to link to other data sets in the DataCite record. Some of that is in our ORE files, and some in our sysmeta, and some in our upcoming EML 2.2 release.  This could be added as a separate feature request once you get the basic DataCite registration working correctly.

I think that we should not add a CN dependency into Metacat -- we are still shipping Metacat as a standalone platform that can be used independently of DataONE, and so we shouldn't depend on DataONE CN functions for basic CRUD operations in the local Metacat.

**Comment by taojing2002** [comment]
Thanks, Matt.

**Comment by taojing2002** [comment]
@mbjones @csjx 
On the 2.10.3 release, we only have those basic elements. The relationship elements will be added by another feature requests as Matt suggested. Here is the link of the datacite information of an eml example:

https://ezid.cdlib.org/id/doi:10.5072/FK2CC13974

I added some fake names and contents on the example eml. :). For example, `Ed` is a last name :)
Please review it at your convenience. There is a link to the entire datacite xml file on the above page.

Now we set the value of the `resourceType` to `metadata`
```
<resourceType resourceTypeGeneral="Dataset">metadata</resourceType>
```
Matt's example is:
```
<resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
```
I am thinking if we can do this way:
```
<resourceType resourceTypeGeneral="Dataset">eml://ecoinformatics.org/eml-2.0.0</resourceType>
```

**Comment by taojing2002** [comment]
On today's dev meeting, we discussed the `resourceType` issue and came up with an agreement:
`<resourceType resourceTypeGeneral="Dataset" />`

**Comment by taojing2002** [comment]
New example after modifying the resourceType:
https://ezid.cdlib.org/id/doi:10.5072/FK2NV9JT20

**Comment by taojing2002** [comment]
I regenerated the data cite metadata for all EML objects on KNB and GOA after deployed Metacat 2.10.3.
Here is an example:
https://ezid.cdlib.org/id/doi:10.5063/F1S46Q72

Here is the result from datacite search for the same doi:
https://search.datacite.org/works?query=doi%3A10.5063%2FF1S46Q72

Note: the search result just shows part of the metadata. For example, it doesn't show the affiliation information even thought it has.
