### ISSUE TITLE
Certificate Metacat compatible with the version 9.6/10 of PostgreSQL

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1270]
Currently Metacat works well with Postgres 9.2/9.3. 
Based on the postgres end of life support, we definitely need to move up:

https://www.postgresql.org/support/versioning/

Seems like compatibility with 9.6 and 10 would be critical, and 9.5 and 9.4 would be useful

**Comment by taojing2002** [comment]
I use postgres.app (https://postgresapp.com/) to install Postgres 9.6, 10 and 11 on Mac.
Then I ran junit test against the three servers undert Tomcat 8. All junit tests passed (except two integration tests) against the three versions of Postgres (9.6, 10 and 11).
It seems that Postgres has a very good backward capability.

**Comment by mbjones** [comment]
That's great, @taojing2002.  Could you update the installation documentation to indicate that people can use any of those versions, and that the newer versions are preferred?

Should we upgrade our postgres databases to version 11 on KNB and Arctic Data Center?

**Comment by taojing2002** [comment]
The documentation is updated. 
Ubuntu 18 only comes with Postgres 10. So we may need to upgrade OS first.
