### ISSUE TITLE
EML Attribute XSLT re-using anchors in such as way that they're not unique / changing attribute tabs doesn't for some entities

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1273]
The data team pointed this out to me. Visit https://arcticdata.io/catalog/#view/urn:uuid:d176be87-9b37-4902-8c87-bb762513320c
and go to the second entity, `SUMup_datasets_july2018_density.nc`.

Notice two things:

1. The Longitude (and other attribute), have anchors of `entity_1_attribute_3` I think it should be `entity_2_attribute_3` because it's the third attribute on the second entity.
2. Changing the tabs, but only on this entity, doesn't work. This could be a MetacatUI issue, or an interaction between Metacat's View Service and MetacatUI.

**Comment by jagoldstein** [comment]
Here is the newest version of the data package, which still has the same issue:
https://arcticdata.io/catalog/#view/urn:uuid:8df8298d-813d-4354-8c03-ddeccf5d255b

I haven't seen symptoms of this bug crop up in any other data package yet.

Fixing the display of this EML in the MetacatUI metadata view is a priority from the support team perspective since we are planning to mint a DOI and publish this one tomorrow. First, we plan to add provenance relationships and are hoping that won't complicate the debugging process nor cause any other issues

**Comment by amoeba** [comment]
Go ahead and work up prov, I expect that won't interact. I'll see if we can't get this tasked out to a dev today. I'm hoping it's a quick fix.

**Comment by jagoldstein** [comment]
thanks @amoeba

**Comment by amoeba** [comment]
Looks like at least the anchor collision is caused by the logic in the eml-dataset.xsl. Entity indexes are calculated per entity type, not globally for all entities. For example:

https://github.com/NCEAS/metacat/blob/71440f59a70dc391a979cdeb9f6ca25456a21d3b/lib/style/skins/metacatui/eml-2/eml-dataset.xsl#L620-L626

I'll try just calculating the index globally instead of per type first.

**Comment by amoeba** [comment]
Decided it'd be smart to confirm that fixing the anchors fixes the problem and it does. Working on the XSLT changes now which look doable.

**Comment by amoeba** [comment]
Zero luck on this yet, @jagoldstein. I'm still trying to get my dev environment set up to test my code changes so it'll be today or tomorrow (more likely).

**Comment by amoeba** [comment]
I think I got this. I'll do a real test on test.arcticdata.io in a few.

**Comment by amoeba** [comment]
@jagoldstein can you test this for me? https://test.arcticdata.io/view/urn:uuid:0d398bc9-405b-4319-a263-734ecf151dbf If the tabs work now we can deploy to arcticdata.io tomorrow AM. Sorry I took so long!

**Comment by jagoldstein** [comment]
@amoeba yes! the tabs work for this package on the test node. please deploy to arcticdata.io. thank you!

**Comment by amoeba** [comment]
👍 will do asap this am

**Comment by amoeba** [comment]
Deployed the updated view service to arcticdata.io just now. https://arcticdata.io/catalog/#view/doi:10.18739/A2JH3D23R looks good to me! Please re-open if that's not the case.

**Comment by jagoldstein** [comment]
sweet! lookin' good. thanks again @amoeba
