### ISSUE TITLE
Various XSLT errors with various processors. Can anyone reproduce these issues?

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1274]
Not sure if this is an issue with my setup, or an issue with the metacatui skin XSLTs.

When I run various XSLT processors,

- xalan-j
- saxon
- xmlstarlet
- xsltproc

I get various errors about variables not being defined. Here's an example:

```
xalan -IN ~/Downloads/science_metadata.xml -XSL lib/style/skins/metacatui/eml-2/emlroot.xsl
file:///Users/bryce/src/metacat/lib/style/skins/metacatui/eml-2/eml-identifier.xsl; Line #140; Column #44; org.apache.xml.utils.WrappedRuntimeException: Could not find variable with the name of packageURI

(Location of error unknown)XSLT Error (javax.xml.transform.TransformerException): No xml-stylesheet PI found in: /Users/bryce/Downloads/science_metadata.xml
Exception in thread "main" java.lang.RuntimeException: No xml-stylesheet PI found in: /Users/bryce/Downloads/science_metadata.xml
	at org.apache.xalan.xslt.Process.doExit(Process.java:1155)
	at org.apache.xalan.xslt.Process.main(Process.java:1128)
```

@tao or someone else, could you try transforming https://gist.github.com/amoeba/12274086f473e15188c16eebba5c62a7 through the eml-2 stylesheets with whatever XSLT processors you like? On my system, I prefer to use xalan-j because I know Metacat packages that to do its XSLT processing.

FYI: My `xalan` "binary" is a shell script that calls `java -cp ... org.apache.xslt.Process -IN ... -OUT`.

If I comment out the code in question, I can eventually get the XSLT transformation to work.

**Comment by mbjones** [comment]
Did you set the variables?  Our style sheets require them, and our software sets them when the XSLT processor is invoked.

**Comment by amoeba** [comment]
Ah, sure didn't. For the last few years, I haven't had to set any variables and running the above xalan command worked fine. Do you think the errors are dependent on the document and maybe it's just something unique about this one?
