### ISSUE TITLE
Data packages marked as replicationAllowed do not get indexed after they are modified

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacat#1277]
We have a number of data packages that are replicated and noticed that when we add data files via MetacatUI the entire resource map goes missing and the data files appear lost in the UI.  A little investigative work shows that a resource map is created but for some reason it is not index.  

### The Issue
The test data package [Ecosys Output for Barrow](https://data-dev.ess-dive.lbl.gov/#view/ess-dive-1e51ee20381d44d-20180829T181802450) was previously published and replicated on the ESS-DIVE dev system.  I added three new data files and they never showed up in the final version

However, I was able to find a [resource map](https://data-dev.ess-dive.lbl.gov/catalog/d1/mn/v2/object/ess-dive-47760167f459d46-20180829T181807530) that references the updated EML file (See ess-dive-47760167f459d46-20180829T181807530).  I found it by searching v2/object api for resource maps created today. ( See [v2/object?fromDate=&formatId=](https://data-dev.ess-dive.lbl.gov/catalog/d1/mn/v2/object?fromDate=2018-08-29T00:00:00.000&formatId=http://www.openarchives.org/ore/terms))

### The Fix
In production, I was able to fix this issue on data package [ Estimates of Monthly CO2 Emissions and Associated 13C/12C Values from Fossil-Fuel Consumption in the U.S.A.](https://data.ess-dive.lbl.gov/#view/ess-dive-9dbb887ee8f13fd-20180828T195338884) by creating a new resource map manually that is not set to replicate.  The resource map was then indexed successfully.  Afterward, I needed to go back and update the resource map to replicate.

### The Question
Do resource maps marked as replicate not get indexed?

### Obsolescence chain for test package doi:10.15485/1356055
```
search by ID: doi:10.15485/1356055
id=ess-dive-1e51ee20381d44d-20180829T181802450 seriesId=doi:10.15485/1356055
	formatType=METADATA
	title=Ecosys Output for Barrow
	obsoletes=ess-dive-1e51ee20381d44d-20180625T143228115
	obsoletedBy=
	resourceMap=
	documents=
	isDocumentedBy=
id=ess-dive-1e51ee20381d44d-20180625T143228115 seriesId=doi:10.15485/1356055
	formatType=METADATA
	title=Ecosys Output for Barrow
	obsoletes=ess-dive-1e51ee20381d44d-20180618T220819355
	obsoletedBy=ess-dive-1e51ee20381d44d-20180829T181802450
	resourceMap=['ess-dive-b8e3670bcf05b7f-20180625T143234735']
	documents=['ess-dive-c7e21fc49ea769e-20180625T143019583', 'ess-dive-ff3548ec10ba92a-20180330T192903805']
	isDocumentedBy=
id=ess-dive-1e51ee20381d44d-20180618T220819355 seriesId=doi:10.15485/1356055
	formatType=METADATA
	title=Ecosys Output for Barrow
	obsoletes=ess-dive-1e51ee20381d44d-20180330T195330088
	obsoletedBy=ess-dive-1e51ee20381d44d-20180625T143228115
	resourceMap=['ess-dive-b3ef2dfcbb9c881-20180618T220826574']
	documents=['ess-dive-ff3548ec10ba92a-20180330T192903805']
	isDocumentedBy=
id=ess-dive-1e51ee20381d44d-20180330T195330088 seriesId=doi:10.15485/1356055
	formatType=METADATA
	title=ecosys output for Barrow
	obsoletes=ess-dive-1e51ee20381d44d-20180330T124753336770
	obsoletedBy=ess-dive-1e51ee20381d44d-20180618T220819355
	resourceMap=['ess-dive-65939a1376074d7-20180330T195332883']
	documents=['ess-dive-ff3548ec10ba92a-20180330T192903805']
	isDocumentedBy=
id=ess-dive-1e51ee20381d44d-20180330T124753336770 seriesId=doi:10.15485/1356055
	formatType=METADATA
	title=ecosys output for Barrow
	obsoletes=ess-dive-0333c0922d36ce4-20180330T194719590
	obsoletedBy=ess-dive-1e51ee20381d44d-20180330T195330088
	resourceMap=['ess-dive-79d8ef2ac974f44-20180330T124800092685']
	documents=['ess-dive-ff3548ec10ba92a-20180330T192903805']
	isDocumentedBy=
id=ess-dive-0333c0922d36ce4-20180330T194719590 seriesId=
	formatType=METADATA
	title=ecosys output for Barrow
	obsoletes=ess-dive-fadd7ac44b61dd1-20180330T193404245
	obsoletedBy=ess-dive-1e51ee20381d44d-20180330T124753336770
	resourceMap=['ess-dive-8b4362622f440d0-20180330T194723490']
	documents=['ess-dive-ff3548ec10ba92a-20180330T192903805']
	isDocumentedBy=
id=ess-dive-fadd7ac44b61dd1-20180330T193404245 seriesId=
	formatType=METADATA
	title=ecosys output for Barrow
	obsoletes=ess-dive-635844288aba421-20180330T192816713
	obsoletedBy=ess-dive-0333c0922d36ce4-20180330T194719590
	resourceMap=['ess-dive-0ef2a5a1a4e9316-20180330T193405708']
	documents=['ess-dive-ff3548ec10ba92a-20180330T192903805']
	isDocumentedBy=
id=ess-dive-635844288aba421-20180330T192816713 seriesId=
	formatType=METADATA
	title=ecosys output for Barrow
	obsoletes=
	obsoletedBy=ess-dive-fadd7ac44b61dd1-20180330T193404245
	resourceMap=['urn:uuid:49315834-b167-48e1-a8f3-548e0ddb12e7']
	documents=['ess-dive-ff3548ec10ba92a-20180330T192903805']
	isDocumentedBy=

```

**Comment by taojing2002** [comment]
@vchendrix Val, the missing indexing happened on Metacat or the CN?

**Comment by vchendrix** [comment]
My guess is both.  But for sure the Member Node.  This issue is that is
seems like once a data package is replicated or marked to replicate
subsequent resource maps are not index.  To the MetacatUI user it looks
like all of their data is lost.

**Comment by taojing2002** [comment]
@vchendrix Thanks Val. Would you please set the debug level to debug for the metacat-index, then use the api method - "reindex" to index the resource map again? I would like to see the error message on the catalina.out file. 
The log4j.properties file locates on metacat-index/WEB-INF/class.

**Comment by vchendrix** [comment]
@mbjones @csjx @taojing2002 I am able to consistently replicated this now on our development server which has replication enabled.  (See https://data-dev.ess-dive.lbl.gov/). This issue seems like is could be  isolated to MetacatUI but I will let you guys decide that.

I can give you read/write access to this server if you give me the Orcid that you would like to authenticate with. 

I started out with a new data package created via the REST interface using python scripts with:
- some number of data files
- a series id
- replicationAllowed 
- a public/read access policy. 

If I add a file via MetacatUI, the data files look like they are missing.  Here is the 
[ log output](https://github.com/NCEAS/metacat/files/2362291/indexing-problem-single-package.log) from this action. No significant errors seem to be thrown. See the dataset here: https://data-dev.ess-dive.lbl.gov/#view/ess-dive-1ea57f59ba1c2da-20180907T191657662

If I add a file using my python scripts, there are no problems. See an example dataset here: https://data-dev.ess-dive.lbl.gov/#view/ess-dive-2304e8cbcd6b31f-20180907T115624288670

_**NOTE: the data package must have all three: a series id, replicationAllowed and a public/read access policy for this issue to surface.**_

**Comment by taojing2002** [comment]
Hi Val: my orcid is http://orcid.org/0000-0002-1209-5268

Thanks,
Jing

**Comment by vchendrix** [comment]
@taojing2002 I have added  you to https://data-dev.ess-dive.lbl.gov

**Comment by vchendrix** [comment]
Closing this issue.  It is a problem with MetacatUI.

1) replica elements are copied over to the new resource map in Metacat UI.  
2)  There seems to be a timing issue WRT to indexing metadata files and resource maps in metacat ui.

**Comment by vchendrix** [comment]
In production.  These were fixed by indexing the metadata and resource map individually

+ https://data.ess-dive.lbl.gov/#view/doi:10.3334/CDIAC/LUE.NDP055.2007
+ https://data.ess-dive.lbl.gov/#view/doi:10.3334/CDIAC/ATG.002
