### ISSUE TITLE
Project abstract displays oddly

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1279]
From https://github.com/NCEAS/metacatui/issues/761

For data packages that have project information, the display for the project abstract is off. It seems that there should be a bounding box like the other fields.

![image](https://user-images.githubusercontent.com/6643222/45317017-b7a0cc80-b506-11e8-879d-c9a33c0cea93.png)

**Comment by amoeba** [comment]
Closed by https://github.com/NCEAS/metacat/commit/b6daceffc93a41b317c6ef67e3bc3b407b850f26.
