### ISSUE TITLE
StackOverflow in Xerces on MNStorage.create() and then the calls hangs

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1280]
For some EML records with long geographicCoverage `geographicDescription` (see [gist](https://gist.github.com/amoeba/f250d1bc04ce82fb4fc68b4b32ec8528)), a POST to /object (MNStorage.create) never succeeds. catalina.out reports a StackOverflow in Xerces:

```
Exception in thread "ajp-bio-8009-exec-37" java.lang.StackOverflowError
	at org.apache.xerces.impl.xpath.regex.RegularExpression.matchString(Unknown Source)
...continues infinitely
```

It appears that a 7000 character description is fine but a 7499 character one doesn't. I suspect that's diagnostically helpful. A gist'ed a portion of catalina.out along with the offending EML record:

https://gist.github.com/amoeba/f250d1bc04ce82fb4fc68b4b32ec8528

A 7499-character `geographicDescription` is long, but I think not entirely unreasonable so it'd be nice to see the behavior here be that the call either succeed or fail, rather than hangs seemingly indefinitely. I saw this behavior on dev.nceas if that's helpful in debugging and did the `MNStorage.create` from R with `arcticdatautils::publish_object(...)`.

**Comment by robyngit** [comment]
In case it's helpful, the limit seems to be 7394 characters for both the `geographicDescription` field and the `attributeDefinition` field.

**Comment by amoeba** [comment]
Thanks @robyngit 	

I was just thinking about this and a good way to debug this would be to use a much simpler XSLT to see if its just the way we've written the XSLTs that's causing the issue.

**Comment by taojing2002** [comment]
It is fixed by upgrade the xerces version
