### ISSUE TITLE
publish API is not updating the resource map with the new DOI

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1287]
In MetacatUI, we display a "Publish with a DOI" button. When clicked, MetacatUI sends a PUT request to `/d1/mn/v2/publish/{pid}`. Previously, that publish service would update the EML with a DOI identifier and the resource map would be updated to aggregate the new DOI.

Right now, the EML is successfully being updated with a DOI but the resource map is not. So there is a bug somewhere that is preventing the resource map from updating correctly.

**Comment by taojing2002** [comment]
Using both curl command and the 2.2.2 version of online metadata editor, the publish method worked fine.
