### ISSUE TITLE
Bad timing of indexing after package save causes data files to disappear

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1288]
This was originally reported by Val Hendrix on the MetacatUI repo, but since this is an indexing bug, I am moving it to Metacat.

----

We have a number of data packages that are replicated and noticed that when we add data files via MetacatUI the entire resource map goes missing and the data files appear lost in the UI. A little investigative work shows that a resource map is created but for some reason it is not index. 

### The Issue
The test data package *Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude** was previously published and replicated on the ESS-DIVE dev system. I added one  data files and they never showed up in the final version

However, I was able to find a resource map that references the updated EML file (See https://data-dev.ess-dive.lbl.gov/view/ess-dive-fff1eb14535fc7b-20181005T215140258). I found it by searching v2/object api for resource maps created today. ( See v2/object?fromDate=&formatId=)

The Fix
In production, I was able to fix this issue on data package Estimates of Monthly CO2 Emissions and Associated 13C/12C Values from Fossil-Fuel Consumption in the U.S.A. by creating a new resource map manually that is not set to replicate. The resource map was then indexed successfully. Afterward, I needed to go back and update the resource map to replicate.

The Question
Do resource maps marked as replicate not get indexed?
```
Search by ID: doi:10.3334/CDIAC/FFE.NDP058.2016.test1
id=ess-dive-e36d820b3c260ca-20181005T215135666 seriesId=doi:10.3334/CDIAC/FFE.NDP058.2016.test1
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-e36d820b3c260ca-20181005T131737934298
	obsoletedBy=
	resourceMap=
	documents=
	isDocumentedBy=
id=ess-dive-e36d820b3c260ca-20181005T131737934298 seriesId=doi:10.3334/CDIAC/FFE.NDP058.2016.test1
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-4d2c097b534e485-20180320T153359785396
	obsoletedBy=ess-dive-e36d820b3c260ca-20181005T215135666
	resourceMap=['ess-dive-c47d7d15547a284-20181005T131749259423']
	documents=['ess-dive-e36d820b3c260ca-20181005T131737934298']
	isDocumentedBy=['ess-dive-e36d820b3c260ca-20181005T131737934298']
id=ess-dive-4d2c097b534e485-20180320T153359785396 seriesId=
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-c2f62cf0f76c5f1-20180320T152034768435
	obsoletedBy=ess-dive-e36d820b3c260ca-20181005T131737934298
	resourceMap=['ess-dive-3f852a3976a249e-20180320T153402137125']
	documents=['ess-dive-4d2c097b534e485-20180320T153359785396']
	isDocumentedBy=['ess-dive-4d2c097b534e485-20180320T153359785396']
id=ess-dive-c2f62cf0f76c5f1-20180320T152034768435 seriesId=doi:10.3334/CDIAC/FFE.NDP058.2016
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-ee6d90a94e626c8-20180320T151704924357
	obsoletedBy=ess-dive-4d2c097b534e485-20180320T153359785396
	resourceMap=['ess-dive-158fb2413fc7932-20180320T152037574624']
	documents=['ess-dive-c2f62cf0f76c5f1-20180320T152034768435']
	isDocumentedBy=['ess-dive-c2f62cf0f76c5f1-20180320T152034768435']
id=ess-dive-ee6d90a94e626c8-20180320T151704924357 seriesId=
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=
	obsoletedBy=ess-dive-c2f62cf0f76c5f1-20180320T152034768435
	resourceMap=['ess-dive-cbaf965a4d3b3b4-20180320T151705604630']
	documents=['ess-dive-ee6d90a94e626c8-20180320T151704924357']
	isDocumentedBy=['ess-dive-ee6d90a94e626c8-20180320T151704924357']
```

### Reproducing the Issue
I am able to consistently reproduce this now on our development server which has replication enabled. (See https://data-dev.ess-dive.lbl.gov/). This issue seems like is could be isolated to MetacatUI but I will let you guys decide that.

I can give you read/write access to this server if you give me the Orcid that you would like to authenticate with.

I started out with a new data package created via the REST interface using python scripts with:

- some number of data files
- replicationAllowed ( and has been replicated): if the package is marked as replicated but has not been replicated yet then the problem will be temporary (until metacat fixes things on its own)
- a public/read access policy.
- a series id

**NOTE: the data package must have all three: a series id, replicationAllowed and a public/read access policy for this issue to surface.**

**Comment by taojing2002** [comment]
Val confirmed that the issue was fixed after a new d1_index_processor jar file was deployed.
