### ISSUE TITLE
Add Methods section heading to metadata view

### ISSUE THREAD

**Issue by drkrynstrng** [NCEAS/metacat#1289]
There does not appear to be a Methods section heading in the metadata view, which makes it look like methods/sampling information is under another heading. Adding a section heading would add clarity and make this information slightly easier to find.

For example, here the methods information appears to be under the Temporal Coverage section:
![image](https://user-images.githubusercontent.com/36723171/47111069-62439380-d207-11e8-9f19-009106c0e544.png)

**Comment by amoeba** [comment]
Looks like this was fixed in 778ffc2fd53c6737b6c04b6512d9f56caca7972c.
