### ISSUE TITLE
Update DOI registrations for EML objects with complete metadata

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1293]
This ticket is the first step of this ticket:
https://github.com/NCEAS/metacat/issues/1267

**Comment by taojing2002** [comment]
We parse the eml document to get creators and the title. The creators will be separated by `,`. It can be a person's name - `givenName surName` or an organization name. It contains the completed list of the creator on the EML object.

**Comment by mbjones** [comment]
Jing, in reviewing this I see you are using a comma as a separator between authors, whereas I think EZID expects them to be delimited by a semicolon.  

From https://ezid.cdlib.org/doc/apidoc.html#profile-datacite:
`datacite.creator`
- The main researchers involved in producing the data, or the authors of the publication in priority order. Each name may be a corporate, institutional, or personal name. In personal names list family name before given name, as in: Shakespeare, William
- Separate multiple names with ";". 
- Non-roman names should be transliterated according to the ALA-LC schemes.

Can you verify and if I am right, correct it to use a semicolon before the release goes out?  Thanks.

**Comment by taojing2002** [comment]
@mbjones You are right. I changed the delimiter to ";".  And also the personal name format has been changed to:
familyName, givenName

The commits are (including the change on the junit test):

11b50b8429063b829976042fb6aa1715f3eb8386
51fef5e11cea8e98c634d6941bde122528231d8f

**Comment by taojing2002** [comment]
metamattj [3:20 PM]
@tao can you let me know where we stand on https://github.com/NCEAS/metacat/issues/1267?  It seems you started to work o it but I’m ot sure if it has been completed.   When I look at a recent EML record i DataCite, the citation metadata is still very wrong and incomplete.  See for example: https://search.datacite.org/works/10.5063/f1b856fh

**Comment by taojing2002** [comment]
Seems like we choose the organization name if a create has both personal information (first, last name) and organization information.

**Comment by mbjones** [comment]
Yeah, that seems to be a problematic algorithm.  We should use the full name. Ideally, we would like to include other details for the individual, including their email, affiliation, and ORCID, if we have them.  I don't think the simple EZID API supports that -- we'd have to move to providing a full DataCite kernel metadata record, which might look like this for the example record cited above:

```xml
<?xml version="1.0"?>
<resource xmlns="http://datacite.org/schema/kernel-4"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="...">
<identifier identifierType="DOI">(:tba)</identifier>
<creators>
    <creator>
        <creatorName nameType="Organizational">United States Census Bureau</creatorName>
    </creator>
    <creator>
        <creatorName nameType="Personal">Bachtel, Juliet</creatorName>
        <givenName>Juliet</givenName>
        <familyName>Bachtel</familyName>
        <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0003-0003-2515</nameIdentifier>
        <affiliation>National Center for Ecological Analysis and Synthesis</affiliation>
    </creator>
    <creator>
        <creatorName nameType="Personal">Randazzo, John</creatorName>
        <givenName>John</givenName>
        <familyName>Randazzo</familyName>
        <affiliation>National Center for Ecological Analysis and Synthesis</affiliation>
    </creator>
    <creator>
        <creatorName nameType="Personal">Gavenus, Erika</creatorName>
        <givenName>Erika</givenName>
        <familyName>Gavenus</familyName>
    </creator>
</creators>
... more DataCite elements go here....
</resource>
```

This type of a DataCite kernel metadata record can be submitted as described in the [EZID API](https://ezid.cdlib.org/doc/apidoc.html#metadata-profiles): 'Alternatively, an entire XML document adhering to the DataCite Metadata Scheme schema may be bound to the metadata element "datacite"'.   Thus, to submit this type of full metadata, one would first construct a full datacite metadata xml document, and then pass it to EZID using the `datacite` profile within the `datacite` element. Be sure to hex-escape newlines and other special characters as described in the EZID API.  So the name-value pair would look like:

`datacite: <?xml version="1.0"?>%0A<resource...`

This may require a minor extension to the `ezid` java library to support the `datacite` element, but we'll need to check.

**Comment by mbjones** [comment]
@taojing2002 I updated the `ezid` library to version 1.0.2 which adds some tests that show how to use the DataCite xml format for uploading more detailed metadata to EZID.  I found out that EZID only supports DataCite 3.1 for now, but I added both a 3.1 and 4.2 example XML documents to the tests resources.  You ca see this in action here: https://github.com/NCEAS/ezid/blob/master/src/test/java/edu/ucsb/nceas/ezid/test/EZIDServiceTest.java#L176

**Comment by taojing2002** [comment]
Thanks, Matt!

**Comment by taojing2002** [comment]
c3d77bb84f24a04b35ba7cad0fdec73cf71b6c27
