### ISSUE TITLE
"Methods" section appears as if it is within "Project Information"

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1295]
Manually copied from https://github.com/NCEAS/metacatui/issues/828 filed by @jagoldstein

In the metacatUI metadata view, the `methods` section of EML appears as if it is a subcategory beneath `project`. Please see this example from https://arcticdata.io/catalog/#view/doi:10.18739/A2901ZF74:

<img width="1089" alt="screen shot 2018-11-06 at 3 10 28 pm" src="https://user-images.githubusercontent.com/18270215/48100000-67787a80-e1d6-11e8-8662-e04d85aabfd1.png">

The "Methods" header should be larger and bold so that it is clearly seen as its own category rather than a sub-header.

Here is another example from the CN (https://search.dataone.org/view/urn:uuid:054536f3-205f-4441-ac01-3f93b81665ea) where the `methods` appear to be a subcategory beneath `taxonomicCoverage`:

<img width="1472" alt="screen shot 2018-11-06 at 3 15 54 pm" src="https://user-images.githubusercontent.com/18270215/48100167-000efa80-e1d7-11e8-81d8-faf4b68845ad.png">

**Comment by jagoldstein** [comment]
the view in this example is much preferred:

https://neutral-cat.nceas.ucsb.edu/view/urn:uuid:06e37992-6074-4690-b947-37f95a7a3497

**Comment by amoeba** [comment]
Great, done in 778ffc2fd53c6737b6c04b6512d9f56caca7972c. I'll coordinate with @csjx 	on getting this updated on arcticdata.io.

Thanks for the bug report.

**Comment by amoeba** [comment]
Hot-patched arcticdata.io so this change is live now. https://arcticdata.io/catalog/#view/doi:10.18739/A2901ZF74 and its friends look better now!

**Comment by jagoldstein** [comment]
thanks again @amoeba ! lookin' good

**Comment by jagoldstein** [comment]
@amoeba can this fix be applied to test.arcticdata.io too please?

**Comment by amoeba** [comment]
Sure thing. Just did it @jagoldstein .

**Comment by jagoldstein** [comment]
excellent, thank you
