### ISSUE TITLE
Review and consolidate logging frameworks

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacat#1297]
We started using Log4J as a logging framework prior to the creation of Apache Commons Logging, but have since started using the Commons Logging factory to get logger instances in many newer Metacat classes.  Because we're not fully consistent, being able to swap out the implementation (like Logback instead of Log4J) isn't possible for an individual developer.

Do a review of the logging frameworks and see if they are compatible with Commons Logging.  Dave mentioned that Logback supports JSON serialization of logs, which may be useful for DataONE nodes.

If Commons Logging is the preferred facade API, replace all Log4J-specific calls across the source code base with Commons Logging calls.  Also, ensure we have no `System.out.println()` calls lingering in the code.

**Comment by mbjones** [comment]
Related to #856, which shoul dbe closed as well when this is resolved.

**Comment by taojing2002** [comment]
Metacat already only uses the Commons Logging now. So this task is done.
