### ISSUE TITLE
optimize xml stylesheet transformation for view service

### ISSUE THREAD

**Issue by nahf** [NCEAS/metacat#1299]
the DBTransform class instantiates a new TransformerFactory and creates a Transformer from file for each call, even though the stylesheet files are a limit and static set.  Building a transformer from file is IO and computationally expensive, and by profiling, is responsible for 95% of the time performing the mn.view() call.

While Transformers are not reusable, TransformerFactories can build intermediate Templates that are, and do the time-consuming bits.  Transformers are then built from the Templates.

I implemented a static TemplatesMap in DBTransform from which specific Transformers can be built, and will create a feature branch and pull request.

**Comment by csjx** [comment]
Hi Rob @nahf  - There is a performance ticket (https://github.com/NCEAS/metacat/issues/1234) for this issue, so please add your comments over there so we keep this issue consolidated.
