### ISSUE TITLE
optimize userHasPermission in D1NodeService to reduce response time

### ISSUE THREAD

**Issue by nahf** [NCEAS/metacat#1300]
Most API calls rely on the isAuthorized() API method to determine authorization against the caller's Session.  The private userHasPermission routine calls CN.listSubjects and is therefore time-consuming because of the API call overhead.  (see issue #1187)

By rearranging the Subject comparisons, we can postpone these expensive checks until after the quick and easy checks are completed, and reduce the number of CN.listSubjects calls.

Additionally, the subject 'public' can be excluded from having its subjectInfo pulled by expandRightsholder.

I have refactored the method and plan to submit a pull request for the change.

**Comment by nahf** [comment]
I created a pull request with refactored authorization, consisting of 2 commits (so far)

https://github.com/NCEAS/metacat/pull/1307

**Comment by taojing2002** [comment]
Rob wrote the utility class to resolve the issue.
