### ISSUE TITLE
Error updating series ID on private dataset

### ISSUE THREAD

**Issue by FiannaOBrien** [NCEAS/metacat#1308]
Updating series ID before setting read to "public" returns the following error: 
`ERROR: id:ess-dive-b558693fc37ad78-20181206T235628830 message:'400 - In the MN.updateSystemMetadata method, the public-readable access rule shouldn't be removed for an DOI object ess-dive-d5c4ecdf747345f-20181219T162507170924 or SID doi:10.1234/5678'`

@vchendrix

**Comment by taojing2002** [comment]
We just introduced this feature - doesn't allow a object with an DOI be set to private (we assume an DOI is public readable.)
https://github.com/NCEAS/metacat/issues/1011

The assumption that the DOI objects always be public readable seems problematic. We should apply the rule when the DOI objects already are public readable.  If the DOI object are private, this rule should be skipped.
