### ISSUE TITLE
Upgrade metacat-index to support Jena v3

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1325]
Between `d1_index_processor` 2.3.8 and current trunk (2.4.0 series), its Jena dependency went from v2 to v3. `metacat-index` depends on `d1_index_processor` which uses Jena and also directly depends on Jena itself.

This is mostly a namespace change (`com.hp.hpl.jena` -> `org.apache.jena`) and it does break the `metacat-index` build when I bump the version of the `d1_index_processor` dep up to `2.4.0-SNAPSHOT`. In order for Metacat to take advantage of some recent changes in `d1_index_processor`, I think we'll want to bump the dep up to `2.4.0` and make `metacat-index` compatible at some point soon. There are some details about the migration [here](https://jena.apache.org/documentation/migrate_jena2_jena3.html).

Judging from the build output below, it looks like a few more changes were made in `d1_index_processor` that need some updating. None of them look problematic.

@taojing2002, do you have any objections to upgrading the dependency and making the necessary changes? Also, what `metacat-index` release would we like this to go in?

<details>
<summary>Build output</summary>

```
$ ant build-metacat-index
...snip...
[artifact:mvn] [ERROR] COMPILATION ERROR :
[artifact:mvn] [INFO] -------------------------------------------------------------
[artifact:mvn] [ERROR] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/SolrIndex.java:[1127,49] error: unreported exception IOException; must be caught or declared to be thrown
[artifact:mvn]
[artifact:mvn] [ERROR] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/annotation/MetacatRdfXmlSubprocessor.java:[179,69] error: cannot access Dataset
[artifact:mvn]
[artifact:mvn] [ERROR]   class file for org.apache.jena.query.Dataset not found
[artifact:mvn] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/annotation/MetacatRdfXmlSubprocessor.java:[279,64] error: incompatible types: com.hp.hpl.jena.query.Dataset cannot be converted to org.apache.jena.query.Dataset
[artifact:mvn]
[artifact:mvn] [ERROR] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/MetacatDocumentDeleteSubprocessor.java:[42,7] error: MetacatDocumentDeleteSubprocessor is not abstract and does not override abstract method getInstanceLabel() in IDocumentDeleteSubprocessor
[artifact:mvn]
[artifact:mvn] [INFO] 4 errors
[artifact:mvn] [INFO] -------------------------------------------------------------
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] BUILD FAILURE
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] Total time:  2.936 s
[artifact:mvn] [INFO] Finished at: 2019-02-25T13:58:01-09:00
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3:compile (default-compile) on project metacat-index: Compilation failure: Compilation failure:
[artifact:mvn] [ERROR] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/SolrIndex.java:[1127,49] error: unreported exception IOException; must be caught or declared to be thrown
[artifact:mvn] [ERROR]
[artifact:mvn] [ERROR] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/annotation/MetacatRdfXmlSubprocessor.java:[179,69] error: cannot access Dataset
[artifact:mvn] [ERROR]
[artifact:mvn] [ERROR]   class file for org.apache.jena.query.Dataset not found
[artifact:mvn] [ERROR] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/annotation/MetacatRdfXmlSubprocessor.java:[279,64] error: incompatible types: com.hp.hpl.jena.query.Dataset cannot be converted to org.apache.jena.query.Dataset
[artifact:mvn] [ERROR]
[artifact:mvn] [ERROR] /Users/bryce/src/metacat/metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/MetacatDocumentDeleteSubprocessor.java:[42,7] error: MetacatDocumentDeleteSubprocessor is not abstract and does not override abstract method getInstanceLabel() in IDocumentDeleteSubprocessor
...snip...
```
</details>

**Comment by amoeba** [comment]
On further inspection, I also noticed that `metacat-index` currently depends on `jena-tdb` 1.0.0 (released Sep. of 2013) and the most recent version is in the 3.10 series. `d1_index_processor` uses 3.7.0 (April 2018). At face value this sounds like a huge leap but it looks not lot a lot has changed between 1.x and 3.x. [Here](https://svn.apache.org/repos/asf/jena/branches/jena-owl2/doc/migrate1-2.html) is a migration guide for 1->2 which is similar to the 2->3 migration in that it's a namespace change with some minor (but breaking) changes to some of the APIs.

Changes to `jena-tdb` versions only affects the following files:

- metacat-index/src/main/java/edu/ucsb/nceas/metacat/index/annotation/MetacatRdfXmlSubprocessor.java
- src/edu/ucsb/nceas/metacat/annotation/BioPortalService.java
- src/edu/ucsb/nceas/metacat/annotation/DatapackageSummarizer.java
- test/edu/ucsb/nceas/metacat/annotation/BioPortalServiceTest.java
- test/edu/ucsb/nceas/metacat/util/AuthUtilTest.java
- test/edu/ucsb/nceas/metacat/util/SystemUtilTest.java

The first four are related to JSON and RDF/XML annotations and the last two are unused imports so it'd be good to make sure those classes are exercised well enough by a test or two to make sure annotations are still working as expected before releasing. I think this should catch the changes between v1->v2->v3.

**Comment by amoeba** [comment]
This was a quick change, but now I'm seeing an odd error in a test failure:

> [artifact:mvn] Tests in error:
> [artifact:mvn]   testProcessDocument(edu.ucsb.nceas.metacat.index.annotation.MetacatRdfXmlSubprocessorTest): Error creating bean with name 'resourceMapSubprocessor' defined in class path resource [application-context-resource-map.xml]: Instantiation of bean failed; nested exception is java.lang.VerifyError: class org.apache.solr.client.solrj.embedded.EmbeddedSolrServer overrides final method request.(Lorg/apache/solr/client/solrj/SolrRequest;)Lorg/apache/solr/common/util/NamedList;

Maybe more stuff changed in `d1_index_processor`. Looking into it now.

**Comment by taojing2002** [comment]
Thank you, Bryce for doing this. Just wondering if you work with the 
trunk of d1_index_process or the branch 2.3? If it is the trunk, there 
is any particular reason to do this?

**Comment by amoeba** [comment]
This is on trunk (https://redmine.dataone.org/projects/d1/repository/revisions/19297). It occurs to me I don't know how DataONE manages trunk vs. release branches. Is that change likely to get released at some point?

**Comment by taojing2002** [comment]
Rob is making a significant structural change on the d1_index_processor 
trunk and I am not sure when it will be released. If you want to your 
change to be released soon, it is better to work on the 2.3 branch which 
can quickly be packed into current Metacat release branch.

**Comment by amoeba** [comment]
Right on, thanks @taojing2002. I'll close this for now and we can re-open when that time comes.

**Comment by nahf** [comment]
I got a taste of the change to Jena 3.7.0 while doing some testing in d1_index_processor.  Once you use go to it, there's some initiation code that gets called, and you can run into runtime issues if your package uses the shade plugin to build an uber-jar.  What works is adding a transformer to the plugin in your pom as in the code example on this page:  https://jena.apache.org/documentation/notes/jena-repack.html

It also briefly describes how to do the work manually, if you are creating your own jar manually.  Basically all of the jena artifact jars have a file `META-INF/services/org.apache.jena.sys.JenaSubsystemLifecycle` in their jar which need to get exposed.

Here's a similar document which might provide some further background.
https://jena.apache.org/documentation/notes/system-initialization.html

**Comment by nahf** [comment]
I also started refactoring the foresite-java package to use the `org.apache` packages instead of the older `com.hp.hpl` ones.  I didn't commit, because it turns out that I didn't need to harmonize d1_libclient_java (which depends on foresite, which depends on com.hp.hpl.jena) to get the index processor 2 RDF subprocessors to work side by side.

Metacat has a fair sprinkling of `com.hp.hpl.jena` imports in them, too, so it looked like it would be a big change.

**Comment by amoeba** [comment]
Thanks for the notes @nahf!
