### ISSUE TITLE
Metacat at CNs keep accessing LDAP servers

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1340]
Recently we found that Metacats on CNs keep sending authorization requests to the ldap server and blow the ldap service at NCEAS. We configured Metacat to use the local ldap server instead. The NCEAS ldap server works fine now. But it still keeps sending request to local ldap server. We need to figure out why.

**Comment by taojing2002** [comment]
So far the MN seems not to cause any issues.

**Comment by taojing2002** [comment]
Data from Nick:
here’s a count of connections to the ldap server by hour for today
```01 100832
02 101517
03 90249
04 100915
05 88623
06 102985
07 121315
08 111519
09 115415
10 20154
11 32804
12 9761
13 21311
14 8175
15 16916
16 1124```

**Comment by nickatnceas** [comment]
Continuing the data from above, grepping for slapd "ACCEPT" in syslog:

16 22193
17 23300
18 18312
19 17446
20 16050
21 16219
22 16284
23 15270

2019-03-28
00 15650
01 14834
02 14511
03 15359
04 15432
05 14538
06 16860
07 16461
08 16377

**Comment by taojing2002** [comment]
This issue is fixed when we configure the cns to access its local ldap servers.
