### ISSUE TITLE
Re-index "replicationAllowed" to be searchable

### ISSUE THREAD

**Issue by HeshamElbashandy** [NCEAS/metacat#1342]
To be able to do a Solr query that only includes data objects that has `replicationAllowed`, the field should be searchable.

**Comment by taojing2002** [comment]
Chris also suggests we should make all of the system metadata fields searchable.

**Comment by taojing2002** [comment]
Those fields need to be changed:
```
checksum
checksumAlgorithm
replicationAllowed
numberReplicas
preferredReplicationMN
blockedReplicationMN
replicaVerifiedDate
```

**Comment by taojing2002** [comment]
a227e872a44c82762346b2746e5c1dc1b62fea8b
