### ISSUE TITLE
Reconfigure how Metacat runs the sitemap task

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1368]
Currently, sitemaps are implemented in a `Sitemap` class which inherits from `java.util.TimerTask` and handles the responsibility of querying the database for metadata records and writing sitemap XML files to the `./sitemaps` directory. Sitemaps are configured by default but not enabled.

When `MetacatServlet` inits, amongst many other things, it also inits `MetacatHandler` with a `java.util.Timer` which is later on used to schedule the Sitemap task. But at this point, the Sitemap task isn't scheduled to run.

The only way to get sitemaps to begin generating is to trigger `MetacatServerlet#handleGetOrPost` by sending an HTTP request to `/metacat/metacat` with any parameters (i.e., sitemaps are forcibly scheduled regardless of what `action` equals). At this point, `MetacatHandler`'s `java.util.Timer` instance is asked to schedule the Sitemap task unless it already is:

```java
timer.schedule(smap, firstDelay, sitemapInterval); // smap is a Sitemap instance
```

Is there a reason we had Sitemaps set up this way? I'd like to see this changes so that sitemaps, if configured, are on by default. We could add an admin API command, `regenerateSitemaps`, to force sitemaps to regenerate.

**Comment by mbjones** [comment]
Your changes sound good to me.  A config parameter with sitemaps on or off would be best, and Metacat should detect that param change while running (i.e., not require a Metacat or tomcat restart to pick it up).

**Comment by amoeba** [comment]
Great, I'll look into that.

**Comment by amoeba** [comment]
Heya @taojing2002 , I've [PR'd](https://github.com/NCEAS/metacat/pull/1393) this and could use a second pair of eyes. Do you think you could target this for the next Metacat release?
