### ISSUE TITLE
Refactor sitemap generation approach to be XML-aware

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1369]
I see 

```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">
<sitemap>
<loc> https://neutral-cat.nceas.ucsb.edu/sitemap1.xml </loc>
<lastmod>2019-07-16</lastmod>
</sitemap>
</sitemapindex>
```

and, from looking at the code, it looks like our attempt at making pretty-printed XML with string concatenation isn't working so well. Should be a quick fix.

**Comment by mbjones** [comment]
Are we using string concatenation to create XML?  I think that's a bad idea, and will likely produce XML with well-formedness problems when (not if) we encounter escaping situations we didn't anticipate.  Wouldn't it be reasonably easy to stream out through an XML parser rather than using string maninuplation?

**Comment by amoeba** [comment]
I think changing the implementation is reasonable. It's been strings-only for a long time AFAICT and I've never seen issues. When I went back in to the code last year I did add some additional XML-escaping to make it safer but I agree about the increased risk for escaping. This doesn't sound like a big task so I'll take a look.

**Comment by amoeba** [comment]
Alright, this is all done and working as expected. I refactored everything that generate XML strings to use the `DocumentBuilderFactory/DocumentBuilder/Document/etc` gang and tested how it handles URLs with PIDs with special characters and confirmed the underlying functionality of actually generating sitemaps works as expected.

I'll leave open and let the commit auto-close this when merged into master.

**Comment by amoeba** [comment]
Heya @taojing2002 , I've [PR'd](https://github.com/NCEAS/metacat/pull/1393) this and could use a second pair of eyes. Do you think you could target this for the next Metacat release?
