### ISSUE TITLE
Index a query string for collections

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1378]
We need to create a subprocessor for collection and portal documents that gets the `filter` elements and constructs a Solr query string. That string should be set as a value on a new Solr field. Our various tools will execute the query from that field to find the list of datasets in a collection.

The query will be constructed using the logic already completed in MetacatUI in FIlters.getQuery(): https://github.com/NCEAS/metacatui/blob/feature-project-editor/src/js/collections/Filters.js#L68

The GH with some additional documentation on how the query is constructed is here: https://github.com/NCEAS/metacatui/issues/1046

**Comment by gothub** [comment]
The `memberQuery` field has been added to the index, in commits
babfdadfe0503f4aadd0470a7307b71da46b9f36 
34a255b01c7516ce12a795afa4794e05142d43c8
b17de92febc2742d6eaa8b23b0d89ee2195073a5
