### ISSUE TITLE
Michner -> Michener on metacatui/about/sharing-your-data page

### ISSUE THREAD

**Issue by yvanlebras** [NCEAS/metacat#1411]
Hi NCEAS,

Looking at our metacat test server pages, I just see that there is a typo in the metacatui/about/sharing-your-datapage, as Michener is spelled Michner here.

Whishing you a good day,

Yvan

**Comment by taojing2002** [comment]
Hi Yvan:
Thank you for report this issue. However, it is more relative to MetacatUi so I created a new ticket on Metacatui and you can follow the progress on this ticket:
https://github.com/NCEAS/metacatui/issues/1191
I also need to point out that our MetacatUI doesn't hardcode person's name. It got it from the package itself or the third party (profile on orcid). So the error may happen on some other place.

**Comment by taojing2002** [comment]
I am going to close the issue.

**Comment by yvanlebras** [comment]
Thank you. Sorry if this was not the good repo and thank you for creating the issue at the good place.
Best,
Yvan
