### ISSUE TITLE
Add Indication of Finishing Database Upgrade in Configuration  

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1416]
ESS-DIV uses Docker to run their Metacats. They reported that sometimes they got strange behaviors after upgrading. They suspect the upgrade was interrupted by a restart that came too soon since the database upgrading is called asynchronously.

We decided to use `metacat?action=getversion` as the indication. 
Things need to do -

- Change the action of `getversion` to read the version from database rather than the metacat.properties file. 
- Make sure the script to upgrade database version running at the last step during the upgrade

**Comment by mbjones** [comment]
While I agree with the need for a strong indicator, I don't think `metacat?action=getversion` is the right approach.  Even if we have finished running the database upgrade scripts, there could be other scripts in the upgrade process that are not finished.  Also, that version comes from the old metacat API, which we are deprecating in favor of the DataONE API.  So, any solution should: 1) take into account all of the upgrade processes that might be running (not just database upgrades), and 2) integrate with the DataONE API.  It seems like exposing the information in the node capabilities document would be the way to go.  How about if we added some new properties to node capabilities, like so:

```xml
    <property key="upgrade_status">in_progress</property>
    <property key="metacat_version">2.10.3</property>
```

The `upgrade_status` flag might be a controlled vocabulary with the following values:

- in_progress
- success
- failure

Might we also need a `needs_restart` status? The upgrade controller would be responsible for setting these values and making sure that failures are handled properly.

Within the node capabilities, this would look like this:

```xml
<ns3:node xmlns:ns2="http://ns.dataone.org/service/types/v1" xmlns:ns3="http://ns.dataone.org/service/types/v2.0" replicate="true" synchronize="true" type="mn" state="up">
    <identifier>urn:node:KNB</identifier>
    <name>KNB Data Repository</name>
    <description>The Knowledge Network for Biocomplexity (KNB) is a national network intended to facilitate ecological and environmental research on biocomplexity.</description>
    <baseURL>https://knb.ecoinformatics.org/knb/d1/mn</baseURL>
    <services>
        <service name="MNCore" version="v1" available="true"/>
        <service name="MNCore" version="v2" available="true"/>
        <service name="MNRead" version="v1" available="true"/>
        <service name="MNRead" version="v2" available="true"/>
        <service name="MNAuthorization" version="v1" available="true"/>
        <service name="MNAuthorization" version="v2" available="true"/>
        <service name="MNStorage" version="v1" available="true"/>
        <service name="MNStorage" version="v2" available="true"/>
        <service name="MNReplication" version="v1" available="true"/>
        <service name="MNReplication" version="v2" available="true"/>
        <service name="MNPackage" version="v1" available="true"/>
        <service name="MNPackage" version="v2" available="true"/>
        <service name="MNView" version="v2" available="true"/>
    </services>
    <synchronization>
        <schedule hour="*" mday="*" min="0/3" mon="*" sec="10" wday="?" year="*"/>
        <lastHarvested>2019-12-20T21:19:16.296+00:00</lastHarvested>
        <lastCompleteHarvest>2019-12-20T21:19:16.296+00:00</lastCompleteHarvest>
    </synchronization>
    <ping success="true" lastSuccess="2019-12-20T21:19:16.297+00:00"/>
    <subject>CN=urn:node:KNB,DC=dataone,DC=org</subject>
    <contactSubject>CN=Christopher Jones A2108,O=Google,C=US,DC=cilogon,DC=org</contactSubject>
    <property key="CN_operational_status">operational</property>
    <property key="CN_date_operational">2012-07-23T00:00:0.000Z</property>
    <property key="CN_node_name">Knowledge Network for Biocomplexity</property>
    <property key="CN_logo_url">https://raw.githubusercontent.com/DataONEorg/member-node-info/master/production/graphics/web/KNB.png</property>
    <property key="CN_info_url">https://knb.ecoinformatics.org/</property>
    <property key="CN_location_lonlat">-119.697933,34.420222</property>
    <property key="upgrade_status">in_progress</property>
    <property key="metacat_version">2.10.3</property>
</ns3:node>
```
