### ISSUE TITLE
MetacatUI free text search doesn't work after Solr upgrades to 8

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1421]
When I searched the text on MetacatUI, it kept spinning. I looked at the tomcat console and found this error:
```
Error from server at http://localhost:8983/solr/metacat-index: undefined field _text_
```

**Comment by taojing2002** [comment]
I looked at the queries which were sent to Metacat and found they don't specify the solr fields for the text. So it depends on the feature of the default field which is `text` in our solr 3.* schema.xml file. However, both `defaultSearchField` and the default query operator are not supported anymore after solr 6. Instead, it suggests to use parameters `df` and `q.op` on the query.
```
<defaultSearchField>text</defaultSearchField>                                                                                                                                                                                                                                                              
 <solrQueryParser defaultOperator="AND"/>
```
The error message indicates Solr will somehow search the field `_text_` if the query doesn't designate the search fields. So I am thinking to make a workaround by using a copy filed:
```
<field name="_text_" type="text_general" multiValued="true" indexed="true" stored="false"/> 
<copyField source="*" dest="_text_"/> 
```
What do you guys think?

@laurenwalker I remember we discussed the issue of  the retirement of the default query operator a while ago. Do you think it will cause any issues on MetacatUI?

**Comment by mbjones** [comment]
@taojing2002 note the summary of related issues I just posted to issue #1420 -- which leads me to believe we would be better off having clients explicitly name the fields to be searched, rather than relying on the default field mechanism. Still, issues to be worked out.

**Comment by taojing2002** [comment]
Okay. Using the explicit field name on the client is our goal. But I will still add the field to support current client otherwise we have to wait  until a new MetacatUI is released.

**Comment by taojing2002** [comment]
The free search works now. So I think MetacatUI fixed the issue.
