### ISSUE TITLE
Some index fields are showing up duplicated

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1439]
See https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=id:%22doi:10.18739/A2D21Z%22

e.g.,

```xml
<arr name="identifier">
  <str>doi:10.18739/A2D21Z</str>
  <str>doi:10.18739/A2D21Z</str>
</arr>
<arr name="sku">
  <str>doi:10.18739/A2D21Z</str>
  <str>doi:10.18739/A2D21Z</str>
</arr>
...
<arr name="updateDate">
  <date>2017-07-17T18:19:44.554Z</date>
  <date>2017-07-17T18:19:44.554Z</date>
</arr>
```

This popped up after @csjx recently upgraded arcticdata.io to Metacat 2.13 which uses our new external Solr setup. I think Solr was upgraded out of band with a JSON dump and JSON load so this may be an artifact of that process and not a bug Metacat's application logic. However, it may also be a config or application logic issue.

Filing this just so we can track it and for visibility. If this is just an artifact of the upgrade process, I think it'd be great to have docs for migrating from Metacat versions with integrated Solr to ones with an external Solr instance.

Todos:

- [ ] Fix up the index on arcticdata.io
- [ ] See if other 2.13 Metacat's we operate have this behavior
- [ ] If appropriate, write up docs for users migrating

**Comment by taojing2002** [comment]
I just reindex the pid and the issue is gone. So it seems it is not a Metacat index issue. I suspect it related to the JSON dump since the objected was created and updated in 2017. So its index created by Chris' json dump. 
We may have two options:
1. Wait users report the pids with the issue and reindex them.
2. Write a script to go through the index to figure out the pids with the duplicated value and reindex them.

**Comment by taojing2002** [comment]
Jeanette will provide a list of pids (she said it will be about 5,000 ids). I will try to run 100 document first to see if it cause any issues.  If there is no problem,  I will run the rest at night.

**Comment by jeanetteclark** [comment]
Sorry Jing, I wasn't very clear. I sampled 5000 pids and found 90% had the issue. I am emailing the file now with the 770,000+ identifiers with issues.

**Comment by taojing2002** [comment]
Hrrm, that means we need almost to reindex all pids. This need a total 
different approach. Chris. Do you have some idea?

**Comment by taojing2002** [comment]
The problem happened when we used the the command to import the dumped old json file to the new server:
```
curl 'http://localhost:8983/solr/metacat-index/update?commit=true' --data-binary @solr-dump-docs-array.json -H 'Content-type:application/json'
```
in the solr-dump-docs-array.json, the docs already have the field `identifier`. The schema.xml also has the copy field:
```
<copyField source="id" dest="identifier"/>
```
So the process will copy the field `id` to the field `identifier` again. Eventually we got the duplicated values.
When I commented out the copyField, the importing only generated one value. 
The following copyFields need to be commented out during the importing:
```
<copyField source="id" dest="identifier"/>
<copyField source="id" dest="sku"/>
<copyField source="pubDate" dest="datePublished" />
<copyField source="dateUploaded" dest="updateDate" />
```
The other copyFields should be kept:
```
   <copyField source="title" dest="titlestr"/>
   <copyField source="origin" dest="originText"/>
    <copyField source="origin" dest="originatorText"/>
    <copyField source="project" dest="projectText"/>
    <copyField source="funding" dest="fundingText"/>
    <copyField source="site" dest="siteText"/>
    <copyField source="parameter" dest="parameterText"/>
    <copyField source="sensor" dest="sensorText"/>
    <copyField source="source" dest="sourceText"/>
    <copyField source="term" dest="termText"/>
    <copyField source="topic" dest="topicText"/>
    <copyField source="investigator" dest="investigatorText"/>
    <copyField source="keywords" dest="keywordsText"/>
```
The attribute `stored` has the vlaue `false` in those `*Text` fields. This means those fields can't retrieved, so they don't exist in the dumped json file. They depend on the copyFiled to generate the only one copy

**Comment by amoeba** [comment]
Thanks for the writeup @taojing2002, that's super helpful and makes sense. Would this be useful for our admin docs?

**Comment by taojing2002** [comment]
I commented out the four copy fields and ran the command again (we can keep the existing solr data files)
```
time curl 'http://localhost:8983/solr/metacat-index/update?commit=true' --data-binary @solr-dump-docs-array.json -H 'Content-type:application/json'
```
It fixed the issue. Then I removed the comment and restarted solr.
