### ISSUE TITLE
Fix leaking threads in ExecutorService instances

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacat#1442]
We use `ExecutorServices` in a few classes to perform asynchronous processing of calls.
The following three instances shutdown the `ExecutorService` thread with `executor.shutdown()`:
- `GenerateSystemMetadata.multiThreadUpgrade()`
- `SyncAccessPolicy.syncAll()`
- `HazelcastService.resynchInThread()`

The following four instances fail to shutdown the `ExecutorService`:
- `MNodeService.updateSystemMetadata()`
- `v2/MNResourceHandler.replicate()`
- `v1/MNResourceHandler.systemMetadataChanged()`
- `v2/MNResourceHandler.systemMetadataChanged()`

This results in a build up of threads since new instances of `MNodeService` and `MNResourceHandler` are created for every Metacat request.

To shutdown `ExecutorServices` cleanly so we can garbage collect them, the [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html) has a good example of using `shutdown()`, `awaitTermination(), ` followed by `shutdownNow()`.  This combination allows tasks to complete in a, say, 60 second window before the immediate shutdown is called.  Migrate our shutdown code to use this pattern.

This bug doesn't explain why large volumes of `MNodeService.get()` requests are causing massive increases in thread count.  However, it's good to fix these nonetheless since they represent a memory leak over time.

**Comment by taojing2002** [comment]
Chris. I looked at those methods and found they are using the code like:
```
executor.submit(runner);
```
Those classes maintain a executor thread pools with a fixed number of threads. So the number of threads will NOT build up when we call the `submit` method. So we don't need to shut down the executor service after calling the `submit` method. Those threads eventully will be destroyed when tomcat shutdowns.

**Comment by vchendrix** [comment]
@csjx @taojing2002  what version of Metacat was this fixed in?

**Comment by taojing2002** [comment]
@vchendrix This is not a bug. The ExecutorService has a fix size of thread and we use the `submit` method. It shouldn't close after submitting tasks.
