### ISSUE TITLE
authoritativeMemberNode not set in MNodeService::update

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacat#1448]
In [MNodeService::update](https://github.com/NCEAS/metacat/blob/master/src/edu/ucsb/nceas/metacat/dataone/MNodeService.java#L363) we overwrite [several properties](https://github.com/NCEAS/metacat/blob/master/src/edu/ucsb/nceas/metacat/dataone/MNodeService.java#L450) in the incoming system metadata. These check out with the behavior defined in the [system metadata specification](https://dataone-architecture-documentation.readthedocs.io/en/latest/design/SystemMetadata.html#mutability-of-system-metadata). _One_ property in particular, `authoritativeMemberNode`, isn't set. This means that the user can control this (which shouldn't be possible), and causes issues when uploading a system metadata document that doesn't have the record.

This blows up when someone updates a package and gives s system metadata document _without_ `authoritativeMemberNode`. The value is used by `doUpdateAuth`, which doesn't exist and a null pointer exception is thrown.

The [R package](https://github.com/DataONEorg/rdataone/blob/1d67e3a8e7f23dca19660d328c2270ce4d3e6536/R/MNode.R#L483) gets around this by placing a check in the create and update object methods so that there's always one present (so the null pointer never happens).

#### Solution

Place `sysmeta.setAuthoritativeMemberNode(originMemberNode);` [here](https://github.com/NCEAS/metacat/blob/master/src/edu/ucsb/nceas/metacat/dataone/MNodeService.java#L451). This ignores what the user supplied and overrides it with `originMemberNode`. This also ensures that there's always one present.

[This](https://github.com/NCEAS/metacat/blob/master/src/edu/ucsb/nceas/metacat/dataone/MNodeService.java#L699) should also probably change to ignore previous, possibly user supplied values.

One issue that _does_ come up is that these should be mutable properties by an administrator. This means that an admin will have to find some other way to set these values than the create and update endpoints. One potential solution is to check if the person issuing the request is an admin. If so, allow them to change it.

Letting the R package default the values probably doesn't hurt anything, but may give users the impression that they can directly control it.

**Comment by jusana** [comment]
Hello all,

Well I have to say this issue has really driven me crazy ;) !!!

Actually I could not update my ORE rdf twice , the first time ok and the second KO (wether with api, or via metacatUI)

with alway this error message
```
<?xml version="1.0" encoding="UTF-8"?><error detailCode="0000" errorCode="500" name="ServiceFailure">
      <description/>
 </error>
```
not leading me to any clues !!!

I finally found i was related to this issue (btw i didn't find it via the issue search engine  with "detail=0000" keyword

Anyway, i am using the python "sdk" v3.4.7 ... and I am getting around the issue by forcing the "authoritativeMemberNode" when i generate the sysmeta of my objects .... but as far as I understand as mentionned in this other closed issue (https://github.com/NCEAS/metacat/pull/1449) and in the sysmeta spec (https://dataone-architecture-documentation.readthedocs.io/en/latest/design/SystemMetadata.html#mutability-of-system-metadata) this value should be set by the CN directly .... is this correct ?

Well, @ThomasThelen sorry to bother, how did you get around this issue on your side (https://github.com/NCEAS/metacat/pull/1449#issuecomment-713055489) ?

Thanks in advance !
julien.

**Comment by jusana** [comment]
Btw,

```
<archived>false</archived>
```
Does not seem to be set either, but is on "create" (post)

**Comment by ThomasThelen** [comment]
@jusana 
I cant vouch for the specification being fully followed in this instance. If I recall correctly, there are cases where some users need to change the authoritativeMemberNode for updated objects so there was hesitation to overwrite the authoritativeMemberNode in the incoming system metadata.

The workaround is to just use the authoritativeMemberNode value from the existing system metadata document of the uploaded file while updating it. This assumes that the updated object will have the same authoritativeMemberNode.

Here's the workflow I used to get around this:

1. Publish a package
2. Download the system metadata of the object being updated
3. Using that system metadata object, update all of the appropriate fields for the new object
4. Upload the new object with the freshly mutated system metadata

Since you're using Python, you can find inspiration for how to do this [here](https://github.com/whole-tale/gwvolman/blob/43fd56a86911fa6405384894bfdabb448f6d8362/gwvolman/lib/dataone/publish.py#L258). Starting from line 258... If the data package has been published before, attempt to get the system metadata for the already published  eml document. Then, update that system metadata with the new eml properties (self.update_sysmeta). Finally, call [_obsolete_object](https://github.com/whole-tale/gwvolman/blob/43fd56a86911fa6405384894bfdabb448f6d8362/gwvolman/lib/dataone/publish.py#L462) to update the EML document.

**Comment by jusana** [comment]
thanks a lot @ThomasThelen , i was wondering how to set the correct value ... I will also assume the same authoritativeMemberNode .... and inspire the rest from the code tou quoted

thanks again very much !!

**Comment by taojing2002** [comment]
I have a short meeting with Bryce and we agree to do this:
1. If the client try to modify the authorizedMemberNode in the update method, Metacat should throw an exception.
2. If the authorizedMember node is null, we may set the current node as the authorizedMemberNode.
