### ISSUE TITLE
Metacat logs using System.out and System.err instead of log4js

### ISSUE THREAD

**Issue by mamelara** [NCEAS/metacat#1453]
Hello, I am from ESS-DIVE and we are looking into ways to logrotate some of the log files left by tomcat to save storage space. However, we found that Metacat log messages are sent to stdout and stderr which get captured by `catalina.out`. This file is not a file that gets logrotated by Tomcat. We also cannot set it up so that our container can setup a logrotation service since that requires root privilege which we do not have due to security issues with our services infrastructure (Spin). 

We would like to get a better idea of what gets logged to stdout and stderr, and if any of these are critical for debugging. We also would like to propose that if these messages are critical that they get properly logged by log4js, rather than stdout and stderr. This would solve our problem since we can rely on the log4js logrotation.  

@vchendrix @gothub are both helping out with this. If you have anything to add/clarify please feel free!

**Comment by mbjones** [comment]
@mamelara We don't log to System directly, but rather use commons logging facilities, which then passes messages to log4j for serialization to various outputs. You can reconfigure metacat through the log4j.properties file in the configuration to completely change which log levels are logged, where those go, and how they are formatted. The default configuration sends that to catalina.out, but you can easily change that configuration. We change it in our deployments.

While it's possible that a few System.out and System.err calls crept into the code, that is not how we designed the logging system, and they should not be there. So, if you find specific instances of that, please let us know, and we'll get those fixed.

**Comment by vchendrix** [comment]
@mbjones Thanks for the feedback.  I think this issue ticket was probably submitted a little too early.  We are in the process of figuring out which error/info message we would lose.  Let's table this discussion until we have some more information for you.

**Comment by mbjones** [comment]
OK, sounds good @vchendrix . @taojing2002 is also working on upgrading our logging system to a newer version, so be sure to refer any issues you encounter to him. In the meantime, I'll close this ticket, but if you find problems with System.out or System.err logging in Metacat, feel free to reopen in.
