### ISSUE TITLE
getObject, getPackage implementations leak file descriptors

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1458]
While doing some performance testing of Metacat with larger (>1000 file) packages on test.arcticdata.io, we ran into a situation where Tomcat was throwing an infinite stream of "Too many open files" exceptions and services were partially offline.

I logged into the server and saw nearly 4000 open file descriptors, mostly pointing at paths like `/var/metacat/data/autogen.2016092314041640733.1`. To reproduce, I restarted Tomcat, hit Download All on https://test.arcticdata.io/view/urn%3Auuid%3Ad108ec6a-025c-46aa-b32e-887aa29d0115 once and waited for it to finish. Once it finished, I hit Download All again and reproduced the "Too many open files" errors. It's very reasonable for Download All (getPackage) to open thousands of file descriptors while doing its work but it's not reasonable that it should open all of them at once and leave them open indefinitely.

To get a sense for wether this was restricted to `getPackage`, I monitored the total number of open file descriptors while I issued a single `getObject` request and saw the number go up by one _and stay up_. So I think we might not be handling the lifecycle around our file handles quite right.

I then took a quick look at the implementations of `getPackage` and `getObject` and noticed that both methods open streams but never explicitly call `.close()` on any of them. Additionally, it doesn't look like these methods are try-caught-finally'd in a way that'd ensure cleanup.

Of course, if this is all true, then why don't we see it more often? I think that's because we've been successfully relying on the GC to run the finalizers on the streams which works fine when Metacat isn't being asked to do too much at once. Running `getPackage` on a larger package is an example of doing too much too fast for this approach.

I think we should re-visit the logic in these methods to manually close streams, preferably inside finally blocks. Could be good to try to lump in with https://github.com/NCEAS/metacat/issues/1167 and https://github.com/NCEAS/metacat/issues/1262.

**Comment by taojing2002** [comment]
In the get method, the input stream will be returned. So Metacat can't close it otherwise the client can't get the expected result. So clients should close the streams. Maybe we need a thread to periodically check if there are too many open descriptors in the the system.

**Comment by amoeba** [comment]
@taojing2002 and I had a call this morning to go over the finer details and one thing that popped out of that conversation was that @ThomasThelen possibly has changes in the implementation of `getPackage` from his work on https://github.com/NCEAS/metacatui/issues/1362 so we should coordinate those two efforts. I forgot to link in that issue when I wrote the initial ticket.

**Comment by taojing2002** [comment]
Close the input stream object in the getObject method. Also, the view method has the same issue and it was fixed.
