### ISSUE TITLE
Editor says "Nothing was found" despite having all permissions

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1460]
**Describe the bug**

The editor will fail to load for a metadata record where the subject of the user attempting to edit does not explicitly have `read` permission in the `accessPolicy`. They do have `write` and `changePermission` granted and are _not_ the `rightsHolder`.

**To Reproduce**
1. Create a metadata object where your subject is not the `rightsHolder` and is only listed in the `accessPolicy` with `write` and `changePermission` permission.
2. Try to edit the dataset 
3. See

<img width="501" alt="Screen Shot 2020-07-21 at 12 55 41 PM" src="https://user-images.githubusercontent.com/563/88106181-7f7e6200-cb51-11ea-9fc4-887b0025b051.png">

**Expected behavior**
It's expected that the editor will load normally.

**Desktop (please complete the following information):**
 - OS: macOS 11
 - Chrome
 - 84.0.4147.89 

**Additional context**

Here's the sysmeta on the metadata record:

```xml
<?xml version="1.0"?>
<d1_v2.0:systemMetadata xmlns:d1_v2.0="http://ns.dataone.org/service/types/v2.0" xmlns:d1="http://ns.dataone.org/service/types/v1">
  <serialVersion>0</serialVersion>
  <identifier>urn:uuid:3f506085-6717-4528-9943-2e5401755f58</identifier>
  <formatId>eml://ecoinformatics.org/eml-2.1.1</formatId>
  <size>3678</size>
  <checksum algorithm="SHA1">e6fdb457624eaec601a5b35f107d6183e4260f0b</checksum>
  <submitter>http://orcid.org/0000-0002-0381-3766</submitter>
  <rightsHolder>foo</rightsHolder>
  <accessPolicy>
    <allow>
      <subject>http://orcid.org/0000-0002-0381-3766</subject>
      <permission>write</permission>
      <permission>changePermission</permission>
    </allow>
  </accessPolicy>
  <replicationPolicy replicationAllowed="false" numberReplicas="0">
    <blockedMemberNode>urn:node:KNB</blockedMemberNode>
    <blockedMemberNode>urn:node:mnUCSB1</blockedMemberNode>
  </replicationPolicy>
  <archived>false</archived>
  <dateUploaded>2020-07-21T20:48:57.342+00:00</dateUploaded>
  <dateSysMetadataModified>2020-07-21T20:50:27.754+00:00</dateSysMetadataModified>
  <originMemberNode>urn:node:METACAT_TEST</originMemberNode>
  <authoritativeMemberNode>urn:node:METACAT_TEST</authoritativeMemberNode>
  <fileName>dummy_science_metadata.xml</fileName>
</d1_v2.0:systemMetadata>
```

**Comment by taojing2002** [comment]
Fixed the bug on the commit 166a0b7231a38f63f318ff344fb646d5c748be10.
