### ISSUE TITLE
Java Version for Building & Running

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacat#1463]
It looks like the free version of Java 8 was deprecated some time ago and the [build file](https://github.com/NCEAS/metacat/blob/master/build.xml#L41) is listing Java 7 as maximum supported Java version. There's also an older [issue](https://github.com/NCEAS/metacat/issues/1186) about Metacat 2.9 supporting Java 8; Java 6 was axed in Metacat 2.2.

Is it safe to say that Java 7 is the current supported version? I think I've built under Java 8 a number of times, so I'm wondering if I should be using Java 11 since it's still supported by Oracle, Java 8 from the linked issue that's implying it's supported since 2.9 (but still open), or Java 7 from the build.xml file.

**Comment by taojing2002** [comment]
Changed it to the version 1.8. We should use more modern java versions such as java 11. However, there is an issue on Hazelcast with the newer java version.
https://github.com/NCEAS/metacat/issues/1313
