### ISSUE TITLE
Update metacat-index's System Metadata processing to match https://redmine.dataone.org/issues/8869

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1464]
Over in https://redmine.dataone.org/issues/8869 we outline a bug caused by string-sensitive comparisons of Subjects in the Solr index when variants of Subject strings that are otherwise equivalent are found in System Metadata. We decided over in that ticket to apply normalization on any Subject strings in Solr index fields which means we need to update `d1_cn_index_processor`.

It looks to me like `metacat-index` duplicates the System Metadata processing logic within its own code base. If that's the case, I wanted a ticket filed here to track that work. @taojing2002 I assigned you since you were assigned over on Redmine. And please close if my assessment is wrong.

**Comment by taojing2002** [comment]
This bug was fixed.
