### ISSUE TITLE
Use type=button in ISO19115 copy button

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1465]
Over in https://github.com/NCEAS/metacatui/issues/1616 I found out that we need a `type=button` attribute on the Copy buttons in the Alternate Data Access section of the ISO19115 view service xslts. Because the view service returns its content wrapped in a `form` tag (not sure why yet), a `button` without a `type`, defaults to a button that submits the form. This breaks copying.

**Comment by amoeba** [comment]
Hey @taojing2002 , I tossed this on to the 2.14 branch but I didn't see any 2.14 series milestones. Do we just need to make one and toss this in? If you wanna make one, toss this issue in, and close this issue go ahead. Otherwise I'm happy to do it.

**Comment by taojing2002** [comment]
I created the 2.14.0 milestone and assigned it to this ticket. I am going close this issue.

**Comment by amoeba** [comment]
Thanks @taojing2002.
