### ISSUE TITLE
Expand elements covered by EML's attribute* index fields beyond just dataTable

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1468]
This is just a cross-post of https://github.com/DataONEorg/d1_cn_index_processor/issues/2:

We noticed today that our EML index processing rules in [`application-context-eml-base.xml`](https://github.com/DataONEorg/d1_cn_index_processor/blob/main/src/main/resources/application-context-eml-base.xml#L457) only capture `attribute` elements under a `dataTable` element (e.g., `//dataTable/attributeList/attribute`). However, EML supports attributes under all entity types, not just `dataTable`. This is probably confusing to users and something I think we should address.

I suggest we change the relevant XPath selectors in `application-context-eml-base.xml` to cover all entity types. I can't think of any downsides to the change, other than having to reindex content. I think all users will want to be able to search for attributes on other entity types.

**Comment by taojing2002** [comment]
Duplicate 1361
