### ISSUE TITLE
Update metacat indexing to support portals schema 1.1.0

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacat#1471]
Update metacat-index to support changes to the portal document schema for v1.1.0. The DataONE formatId will be https://purl.dataone.org/portals-1.1.0.

The changes to the schema are currently being made [here](https://github.com/DataONEorg/collections-portals-schemas/pull/87).

**Comment by laurenwalker** [comment]
Thanks for creating this issue, Peter!

**Comment by gothub** [comment]
Changes to portal document indexing for the `collectionQuery` field will include supporting these portal document changes outlined in the [changelog](https://github.com/DataONEorg/collections-portals-schemas/blob/dev-1.1/CHANGELOG.md)
- [ ] `<filterGroup>` both at the root level and nested
- [ ] `<exclude>` to negate a `<filterGroup>` result from the resultset
- [ ]  `<operator>` which defines how `<filter>` clauses are combined
- [ ] `<fieldsOperator>` which defines how `<values>` are joined

**Comment by gothub** [comment]
Ensure that the Solr 'negation' problem is handled, see https://github.com/NCEAS/metacatui/issues/1600

**Comment by robyngit** [comment]
See also: https://github.com/NCEAS/metacat/issues/1477

**Comment by gothub** [comment]
This fix has been merged to the `devel` branch and will be included in the 2.14.1 release.
