### ISSUE TITLE
Add new xml schema to Metacat for collections-portals-1.1.0

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1473]
Here are my notes from when I did this for collections-portals-1.0.0:

To get a metadata doc to validate against a .xsd schema, create a directory for the schema in metacat/lib/schema and put the schema .xsd file in that directory.

Add the namespace bean to the namespace bean list in metacat-index/src/main/resources/index-processor-context.xml

Add the schema namespace to the Postgres db via the upgrade .sql files that are execeuted during the Metacat upgrade/configuration.

loaddtdschema-postgres.sql:
```
  INSERT INTO xml_catalog (entry_type, public_id, system_id)
  VALUES ('Schema', '@portals1_0_0namespace@', '/schema/portals-1.0.0/portals.xsd');
```
upgrade-db-to-2.11.0.sql:
```
INSERT INTO xml_catalog (entry_type, public_id, system_id) SELECT 'Schema', 'https://purl.dataone.org/portals-1.0.0', '/schema/portals-1.0.0/portals.xsd'  WHERE NOT EXISTS (SELECT * FROM xml_catalog WHERE public_id='https://purl.dataone.org/portals-1.0.0');
```

Update metacat.properties with the new Metacat version and list the upgrade-db-to-X.sql file in the script list.

Configure the database part of Metacat in the admin panel and that will run the upgrade script.

**Comment by gothub** [comment]
@laurenwalker When should this change be made? Is this blocked until v1.1.0 portal and collection schema files are available at purl.dataone.org? If not, I  can make these changes and include them in a PR with #1471.

**Comment by gothub** [comment]
This fix has been merged to the `devel` branch and will be include in the 2.14.1 release.
