### ISSUE TITLE
Fix how exclude filters are translated in the collectionQuery

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacat#1477]
**Problem:** When a portal or collection definition filter has `exclude` set to `true`, the Solr query string for that filter includes a `-` sign before the associated query. If a portal comprises just one query rule, and that rule uses one of these "negated" operators, then the data search gives 0 results.

**Solution:** Append ` AND *:*` to any query string that is built from a Filter model that's negative (`exclude:true`).

See [this issue in MetacatUI](https://github.com/NCEAS/metacatui/issues/1600) for more details

**Comment by gothub** [comment]
This fix has been merged to `devel` and will be included in the 2.14.1 release.
