### ISSUE TITLE
Index dataset license

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacat#1479]
It would be nice if the rights of a dataset were indexed in metacat/solr so that license information can easily be examined.

For EML, this would look in `eml/dataset/intellectualRights`

**Comment by amoeba** [comment]
Thanks @jeanetteclark. Related: https://github.com/NCEAS/metacat/issues/1348 + https://github.com/DataONEorg/d1_cn_index_processor/issues/6. Could probably get this done at the same time as https://github.com/DataONEorg/d1_cn_index_processor/issues/6. cc @gothub

**Comment by mbjones** [comment]
In addition to intellectualRights, the main place to watch is the new EML 2.2.0 structured license fields (name, URL, and identitifier), so that we can more precisely indicate licenses.  See https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#dataset-license

**Comment by jeanetteclark** [comment]
bump @mbjones

**Comment by mbjones** [comment]
+1 @taojing2002

**Comment by taojing2002** [comment]
This is the  duplicated one to the dataone-indexer:
https://github.com/DataONEorg/dataone-indexer/issues/2
