### ISSUE TITLE
support java 17 source compatibility and current JVM releases

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1481]
We currently operate on Java 8 (issue #1463) and have been prevented in upgrading because of hazelcast needing Java 10 and beyond (issue #1313).  Metacat should be operable on supported JVM versions, particularly OpenJDK 11 which is the most recent LTS version. It should be supported through 2026 by AdoptOpenJDK. Java 15 is the current release, which will only be supported until Java 16 comes out in March 2021.  See https://en.wikipedia.org/wiki/Java_version_history for a summary. 

For us, I think this means we should 1) compile using source compatibility against the most recent LTS version (11 at this time), and 2) ensure our build and tests pass and that we can run under the most recent version (currently 15) at the time of each metacat release.

On the longer time front, I worry about the availability of open java support, and we should be moving towards a more modular infrastructure, and the extent possible refactor subystems like indexing that can stand alone and be gradually migrated to other languages if it makes sense.

To close this issue:

- [ ] Change the metacat build to use source compatibility with the most recent LTS (Java 11), and build releases with that version
- [ ] Test that the release works with the most recent java version (currently Java 15)

**Comment by mbjones** [comment]
With the removal of Hazelcast, we should now be able to move up to modern Java LTS releases. I suggest we should require Java 17 in the 3.0.0 release, so I am retargeting to that milestone and retargeting the issue.

**Comment by taojing2002** [comment]
Send an email to metacat-dev mailing list to ask there opinions about our plan:

- Metacat 3.0.0 supports both java 1.8 and 17.
- Later versions only support java 17 and later.

**Comment by mbjones** [comment]
@taojing2002 after reflecting further, let's consider these options in the email, and ask what people prefer:

1. Require JRE 17 or later for Metacat 3.0.0 (will require sites to upgrade java to deploy)
- because Metacat 3 is a major release, breaking changes are expected
3. Support both JRE 8 and JRE 17 in Metacat 3.0.0, but deprecate JRE 8 to be removed in a later release
- allows peolle longer to adapt to the JRE upgrade, but means a breaking change will occur in a non-major release later
