### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacat#1483]
From an inclusivity perspective, I suggest we rename the `master` branch to `main` and generally use more welcoming terms as we describe our software architectures. The use of the the terms `master` and `slave` in computing are not welcoming.  For context, see the [Inclusive Naming](https://inclusivenaming.org) project and [this repo](https://github.com/github/renaming).

**Comment by mbjones** [comment]
@taojing2002 Branch has been renamed. Need to check jenkins and travis, etc. Working copies can be updated with:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by mbjones** [comment]
@taojing2002 I updated the CONTRIBUTING file and sphinx install docs to reflect the change to `main`. I'm going to target this for 2.16.0, assuming you'll integrate the `develop` changes there. It's essentially done in 2.15.0, but I think the docs changes missed your PR for 2.15.0.
