### ISSUE TITLE
Incorrect geohash 

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1488]
A dataset with an incorrect geohash was found today by an ADC user. This dataset: https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=id:%22doi:10.18739/A2S46H60V%22&fl=*BoundCoord,geohash_9 seems to have the correct bounding box, but the geohash that was generated by the indexer is located in Finland (`62.49999762, 25.00001192`). I believe the correct lat, long bounding box centroid should be about `62.49999762, -155`. It seems like maybe the geohash generator code is struggling with bounding boxes that overlap the `0` longitude meridian.

```xml
<float name="southBoundCoord">50.0</float>
<float name="northBoundCoord">75.0</float>
<float name="westBoundCoord">175.0</float>
<float name="eastBoundCoord">-125.0</float>
<arr name="geohash_9">
<str>ue1g8cu2y</str>
</arr>
```

**Comment by gothub** [comment]
The metacat indexer component (in ./cn/indexer/convert/GeohashConverter.java) is using the `geohash` package (groupId: ch.hsr, artifactId: geohash, version: 1.0.10). to calculate the center point of a bounding box, then calculates the geohash that includes that point. The `geohash.BoundingBox.getCenterPoint()` method doesn't take into account bounding boxes that cross the International Date Line, so the simple center point calculation is wrong:
```
    double centerLongitude = (westLongitude + eastLongitude) / 2;
```
For the above case:
```
      centerLongitude = (175 + -125) / 2.0 = 25 // but this should be -155.0
```

The geohash algorithm is unaffected by the IDL, so I propose:
- we continue to use the `geohash` package to calculate the geohash from the bounding box center point
- we perform our own bounding box center point calculation in GeohashConverter.java, taking into account boxes that cross the IDL
- perform our due-diligence and submit a PR with this fix to the geohash package, for use in a future release
