### ISSUE TITLE
Enforce NodeReplicationPolicy in the MN.replication method

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1493]
I just took a quick look and found we haven't enforce the node replication policy:

https://dataone-architecture-documentation.readthedocs.io/en/latest/apis/Types.html#Types.NodeReplicationPolicy

Maybe first round we can enforce allowedNode and allowedObjectFormat?

**Comment by taojing2002** [comment]
Matt suggests we should enforce all elements.

**Comment by mbjones** [comment]
Thanks @taojing2002 yeah, I think they all are needed. Given that we'd be checking for each replica request, it seems reasonable to AND them all together and evaluate them all at once.
