### ISSUE TITLE
Update the stock metacat.properties sitemap config to include 1.1.0 portal docs

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1519]
I hadn't realize the 1.1.0 schema is out but it's at least in the DataONE [formats list](https://cn.dataone.org/cn/v2/formats).

So we should update:

https://github.com/NCEAS/metacat/blob/e9bb966bfefde3e26236a6da789ef1eb367a5761/lib/metacat.properties#L593

to include it so the sitemaps contain 1.1.0 portals.

**Comment by mbjones** [comment]
@artntek with your properties familiarity, can you look at this and add it please to 3.0.0? It would be good for all of our portals to be indexed by google, and I think the change is a single line property change. If it looks like more work than that, feel free to push it to 3.1.0.

**Comment by artntek** [comment]
On closer inspection, it appears that @taojing2002 has already done this: 3de37dc4a023ac6a83060dbf739fbb64b7beebd3
