### ISSUE TITLE
EML to HTML/PDF is broken on 0.97

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacat#1522]
I noticed that the PDF file that gets included in BagIt 0.97 exports is broken. Instead of HTML, there's a rendering of a tree of EML, shown below and attached.

[urn_uuid_eddcf1fd-0ffe-4363-b60b-087cf4c5efe4-METADATA.pdf](https://github.com/NCEAS/metacat/files/6977466/urn_uuid_eddcf1fd-0ffe-4363-b60b-087cf4c5efe4-METADATA.pdf)

To Reproduce:
1. Download a data package
2. Navigate into the `data/` folder
3. Open the PDF document
4. Note that it isn't nicely formatted HTML

<img width="1016" alt="Screen Shot 2021-08-12 at 10 38 33 AM" src="https://user-images.githubusercontent.com/9289652/129243276-44939a7e-55fa-48be-884a-e903b9edd62c.png">

**Comment by mbjones** [comment]
I noticed this a while back too. It is likely becuase of XSLT stylesheet changes. In previous versions of the stylesheets, they were parameterized to produce different outputs depending on how they were invoked. There were 3 typical locations that they were used, each of which had different outputs: on Metacat landing pages, in Morpho window displays, and as a PDF for inclusion in package downloads. 

The canonical copy of the XSLT files was in the EML repository, as they were used across multiple software projects. At some point, someone added them to the metacatui repo, and I think maintenance of the parameterized versions fell by the wayside. So, we may need to determine 1) which version of the stylesheets is being used to create the PDF, 2) if that version still supports multiple modes for output, and 3) if it is being called with the correct input variables to configure it to be 'pdf' mode. I forget the details of how all of that worked, but I could reconstruct if needed -- its controlled through a set of global variables at the top level of the XSLTs, which are set by the methods requesting a transform.

**Comment by taojing2002** [comment]
It seems only eml 2.2.0 objects don't work.

**Comment by taojing2002** [comment]
There is no mappings for the eml 2.20 in the style/skins/default/default.xml file, which is used to determine style sheet files in generating the pdf file. After the mapping was added, it works.
