### ISSUE TITLE
Have MNCore.getCapabilities() report on auth.allowSubmitters parameter setting

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacat#1528]
The [Metacat property `auth.allowedSubmitters` ](https://knb.ecoinformatics.org/knb/docs/metacat-properties.html)setting restricts which DataONE subjects can create or update objects. Client programs currently don't have a way to query Metacat to check if the list of allowed submitters is defined, and what DataONE subjects are in the list.

Update `MNCore.getCapabilities()` to report on the setting of this properties, as it is [service method restriction](https://releases.dataone.org/online/api-documentation-v2.0.1/apis/Types.html#Types.ServiceMethodRestriction).

If `auth.allowSubmitters` has the following value:
```
auth.allowedSubmitters:  http\://orcid.org/0000-0002-2192-403X: CN=knb-data-admins,DC=dataone,DC=org
```

then the `getCapabilties()` report would contain:

```
...
  <services>
  ...
    <service name="MNStorage" version="v1" available="true">
        <restriction methodName="create">>
            <subject>http://orcid.org/0000-0002-2192-403X</subject>
            <subject>CN=knb-data-admins,DC=dataone,DC=org</subject>
        </restriction>
        <restriction methodName="update">
            <subject>http://orcid.org/0000-0002-2192-403X</subject>
            <subject>CN=knb-data-admins,DC=dataone,DC=org</subject>
        </restriction>
    </service>
    <service name="MNStorage" version="v2" available="true">
        <restriction methodName="create">>
            <subject>http://orcid.org/0000-0002-2192-403X</subject>
            <subject>CN=knb-data-admins,DC=dataone,DC=org</subject>
        </restriction>
        <restriction methodName="update">
            <subject>http://orcid.org/0000-0002-2192-403X</subject>
            <subject>CN=knb-data-admins,DC=dataone,DC=org</subject>
        </restriction>
    </service>
...
```

The DataONE [ServiceMethodRestriction](https://dataone-architecture-documentation.readthedocs.io/en/latest/apis/Types.html#Types.ServiceMethodRestriction) type can't be used to represent the `auth.deniedSubmitters`, so this parameter setting will not be included in the report (only allowed subjects can be listed).

Related issue: https://github.com/NCEAS/metacatui/issues/1817 

@taojing2002 how does the report format look? Should only `create()` be listed? What about `generateIdentifier()`?

**Comment by taojing2002** [comment]
I changed the some attribute name from `method` to `methodName`.

**Comment by taojing2002** [comment]
The allowedSubmitters property doesn't control the updateSystemMetadata method.

**Comment by taojing2002** [comment]
The code and test code was committed to the develop branch.
