### ISSUE TITLE
Update  cached solr schema file when the schema file was changed in the solr server

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1529]
Lauren reported an issue:
https://github.com/NCEAS/metacat/issues/1525

It turns out that problem is the cached schema file wasn't updated when the schema file was changed in the solr server. We either need to automatically to update the cached schema file or remove the cache version at all.

**Comment by mbjones** [comment]
I htink this issue is obsolete with the new dataone-indexer refactor, so assigning to @taojing2002 to assess that and close the issue if true.

**Comment by taojing2002** [comment]
Yes, we don't cache the schema in Metacat anymore. So the issue is obsoleted.
