### ISSUE TITLE
Add the OSTI DOI plug-in

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1553]
The OSTI DOI plug-in should at least support these two DataONE API methods:
```

- public Identifier generateIdentifier(Session session, String scheme, String fragment)
- public Identifier publish(Session session, Identifier identifier)

```  
When a user call the `generateIdentifier` method, he/she will pass the parameter `scheme` with value of `DOI` and the `fragment` parameter with the value of `null`.  The method will return a DOI which has been registered on the OSTI Elink service with the status of `Saved`.

Here is my vision in what scenarios we can call the `publish` method and what the `publish` method will do:

- The `identifier` in the `publish` method is a `DOI` and the `DOI` has been registered on the OSTI Elink service.
- The object with the DOI identifier exists on the Metacat instance and is public readable.
- The `publish` method will generate a metadata document for this DOI, submit it to the OSTI Elink service and make the status of the DOI to be `PENDING`.

I also have a question regarding the `publish` method - who is allowed to call the method?

Val and Fianna, what do you think about the plan?

**Comment by vchendrix** [comment]
@taojing2002 It makes for sense for the OSTI publication to have the endpoint do the following:

- `generate` (mint a doi via OSTI )- This should take the PID of the metadata file to "reserve" a DOI with OSTI.  This is done by adding `<set_reserved/>` in the OSTI xml submitted.  No dummy metadata should be submitted to OSTI.  At this point, we can deal with any validation errors that OSTI may return.  Set the new DOI as the seriesId of the provided metadata file. If it is not desireable to refactor `/generate` in this way then maybe a new endpoint for reserving a DOI with a DOI service can be added.

- `publish` (notify OSTI that the data package is live and make it public) - Update site_url and provide the osti_id to make sure that the record is updated and not duplicated.

### Snippet of `eml2osti.xsl`
```xml

<?xml version="1.0"
        encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output encoding="UTF-8" indent="yes" method="xml"/>
    <xsl:strip-space elements="*"/>
    <xsl:param name="data_type" select="'SM'"/>
    <xsl:param name="country" select="'US'"/>
    <xsl:param name="lang" select="'English'"/>
    <xsl:param name="site_code" select="'ESS-DIVE'"/>
    <xsl:param name="site_url"/>   
    <xsl:param name="subject" select="'54 ENVIRONMENTAL SCIENCES'"/>
    <xsl:param name="osti_id"/>
    <xsl:template match="dataset">
        <records>
            <record>
                <xsl:if test="$site_url">
                    <site_url><xsl:value-of select="$site_url"/></site_url>
                </xsl:if>
                <xsl:choose>
                    <!-- Edit existing -->
                    <xsl:when test="$osti_id">
                        <osti_id><xsl:value-of select="$osti_id"/></osti_id>
                    </xsl:when>
                    <!-- only create new if there is not osti_id and site url -->
                    <xsl:when test="not($osti_id) and not($site_url)">
                        <set_reserved/>
                    </xsl:when>
                </xsl:choose>
...
```

**Comment by taojing2002** [comment]
The `publish` method is doing what you described - submitted the OSTI metadata with `site_url` to the Elink service.
The `generate` method sends the OSTI metadata with `<set_reserved/>` as you described. But it sets some fields to `unknown`
```
<?xml version="1.0" encoding="UTF-8"?>
<records>
  <record>
    <set_reserved/>
    <title>unknown</title>
    <contract_nos>unknown</contract_nos>
    <sponsor_org>unknown</sponsor_org>
     <dataset_type>unknown</dataset_type>
    <publication_date>2000</publication_date>
    <site_input_code>ESS-DIVE</site_input_code>
    <creatorsblock>
      <creators_detail>
        <last_name>unknown</last_name>
      </creators_detail>
      </creatorsblock>
  </record>
</records>
```

**Comment by vchendrix** [comment]
@taojing2002 ok that is good to know.  I think I am uncomfortable sending in dummy data to OSTI.  There is no way to know between generate and publish what dataset this is supposed to be linked to from within OSTI. Maybe this is OK but it is different than how we have be performing this process up to now.  When we reserve a DOI it gives us a chance to deal with any validation errors.

**Comment by taojing2002** [comment]
The EZID adaptor Currently has two methods:
```
public Identifier generateDOI()
public boolean registerDOI(SystemMetadata sysMeta)
```
The `generateDOI` method will submit the dummy metadata to the EZID service and get back a DOI.
The `registerDOI` method will submit the real metadata to the EZID service for the given DOI specified in the system metadata.

Here is the interaction between Data APIs with the two methods:
```
MNode.generate(String scheme) calls generateDOI()
MNode.create() calls registerDOI(sysMeta)
MNode.update() calls registerDOI(sysMeta)
MNode.updateSystemmetadata() calls registerDOI(sysMeta)
```
We also have an unofficial  method:
```
MNode.publish(Identifier originalIdentifier) calls both generateDOI() and registerDOI(sysMeta) (triggered implicitly by the MNode.update method
```

**Comment by vchendrix** [comment]
@taojing2002 We have discussed this in our leadership meeting.  It was decided that we prefer the current functionality of the `/generate` and `/publish` apis.  Dummy data is OK.

**Comment by taojing2002** [comment]
On the meeting, we decided that Metacat can be configured as publishing DOI automatically or not.
So the DOI adaptor class should have those methods:
```
generateDOI()
updateDOIMetadata(sysMeta) - only update DOI metadata
publishDOI(sysMeta) - update DOI metadata and publish it (make it public)
```
Here is the logic of the interaction between DataONE  APIs and the Adaptor methods:
```
        If (config.autoPublishDOI) {
              MNode.create() calls publishDOI(sysMeta) 
              MNode.update() calls publishDOI(sysMeta) 
              MNode.updateSystemmetadata() calls publishDOI(sysMeta)
        } else {
              MNode.create() calls updateDOIMetadata(sysMeta) 
              MNode.update() calls updateDOIMetadata(sysMeta) 
              MNode.updateSystemmetadata() calls updateDOIMetadata(sysMeta)
        }
```
We also create a new MN API for curators only to explicitly to make a DOI public:
```
MNode.publishDOI(Identifier doi) 
```
The rest call looks like:
```
 PUT /publishDOI/doi
```

**Comment by mbjones** [comment]
Jing -- feedback on your takeaway from our discussion... publishDOI should do only one thing, not two. Here's my redefinition of the methods with the subtle differences:

```
generateDOI() - generates a **reserved** identifier from the service, with no or placeholder metadata
updateDOIMetadata(sysMeta) - only update DOI metadata
publishDOI(sysMeta) - only publish the DOI (make it public) with the DOI provider
```

Here is the logic of the interaction between DataONE  APIs and the Adaptor methods:
```
Pseudocode calls during `MNode.create()`, `MNode.update()`, and `MNode.updateSystemmetadata()`:

updateDOIMetadata(sysMeta) 
If (config.autoPublishDOI) { 
    publishDOI(sysMeta) 
}
```

Also, consider whether this internal `publishDOI` should be renamed `publishIdentifier` given the "future proofing" comment from below.

We also create a new MN API for **authorized users only** to explicitly to make a DOI public (and future proof it to potentially be extended to work with other sorts of identifiers too, such as arks):
```
MNode.publishIdentifier(Identifier id) 
```
The rest call looks like:
```
 PUT /publishIdentifier/{identifier}
```

**Comment by taojing2002** [comment]
Matt's suggested API are:
```
generateDOI() - generates a **reserved** identifier from the service, with no or placeholder metadata
updateDOIMetadata(sysMeta) - only update DOI metadata
publishDOI(sysMeta) - only publish the DOI (make it public) with the DOI provider
```
The logic of the interaction between DataONE APIs and the Adaptor methods:
```
Pseudocode calls during `MNode.create()`, `MNode.update()`, and `MNode.updateSystemmetadata()`:

updateDOIMetadata(sysMeta) 
If (config.autoPublishDOI) { 
    publishDOI(sysMeta) 
}
```
After working on this for a while, I am thinking we may do this way:
```
generateDOI() - generates a **reserved** identifier from the service, with no or placeholder metadata
registerDOIMetadata(sysMeta, isAutoPublishDOI) - update with/without publishing DOI metadata
publishDOI(identifier) - only publish the DOI (make it public) with the DOI provider
```
The logic of the interaction between DataONE APIs and the Adaptor methods:
```
Pseudocode calls during `MNode.create()`, `MNode.update()`, and `MNode.updateSystemmetadata()`:
registerDOIMetadata(sysMeta, config.autoPublishDOI)
```
Using `publishDOI(identifier)` rather than `publishDOI(sysmeta)` is better to align with the method `MNodeService.publishIdentifier(identifier)`.
In the original design, there are two calls to connect the DOI service - one for `registerDOIMetadata` and the other is for `publishDOI`. If we pass the boolean variable to the `registerDOIMetadata` method, we can decrease the calls to one. And it can make the implementation easier. For example, in the original design, we need a method `publishDO(sysmeta)`. And we have to put logic which determines pid or/and sid are DOIs into both ` registerDOIMetadata(sysMeta)` and `publishDOI(sysmeta)`. 

What do you think?

**Comment by taojing2002** [comment]
I am thinking a new way. We can put the logic of handling to publish DOI automatically or not  in each adaptor class rather than MNodeService class.  So the adaptor class has those methods:
```
generateDOI() - generates a **reserved** identifier from the service, with no or placeholder metadata
registerDOIMetadata(sysMeta) - update with/without publishing DOI metadata
publishDOI(identifier) - only publish the DOI (make it public) with the DOI provider
```
But in the implementation of the `regsiterDOIMetadata(sysMeta)`, we have the logic like:
```
If (config.autoPublishDOI) { 
    //add code to make the DOI public
}
```
So the logic is encapsulated in the adaptor class and the number of network traffic still can be kept to be one.
@mbjones @vchendrix 
What do you think?
