### ISSUE TITLE
Unhelpful error message when trying to create as a denied submitter

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1573]
I am attempting to submit an object to a Metacat that is configured with a "allowed submitter" list. My identity is not in the allowed submitter list, so I expect an error message when I try to submit an object. 

But the error message from Metacat is not very helpful. It is the same message I get when I submit without an auth token:

```
<?xml version="1.0" encoding="UTF-8"?><error detailCode="1110" errorCode="401" name="InvalidToken">
    <description>Session is required to WRITE to the Node.</description>
</error>
```

I think it will be helpful, particularly to repository managers, to get a message that the person is not in the allowed submitter list so that the problem can be solved for that user.

**Comment by taojing2002** [comment]
@artntek Thank you, Matthew.  I think Lauren used an invalid token to get a different error message. However, the message still is not very clear - the user is not allowed to insert/update for this specific object or anything, which is our case. 
```
<error>User 'http://orcid.org/<my-orcid>' is not allowed to insert 
and update</error>
```
If we can explicitly say the user is not in the allowed-user-list on this node, it can be much more helpful.

**Comment by taojing2002** [comment]
@artntek Sorry, I skipped one line on your comment - you already have the plan to update the error text :)
