### ISSUE TITLE
Reserved Solr characters are ignored in queries

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacat#1575]
While testing changes to fix [this metacatui bug](https://github.com/NCEAS/metacatui/pull/1956) about Solr queries, I found an issue with how Metacat is handling queries with special characters.

The [reserved characters for Solr queries](https://solr.apache.org/guide/7_3/the-standard-query-parser.html#escaping-special-characters) are `+ - && || ! ( ) { } [ ] ^ " ~ * ? : /`, which should be escaped with backslashes. When I send a query to Metacat with any of those characters, it looks like the character is completely ignored.

## Steps to reproduce

When I search dev.nceas for all metadata docs, I get 18,713 results:

https://dev.nceas.ucsb.edu/knb/d1/mn/v2/query/solr/?q=formatType:METADATA&rows=0&wt=json

```json
{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"formatType:METADATA",
      "fq":"(readPermission:\"public\")OR(writePermission:\"public\")OR(changePermission:\"public\")OR(isPublic:true)",
      "rows":"0",
      "wt":"javabin",
      "version":"2"}},
  "response":{"numFound":18713,"start":0,"numFoundExact":true,"docs":[]
  }}

```

When I include a filter for a reserved character, I should get less than 18,713. For example, if I search for the string `+ - || ! ( ) { } [ ] ^ " ~ * ? : /` (escaped and URL-encoded):

https://dev.nceas.ucsb.edu/knb/d1/mn/v2/query/solr/?q=formatType:METADATA%20AND%20%5C%22%5C%2B%20%5C-%20%20%5C%7C%5C%7C%20!%20%5C(%20%5C)%20%5C%7B%20%5C%7D%20%5C%5B%20%5C%5D%20%5C%5E%20%5C%22%20%5C~%20*%20%5C%3F%20%5C%3A%20%5C%2F%5C%22&rows=0&wt=json

I still get 18,713 results:

```json
{
  "responseHeader":{
    "status":0,
    "QTime":2,
    "params":{
      "q":"formatType:METADATA AND \"\\  \\- \\|\\| \\! \\( \\) \\{ \\} \\[ \\] \\^ \\\" \\~ \\* \\? \\: \\/\"",
      "fq":"(readPermission:\"public\")OR(writePermission:\"public\")OR(changePermission:\"public\")OR(isPublic:true)",
      "rows":"0",
      "wt":"javabin",
      "version":"2"}},
  "response":{"numFound":18713,"start":0,"numFoundExact":true,"docs":[]
  }}

```

## Expected behavior

I would expect to get only the search results that have that exact string `+ - || ! ( ) { } [ ] ^ " ~ * ? : /`.

## Related issue
I also noticed that ampersands in Solr queries, even when properly escaped with backslashes, cause Solr errors. See #1576

**Comment by taojing2002** [comment]
I tried to search "+" directly against the solr server bypassing Metacat. It should return at least one document since I added one document containing those special character on its abstract. However, it returned zero:
```
tao$ curl http://localhost:8983/solr/metacat-index/select?q=%5C%2B
{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"\\+"}},
  "response":{"numFound":0,"start":0,"numFoundExact":true,"docs":[]
  }}

```
In the response, the q value is `\\+` rather than `\+`. 

It sounds like a solr configuration issue.

**Comment by laurenwalker** [comment]
@taojing2002 Thanks for looking into it, Jing. So does it look like we can configure the default behavior in Metacat and in our deployments to allow searches for these characters?

**Comment by taojing2002** [comment]
Currently we use the `text_general` field to store text strings. This field uses StandardTokenizerFactory for index and query, which rips extraneous character such as those special characters. If we change it to WhiteSpaceTokenizerFactory in the schema and reindex the entire documents, the problem should be fixed. 
We talked about this issue on our weekly developer meeting and decided it is not necessary to support the search of those special characters.
