### ISSUE TITLE
OSTI DOI Plugin Notifications need more information 

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacat#1588]
The OSTI DOI plugin will email the configured email on error. However, it is hard to tell which systems is sending the error email. It would be nice of the email subject and body had information about which system is sending the error message.

**Comment by mbjones** [comment]
@vchendrix The commit in sha 6813fbd on branch https://github.com/NCEAS/metacat/tree/feature-1588-osti-doi-emails contains a proposed change that would provide the server name in the email from the metacat service. The email would now be of the following form:

```
Subject: OSTI Errors from data.ess-dive.lbl.gov at Mon, 27 Jun 2022 07:28:12 z

Dear operators:

Metacat got the following error message when it interacted with the OSTI ELink Service.

Server: data.ess-dive.lbl.gov

--- Error text goes here ---

```

Would that satisfy the needs here? Feel free to propose other changes to the very simple class [`OstiErrorEmailAgent`](https://github.com/NCEAS/metacat/blob/feature-1588-osti-doi-emails/src/edu/ucsb/nceas/metacat/doi/osti/OstiErrorEmailAgent.java) that sends the emails.

@taojing2002 Once this is approved can you merge it into the next release?

**Comment by vchendrix** [comment]
> @vchendrix The commit in sha 6813fbd on branch https://github.com/NCEAS/metacat/tree/feature-1588-osti-doi-emails contains a proposed change that would provide the server name in the email from the metacat service. The email would now be of the following form:
> 
> 
> 
> ```
> 
> Subject: OSTI Errors from data.ess-dive.lbl.gov at Mon, 27 Jun 2022 07:28:12 z
> 
> 
> 
> Dear operators:
> 
> 
> 
> Metacat got the following error message when it interacted with the OSTI ELink Service.
> 
> 
> 
> Server: data.ess-dive.lbl.gov
> 
> 
> 
> --- Error text goes here ---
> 
> 
> 
> ```
> 
> 
> 
> Would that satisfy the needs here? Feel free to propose other changes to the very simple class [`OstiErrorEmailAgent`](https://github.com/NCEAS/metacat/blob/feature-1588-osti-doi-emails/src/edu/ucsb/nceas/metacat/doi/osti/OstiErrorEmailAgent.java) that sends the emails.
> 
> 
> 
> @taojing2002 Once this is approved can you merge it into the next release?

@mbjones @taojing2002 That is perfect.

**Comment by taojing2002** [comment]
@mbjones @vchendrix It looks good to me as well. I merged the feature branch to the develop branch.
