### ISSUE TITLE
Reimplement the feature of resubmitting failed index tasks

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1603]
Currently the class of IndexGeneratorTimerTask.java in  metacat-index can resubmit the failed index tasks periodically.  However, the implementation directly uses the hazelcast code, which is obsoleted in this release. We need to reimplement the class in the metacat component.

**Comment by taojing2002** [comment]
We found there is a database table (i`ndex_event`) and java class  `IndexEventDAO` behind hazelcast. So now we directly use the code in Metacat.

**Comment by taojing2002** [comment]
Now, the feature, which resubmits the index tasks which fails to be put into RabbitMQ (e.g., the RabbitMQ is down), has been done. 

However, we still need to think about how to resubmit the index tasks, which fail in Dataone-Index.

**Comment by artntek** [comment]
see https://github.com/DataONEorg/dataone-indexer/issues/23
