### ISSUE TITLE
Reimplement d1/mn/v2/monitor/status

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1609]
`d1/mn/v2/monitor/status` will return the size in the index queue. Currently we get it from the size of a hazelcast queue. Since hazelcast is removing, we need to reimplement this feature base on rabbitmq.

**Comment by mbjones** [comment]
Given that the dataone-indexer will no be a separate service, do we want to keep this /monitor API in metacat? I suppose it will be accessible as we already have the rabbitmq credentials, so maybe re-implementation wouldn't be too hard.

**Comment by taojing2002** [comment]
Good question, Matt! I was thinking if we still really need to keep this
monitor API in metacat since RabbitMQ has a good interface to look at it
inside. However, I think it is good to have this api for
non-metacat-operator users with an idea how long it will take to index
their objects.

**Comment by mbjones** [comment]
@taojing2002 If you remember from our design diagram and discussion, we talked about adding a monitoring API to the index service itself. I'm not sure we really want to expose the rmq service per se. Let's discuss next week. If we do decide to implement it in the indexer, then it probably can be removed from Metacat.

**Comment by taojing2002** [comment]
The support was removed.
