### ISSUE TITLE
Change `edu.ucsb.nceas.metacat.oaipmh` code so it uses PropertyService instead of manipulating `metacat.properties` directly

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1632]
Related to epic #1611

Code in the package `metacat/src/edu/ucsb/nceas/metacat/oaipmh` [accesses the metacat.properties file directly](https://github.com/NCEAS/metacat/blob/develop/src/edu/ucsb/nceas/metacat/oaipmh/provider/server/OAIHandler.java#L369)

- This code is still in use by about 6 orgs. 
- Need to change code so it uses PropertyService instead of metacat.properties (thus picking up the recent site properties overlay functionality). 
- Originally created to be metacat-agnostic; OK to make it metacat specific if needed
-

**Comment by taojing2002** [comment]
Now it load properties from PropertyService rather than the metacat.properties file.
