### ISSUE TITLE
Release Notes and Metacat Legacy Deployments Outreach

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1671]
Metacat 3.0.0 will introduce some breaking changes. This issue is intended to keep track of any communications/outreach we need to do, to help organizations navigate the upgrade, if they have much older versions of Metacat installed

**Comment by artntek** [comment]
## Skins-based Metacat deployments

[This is a list of known organizations](https://docs.google.com/spreadsheets/d/1ioh2dpaJsOdSftEg7pYpj8Tn9Pg4by62YHmR-79zCPQ/edit?usp=sharing) that still have skins-based deployments of Metacat.

We can reach out about their upgrade path in light of our upcoming breaking changes for Metacat v3.0.0

**Comment by mbjones** [comment]
# Morpho no longer supported

In 3.0.0, we no longer support the original Metacat API, and therefore all Morpho clients (and other clients that depend on the old API) will no longer work.  Client access can be done via the DataONE API.

For reference, we did work on a version of Morpho ([milestone 2.0.0](https://github.com/NCEAS/morpho/milestone/20))  that works against the DataONE API, but it never got released due to some blockers and lack of resources to complete it. It was very close though.

**Comment by artntek** [comment]
With the 3.0.0 release, we want to issue a DOI, and make sure our release notes have a good description of what to look out for when upgrading, and the features that have been removed

**Comment by mbjones** [comment]
to add to this, ESS-DIVE doesn't even use the skin for a UI per se -- instead, they are using it to trigger an XSLT transform, just as we are doing in the "metacatui" skin. Neither of those cases use the skins structure for a UI directly but indirectly it is used to configure XSLT.

**Comment by doulikecookiedough** [comment]
The first draft for the 3.0.0 release notes have been added to branch [feature-1671-release-docs](https://github.com/NCEAS/metacat/tree/feature-1671-release-docs) in the `RELEASE-NOTES.md`

Upgrade notes and breaking change notes will be discussed during the next backend meeting.

**Comment by doulikecookiedough** [comment]
I have added upgrade notes to `RELEASE-NOTES.md` based on Jing's [upgrade notes document](https://hpad.dataone.org/3AWQRgIETY-eA9iicc6qog?view), and updated `README.md` with ORCIDs for the current contributors and NCEAS & DataONE banners at the bottom.
- [x] Add ORCID identifiers for the 4 current authors
- [x] add the NCEAS and DataONE banner images to the README (decide on bottom or top)

To Do:
- [ ] **Add a DOI and citation to the README at the top**
