### ISSUE TITLE
Issues to support OAI-PMH harvester, provider and LTER harvester

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1690]
Both LTER and OAI-PMH harvesters use the Metacat client library to log-in and insert/update objects. The Metacat client library is based on the Metacat API and our goal to disable the API in 3.0.0 will make the client library invalid. So both harvester services will be invalid as well. In our today's dev meeting, Matt said it was fine to NOT support the two harvesters. So I am going to remove the source/test code for both harvester.

 Matt also mentioned we should keep the OAI-PMH provider service on Metacat. I went through the code and found the OAI-PMH provider has its own servlet class (fortunately it is not exposed by the Metacat API) and also uses the Metacat client library to get content of a given docid (unfortunately). However, it seem there is only one place (line 362 in `edu.ucsb.nceas.metacat.oaipmh.provider.server.catalog.MetacatCatalog` class) using  the Metacat client:
```
     /* Perform a Metacat read operation on this docid */
        Metacat metacat = MetacatFactory.createMetacatConnection(metacatURL);
        Reader reader = new InputStreamReader(metacat.read(docid));
        StringBuffer stringBuffer = IOUtil.getAsStringBuffer(reader, true);
        String emlString = stringBuffer.toString();
        recordMap.put("recordBytes", emlString);
```
It seems we can change it easily to use the DataONE api after we transform the docid to a PID.  However, the testing is an issue since we don't have any test classes for this OAI-PMH part in Metacat.

**Comment by taojing2002** [comment]
The harvester client for LTER was removed by the commit 9079404d..820d5953.

**Comment by taojing2002** [comment]
It seems the OAI provider loads the metacat.properties file directly into a property object. It doesn't work now since we are using the relay mechanism.

**Comment by artntek** [comment]
related to Issue #1632

**Comment by taojing2002** [comment]
Results:
- Both LTER and OAI-PMH harvesters are removed.
- The OAI-PMH provider service still function after some modification.
