### ISSUE TITLE
Un-hack Metacat use of Port Numbers to Determine https vs http

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1697]
Metacat currently serves traffic via https only if the `server.httpPort` AND the `server.httpSSLPort` are BOTH set to 443. This is confusing and error-prone, and means we can't directly tell if metacat urls should be http or https for other applications (e.g. see #1700). 

Fixing it will also allow us to automatically configure the base metacat url used by the `dataone_indexer`, since that currently assumes https, and therefore breaks on non-SSL deployments.

When Jing and I were discussing this, we decided an approach like this could work:

```
server.name=localhost
server.httpPort=8443
server.isSSL=true
```

**Comment by taojing2002** [comment]
@artntek What about those name?
```
server.name=localhost
server.webPort=8443
server.https=true
```
`httpPort` implies `http`, not `https`. `webPort` seems neutral.
`ssl` may be too technical.

**Comment by taojing2002** [comment]
@artntek I updated the above comment.

**Comment by artntek** [comment]
Works for me!
