### ISSUE TITLE
CN/MN.archive method doesn't handle DRYAD identifiers correct

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1711]
When Ian and I tried to archive DRYAD objects by curl command, it always gave us error messages saying the object doen't exist. It only read part of the identifier. But the getSystemMetadat method handles the DRYAD pid correctly.

**Comment by mbjones** [comment]
@taojing2002 could you put the exact error message here please? I looked into this yesterday and its not obvious why the PID-encoding/decoding failed when it works for other API calls like `/meta`.

**Comment by taojing2002** [comment]
@mbjones 
This meta command works:
```
curl -s "https://cn.dataone.org/cn/v2/meta/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.12%3Fver%3D2017-08-29T11%3A52%3A08.075-04%3A00"
```
If I just change `meta` to `archive` on the url and it doesn't work:
```
root@cn-ucsb-1:/usr/share/dataone-cn-index# curl -E /etc/dataone/client/private/urn_node_CNUCSB1.pem -s -X PUT "https://cn.dataone.org/cn/v2/archive/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.12%3Fver%3D2017-08-29T11%3A52%3A08.075-04%3A00"
<?xml version="1.0" encoding="UTF-8"?><error detailCode="4971" errorCode="404" name="NotFound">
    <description>No system metadata could be found for given PID: http:/dx.doi.org/10.5061/dryad.12</description>
</error>
```

**Comment by mbjones** [comment]
Thanks, Jing. The error is helpful, as it shows two separate issues with the PID that is returned:

1. One of the forward slashes got stripped out
2. The query string following the `?` was truncated. 

This should help track down the parsing error. We could probably add some unit tests that use the encoded PID as input and see which one of the decoding methods outputs the incorrect decoding.

**Comment by taojing2002** [comment]
After preliminary investigation, it seems that the issue is not in Metacat. I called `MN.archive` and `CN.archive` against `dev.nceas` about a non-existing pid, and the result shows the pid is correct:
```
curl -H "Authorization: Bearer $token" -X PUT "https://dev.nceas.ucsb.edu/knb/d1/cn/v2/archive/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.12%3Fver%3D2017-08-29T11%3A52%3A08.075-04%3A00"
<?xml version="1.0" encoding="UTF-8"?><error detailCode="4971" errorCode="404" name="NotFound">
    <description>No system metadata could be found for given PID: http://dx.doi.org/10.5061/dryad.12?ver=2017-08-29T11:52:08.075-04:00</description>
```
```
curl -H "Authorization: Bearer $token" -X PUT "https://dev.nceas.ucsb.edu/knb/d1/mn/v2/archive/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.12%3Fver%3D2017-08-29T11%3A52%3A08.075-04%3A00"
<?xml version="1.0" encoding="UTF-8"?><error detailCode="1800" errorCode="404" name="NotFound">
    <description>No system metadata could be found for given PID: http://dx.doi.org/10.5061/dryad.12?ver=2017-08-29T11:52:08.075-04:00</description>
</error>
```
So I uploaded two objects to `dev.nceas` with the dryad style pids, then archived them. The `MN.archive` call succeeded; the `CN.archived` failed since `dev.nceas` is a v2 mn.
```
curl -H "Authorization: Bearer $token" -X PUT "https://dev.nceas.ucsb.edu/knb/d1/mn/v2/archive/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.12%3Fver%3D2017-08-29T11%3A52%3A08.075-04%3A00"
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<identifier xmlns="http://ns.dataone.org/service/types/v1">http://dx.doi.org/10.5061/dryad.12?ver=2017-08-29T11:52:08.075-04:00</identifier>
```
```
curl -H "Authorization: Bearer $token" -X PUT "https://dev.nceas.ucsb.edu/knb/d1/cn/v2/archive/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.12%3Fver%3D2017-08-29T11%3A52%3A08.075-05%3A00"
<?xml version="1.0" encoding="UTF-8"?><error detailCode="4970" errorCode="401" name="NotAuthorized">
    <description>The Coordinating Node is not authorized to make systemMetadata changes on this object. Please make changes directly on the authoritative Member Node.</description>
</error>
```

**Comment by taojing2002** [comment]
I guess the cn proxy somehow use the web container to decoded url before it passes the url to Metacat. Base on my investigation, the url after decoding by the web container is: (note: a `/` is missing)
```
http:/dx.doi.org/10.5061/dryad.12?ver=2017-08-29T11:52:08.075-04:00
```
This decoded url is passed to Metacat. Since there is a `?`, Metacat thinks it has a query string, not a part of path info. So eventually, Metacat thinks the pid is:
```
http:/dx.doi.org/10.5061/dryad.12
```

**Comment by taojing2002** [comment]
Filed a [ticket](https://github.com/DataONEorg/d1_cn_rest/issues/3) on `d`_rest`.
