### ISSUE TITLE
Should we prevent MetacatServlet startup if the initSecondHalf method fails?

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1721]
In the MetacatServlet class, we have a method named initSecondHalf, which registers all services. If it fails, Metacat will prevent any old Metacat API calls. But we removed all old Metacat API calls, this mechanism doesn't work anymore. We need to another mechanism to prevent MetacatServlet startup if that method fails.

**Comment by mbjones** [comment]
I'm pretty sure that @artntek added some new checks on Metacat startup to ensure things are properly working -- and to exit metacat if they fail. Maybe we can reuse that same mechanism? The `initSecondHalf` method has always felt a bit mysterious to me.

**Comment by artntek** [comment]
https://github.com/NCEAS/metacat/tree/develop/src/edu/ucsb/nceas/metacat/startup
