### ISSUE TITLE
Remove reference to HarvesterRegistration from web.xml

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1736]
This exception happens on startup, because tomcat is trying to load the HarvesterRegistration servlet (via `web.xml`), but the class `edu.ucsb.nceas.metacat.harvesterClient.HarvesterRegistration` has been removed from the codebase:

```console
16-Nov-2023 02:05:49.429 INFO [main] org.apache.catalina.core.ApplicationContext.log Marking servlet
 [HarvesterRegistration] as unavailable
16-Nov-2023 02:05:49.429 SEVERE [main] org.apache.catalina.core.StandardContext.loadOnStartup
 Servlet [HarvesterRegistration] in web application [/metacat] threw load() exception
	java.lang.ClassNotFoundException: edu.ucsb.nceas.metacat.harvesterClient.HarvesterRegistration
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1329)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141)
		at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:488)
```

**Comment by artntek** [comment]
Also noticed we still have a [harvester login jsp](https://github.com/NCEAS/metacat/blob/d0908bba09837b0cad8a7da629726fd8e849bb15/lib/style/skins/default/harvesterRegistrationLogin.jsp#L35) that likely needs removing?

**Comment by taojing2002** [comment]
The servlet was removed from the web.xml and the branch was merged into the develop branch.
