### ISSUE TITLE
K8s Migration: from legacy solr core to k8s collection

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1754]
test, refine & document migration steps to k8s from an existing legacy deployment for Solr sub-chart.

For the subsequent reindex action, see [indexer issue #52](https://github.com/DataONEorg/dataone-indexer/issues/52)

**Comment by taojing2002** [comment]
We don't support solr upgrade for 3.0.0 from the old cores. Solr must have a new core for 3.0.0.
