### ISSUE TITLE
The catalog_id is null in the xml_documents table for eml

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1768]
It should not be null. We need to take a look.

**Comment by vchendrix** [comment]
Where is this set?
+++++++++++++++++++++++++++++++++
Valerie Hendrix
***@***.***
Lawrence Berkeley National Lab

Mail Stop: 50B-2239
Room:      50B-2258E
Phone:     (510) 495-2905
Pronouns: she/hers
+++++++++++++++++++++++++++++++++

**Comment by taojing2002** [comment]
Hi Val:

It was set in the DocumentImpl class. This is a new bug introduced in our
development of 3.0.0. Our previous release versions don't have the issue.

Thanks,

Jing

**Comment by taojing2002** [comment]
In this commit feature-1620-remove-metacat-replication 2da97bf9, the bug was fixed. The reason is that we didn't modify the code to look up catalog id in DBSAXHandler after we removed the EMLSAXHandler class.
