### ISSUE TITLE
Backup the data from eliminated  tables into csv files 

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1777]
In Metacat 3.0.0 release, those tables will be dropped:

- xml_path_index
- xml_queryresult
- xml_returnfield
- xml_accesssubtree
- xml_index
- xml_nodes_revisions
- xml_nodes
- xml_replication

Those tables will drop some columns:

- xml_revisions
- xml_documents

Since the tables of `xml_path_index`, `xml_queryresult`, `xml_returnfield`, `xml_index` relate to the path query search, which we don't support, we don't need to backup them. The table of `xml_accesssubtree` is for a feature to control of sub-sections in an eml object, which we haven't been used for a long time, this table we don't need to backup.

So the tables we need to backup into csv files are:
- xml_nodes_revisions
- xml_nodes
- xml_replication
- xml_revisions
- xml_documents

Some concerns:
1. Where do we store those backup files?
2. The xml_nodes and xml_nodes_revisions can be huge, it may take a while and a large space.

**Comment by taojing2002** [comment]
Maybe we put the csv file into the Metacat backup directory, which stores the configuration backups now.

**Comment by mbjones** [comment]
Thanks @taojing2002 

`xml_nodes_revisions` and  `xml_nodes` could be reconstructed from the raw metadata documents, right? So maybe those don't need to be backed up?

**Comment by taojing2002** [comment]
@mbjones You are right. But I was worrying about some very old objects which only are stored in the `xml_nodes` (or `xml_nodes_revsions` table), not in the file system.  
I was thinking through it more. We already have a feature to write objects from the `xml_nodes` (or `xml_nodes_revisions`) table to files if they are only stored in database during the Metacat 3.0.0 upgrade process. So we don't need to back up all records of `xml_nodes` and `xml_nodes_revisions`.  However, if the writing to files process for an object fails, we need to back up the record into a csv file (KNB has 5 objects which failed to be written to the files since they have non-regular docid (doi://xxxx)).  

So those tables need to be backed up:
- xml_replication
- xml_revisions
- xml_documents

Those tables need be backed up partially (only records don't be in the file system)

- xml_nodes_revisions
- xml_nodes

What do you think?

**Comment by mbjones** [comment]
Please get input from @artntek,but I think that issue can be safely ignored, especially if you are already saving the few docs not already on the file system. Just be sure that if an error occurs in that process, either a good notification happens, or maybe the upgrade aborts?

**Comment by artntek** [comment]
To clarify: Let's consider the knb example [mentioned by @taojing2002 above](https://github.com/NCEAS/metacat/issues/1777#issuecomment-1894640756), where 5 documents fail the file backup.

If an operator did the upgrade, and there is a good notification, [as described by @mbjones](https://github.com/NCEAS/metacat/issues/1777#issuecomment-1895840560), then, as I understand it, there will be no existing file backup of those 5 records.

What should the operator do, in order to remedy the situation?

**Comment by mbjones** [comment]
Yeah, "maybe the upgrade aborts" is the better solution, but we should try really hard to handle errors in saving those files. The only non-recoverable reasons it might fail would be system issues like a full disk, in which case the upgrade should likely abort anyways.

**Comment by taojing2002** [comment]
This issue should be very rare when Metacat writes data to files from db during the upgrading process.  I guess maybe only KNB can happen since we manipulated the database somehow.  So I just give a chance to save those 5 objects in a backup file. I agree to give users a warning is a good idea. Abort maybe overkills. It is very hard to operators to remedy the issues.

**Comment by mbjones** [comment]
I think if we abort the upgrade, we should be providing enough info that a good sysadmin can fix the problems and try the upgrade again. For example, if their disk is full, preventing the files from writing, or if they don't have adequate permissions, then the upgrade aborts and they fix the issues and try again.
