### ISSUE TITLE
Object endpoint raise error code on DOI plugin  when no DOI found

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacat#1781]
This is related to nceas/metacatui#2167

We had an issue this week where a user received an error when they were saving a dataset and the resource map was not created in metacatUI.

The confluence of issues
1)  data.ess-dive.lbl.gov was inundated ( and still currently is) with indexing tasks for replication verifications. There are lots of dirtySystemMetadata requests in the apache logs
2)  The user received an error in the UI when saving.  Their metadata changes where updated but the resource map failed to create.  They emailed us with an urgent request to fix due to the fact that they told 150+ people the data was ready
3) We repaired the resource map from the backend by associating the data files from listed in the metadata file which also matched the previous version of the dataset
4) We found a draft dataset record for the metadata file that received the error  the told us the doi for the updated dataset could not be found. 

> EML draft for ess-dive-e976198fe417dbb-20231222T191240371(WHONDRS River Corridor Dissolved Oxygen, Temperature, Sediment Aerobic Respiration, Grain Size, and Water Chemistry from Machine-Learning-Informed Sites across the Contiguous United States (v3)) by Brieanne Forbes. This EML had the following save error: `MNodeService.update - The object ess-dive-e976198fe417dbb-20240109T184353161 has been saved successfully on Metacat.  However, the new metadata can't be registered on the DOI service: OSTIElinkService.getMetadata - the reponse is blank. So we can't find the identifier 10.15485/1923689, which type is doi`   ...

5) We manually looked up the doi in OSTI to confirm that is was there. It was.
6) I can only assume that the Metacat was overloaded with system metadata updates and this query failed to return a result due to the load in some way.

This particular error is of no concern to the user and should not have affected the experience saving (since the metadata was updated anyway).  We already receive system emails for these errors.

**Solution Requested**
In the case where a DOI is not found and the metadata is updated a warning message should be returned with and HTTP status of 200 or some other 2XX code that signifies a successfully updated

**Comment by taojing2002** [comment]
As you suggested, in the both create/update method Metacat doesn't return a non-200 http status if the DOI registration/update fails. It will return 200.

**Comment by mbjones** [comment]
This is great, and I agree with the change. That said, when we get DOI failures, especially fixable errors from EZID/OSTI/DataCite being down, do we have a menchanism to track and retry the DOI metadata updates or minting ops?

**Comment by taojing2002** [comment]
Unfortunately, we don't have the mechanism. We only have the mechanism to
re-try if the password doesn't work.
