### ISSUE TITLE
v3.0.0 RC Installation, Migration and Upgrade Dry Run (KNB corpus)

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1797]
Prior to releasing Metacat 3.0.0, we need:
* more in-depth testing, especially in k8s. 
* to determine what are the steps needed to upgrade from 2.19.x (including solr and postgres), and document these (see #1754 and #1753).

We therefore propose to carry out the following steps to perform a dry run of the KNB upgrade/k8s deployment

> **NOTE: update the upgrade documentation in the admin guide** for each step...

1. Work with @nickatnceas to copy production data for testing (see [directory layout below](https://github.com/NCEAS/metacat/issues/1797#issuecomment-1944180382)): 
    - [x] Copy the production postgres data (`knb:/var/lib/postgresql`) to the ceph volume at `/mnt/ceph/repos/knb/postgresql`
        * Matt said: "note that the postgres data should be in a consistent state to restart the database -- not sure what that means in terms of WAL files and stuff. probably need to treat it like a hot backup"
    - [x] copy the production data from `knb:/var/metacat` to the ceph volume at `/mnt/ceph/repos/knb/metacat`
        - [x] Time how long this takes (~6TB), and, based on this...
        - [x] advise on the best strategy so we can revert after testing (see below), without needing to re-copy across from knb again. Examples: 
            * make an initial backup copy (`cp -r`) on the same ceph volume, and then rsync to bring up to date before live release?
            * use hard links for testing, since no files are edited, only new ones added (is this true??)
            * Or just bite the bullet and re-copy everything when the real deployment happens?
            * or some other option?
        - Nick said: "restoring the Ceph copy with another rsync from production would save time over making a second copy"

1. Create Persistent Volumes
    - [x] Set up a PV to point to `/mnt/ceph/repos/knb/metacat` for metacat.
    - [x] Set up a PV to point to `/mnt/ceph/repos/knb/postgres` for postgres
    - [x] ~~Set up a PV to point to old solr data (`/mnt/ceph/repos/knb/metacat/solr`)~~ Solr must re-index all for v3.0.0, so we don't need to transfer old index

1. Then do the manual upgrade steps:
    - [x] to be compatible with PG-14 (was already v14)
    ~~to be compatible with solr 9~~

1. Deployment
    - [x] Create new values.yaml overrides to mirror ADC production installation. 
    - [x] When major changes are complete (wait until indexer auth changes finished?), deploy to dev cluster

1. Testing: Run any existing client-library test suites we have available:
    - [x] [R Client tests](https://github.com/dataoneorg/rdataone)
    - [x] [Python tests](https://github.com/dataoneorg/lib_client/src/d1_client/tests)
    - [x] Ask Robyn to run MetacatUI tests against k8s backend - none available
    - [x] What other testing options are available?

**Comment by mbjones** [comment]
Added
Links to R and Python tests.

**Comment by artntek** [comment]
This is the directory structure @mbjones and I agreed on for the ceph volume

```shell
/mnt/cephfs
├── curation
├── home
│   ├── jones
│   ├── jrando
│   └── outin
├── repos
│   ├── arctic
│   │   ├── data
│   │   │   └── 10.18739
│   │   │       ├── A2025R
│   │   │       ├── A20863712
│   │   │       └── A2251FM67
│   │   ├── hashstore
│   │   ├── index
│   │   ├── metacat
│   │   ├── postgres
│   │   ├── solr
│   │   └── tiles
│   │       └── 10.18739
│   ├── drp
│   │   ├── data
│   │   │   └── 10.57902
│   │   │       ├── D70590
│   │   │       └── D71599
│   │   ├── hashstore
│   │   ├── metacat
│   │   ├── postgres
│   │   └── tiles
│   │       └── 10.57902
│   └── knb
│       ├── data
│       │   └── 10.5063
│       │       └── F12V2DK1
│       ├── hashstore
│       ├── metacat
│       ├── postgres
│       └── tiles
│           └── 10.5063
└── services
    └── metadig
```

**Comment by nickatnceas** [comment]
Here are the changes I've made to mn-ucsb-4 so far:

- Added a Ceph subnet NIC to the VM
- Configured networking for new NIC enp5s0 in `/etc/network/interfaces`
- Installed Ceph packages
- Installed Ceph conf, auth files, and fstab config in `/etc` for pdg-subvol
- Mounted pdg-subvol to `/mnt/ceph`
- Copied `/var/lib/postgresql/` to `/mnt/ceph/repos/knb/postgresql/` (`cp -a`)
    - 256 GiB, it took 100m14.908s (43.7 MiB/sec)
- Started copying  `/var/metacat/` to `/mnt/ceph/repos/knb/metacat/` (`cp -a`)

I will time updating both copies with rsync later.

**Comment by nickatnceas** [comment]
`/var/metacat/` to `/mnt/ceph/repos/knb/metacat/` `cp -a` process has copied 3.6 TiB over the last 24 hours

**Comment by nickatnceas** [comment]
the metacat copy finished, it took a little over 37 hours:
```
root@mn-ucsb-4:/var/metacat# time cp -a * /mnt/ceph/repos/knb/metacat/

real    2232m43.851s
user    0m31.515s
sys     279m30.690s
```

I'm timing rsync runs now.

**Comment by nickatnceas** [comment]
Rsync update times:
- Postgres:
    - After ~2 days: 49 min
    - Immediately after previous run: 8 min
- Metacat:
    - After ~4 hours: 4 min

Rsync commands:
```
time rsync -aHAX --delete --stats --human-readable /var/lib/postgresql/ /mnt/ceph/repos/knb/postgresql/
time rsync -aHAX --delete --stats --human-readable /var/metacat/ /mnt/ceph/repos/knb/metacat/
```

**Comment by mbjones** [comment]
Thanks. So that looks like about 37 hours. So, what was the average speed for the full copy (I'm unsure how much total data was copied)?

**Comment by nickatnceas** [comment]
5654 GiB for /var/metacat/
43.5 MiB/sec

**Comment by artntek** [comment]
Thank you, @nickatnceas!

Based on these results, what do you recommend before I start messing up the data with testing? Should we make a full copy locally, to keep as a backup we can revert to later (and bring up to date with rsync)? Or is there a better approach?
