### ISSUE TITLE
Automatically added Escape sign in property files may cause issues 

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1808]
The property `auth.allowedSubmitters`  may have a list of the user names separated colon (:). If an individual name has the colon as well, the colon should be escaped by a backslash (\\). Here is an example for two user names:
```
auth.allowedSubmitters=http\://orcid.org/0000-0002-1209-5268:cn=parc,o=PARC,dc=ecoinformatics,dc=org
```
However, Java property file automatically adds the escape sign for colons, the new line will be:
```
auth.allowedSubmitters=http\://orcid.org/0000-0002-1209-5268\:cn\=parc,o\=PARC,dc\=ecoinformatics,dc\=org
```
So the two colons are identical now and will be treated as part of the user name. Metacat will think this is one user name rather than two.

**Comment by doulikecookiedough** [comment]
To clarify, when the properties file `metacat.properties` gets saved in `metacat/admin`, if an escape character is found, it gets automatically prepended with 2 additional escape characters in:

```
auth.allowedSubmitters=auth.allowedSubmitters=http\\\://orcid.org/0000-0002-1209-5268\:cn\=parc,o\=PARC,dc\=ecoinformatics,dc\=org
```

After discussing with @taojing2002 (who has already investigated/tested this potential problem), the additional escape characters do not cause any unexpected issues and is correctly interpreted by our services. I have added a comment in [Issue-1802](https://github.com/NCEAS/metacat/issues/1802) to improve the notes related to this issue to consolidate minor changes to formatting, commenting and linting.
