### ISSUE TITLE
Metacat config changes for `d1_portal`

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1812]
* change pom d1_portal version to 2.3.3

* add a field on metacat.properties file to specify the public cert:
```properties
cn.server.publiccert.filename=/Users/brooke/dev/GITHUB/DataONEorg/ca/DataONETestCAChain.crt;/Users/brooke/dev/GITHUB/DataONEorg/ca/DataONEProdCAChain.crt
```

* add a new field in the Metacat properties admin page for the `cn.server.publiccert.filename` property

**Comment by artntek** [comment]
Reopened for integration testing after [d1_portal bugfix](https://github.com/DataONEorg/d1_portal/pull/8/files#diff-ff30697ff7653f71e72e35b6bd66bb6b29fe1a8d0beae473ea1e437b8cb0e48e)

## Test Plan:

### Prerequisites

1. Install metacat from `develop`; go through the admin configuration steps; restart tomcat; check it's working by creating a dataset and making sure it gets indexed
2. Obtain 2 test JWT token files, each with Subject matching the default local metacat instance (`urn:node:METACAT1`), and place both in `/var/metacat/certs`:
    * One issued against the DataONE Test Intermediate CA - let's call this `d1-test-ca-token`
    * One issued against the Prod CN - let's call this `prod-cn-token`
5. Obtain copies of the **DataONE [Test CA (DataONETestCAChain.crt)](https://raw.githubusercontent.com/DataONEorg/ca/main/DataONETestCAChain.crt) and [Prod CA (DataONEProdCAChain.crt)](https://raw.githubusercontent.com/DataONEorg/ca/main/DataONEProdCAChain.crt) chains**, and place both in `/var/metacat/certs`
6. For each of the following scenarios,        
    * add the key `cn.server.publiccert.filename=` to the file `/var/metacat/config/metacat-site.properties`, if it doesn't already exist, and set to the value(s) shown in "Config:", below.
    * Look in the catalina.out logs for whatever's described in "Expected - grep for:", below
    * There should be no related ERRORS or stacktraces in the logs


### Certificate Loading Test Cases

1. No properties key, no errors
    * **Config:**
        * delete the key `cn.server.publiccert.filename=` from `$TOMCAT_HOME/webapps/metacat/WEB-INF/metacat.properties`, AND check it is not present in `/var/metacat/config/metacat-site.properties`
    * restart tomcat
    * **Expected - grep for:**
        * [INFO]: Successfully added cert from CN server

2. Key without value; no errors
    * **Config:**
        * Reinstate the key `cn.server.publiccert.filename=` (with no value) in `$TOMCAT_HOME/webapps/metacat/WEB-INF/metacat.properties`, AND check it is still not present in `/var/metacat/config/metacat-site.properties`
    * restart tomcat
    * **Expected - grep for:**
        * [INFO]: Successfully added cert from CN server

3. One local cert
    * **Config:**
        * `cn.server.publiccert.filename=/var/metacat/certs/DataONETestCAChain.crt`
    * restart tomcat 
    * **Expected - grep for:**
        * [INFO]: Successfully added cert from CN server
        * [INFO]: Successfully added cert: /var/metacat/certs/DataONETestCAChain.crt


4. Two local certs
    * **Config:**
        * `cn.server.publiccert.filename=/var/metacat/certs/DataONETestCAChain.crt;/var/metacat/certs/DataONEProdCAChain.crt` (Note semicolon-delimited)
    * restart tomcat 
    * **Expected - grep for:**
        * [INFO]: Successfully added cert from CN server
        * [INFO]: Successfully added cert: /var/metacat/certs/DataONETestCAChain.crt
        * [INFO]: Successfully added cert: /var/metacat/certs/DataONEProdCAChain.crt


### Token Verification Test Cases

With metacat in the state from test case 4 (i.e. 2 local certs loaded), do the following:


5. Indexer does NOT have a token
    * **Config:**
        * check the default value `dataone.nodeToken.file=/var/metacat/certs/token` that appears in metacat.properties has NOT been overridden in site properties
        * ensure you do NOT have a file at the path `/var/metacat/certs/token`
    * restart tomcat if anything changed
    * Log into metacatui, create a PRIVATE dataset, and verify it does NOT get indexed
    * (grep the logs for the PID, and you should see indexer errors)


6. Indexer has CN token
    * **Config:**
        * in site properties, set the override value: `dataone.nodeToken.file=/var/metacat/certs/prod-cn-token`
    * restart tomcat
    * Log into metacatui, create a PRIVATE dataset, and make sure it DOES get indexed


7. Indexer has D1 Test CA token
    * **Config:**
        * in site properties, set the override value: `dataone.nodeToken.file=/var/metacat/certs/d1-test-ca-token`
    * restart tomcat
    * Log into metacatui, create a PRIVATE dataset, and make sure it DOES get indexed

**Comment by doulikecookiedough** [comment]
@artntek Thank you for writing out this test plan! I have executed the instructions for each scenario and I did not encounter any unexpected results other than for scenario 6 where I encountered an exception RE: LDAP (stack trace included below). Please let me know if there is anything else you would like me to check.

**Prerequisites:**
1. Install Metacat
- [x] Installed fresh Metacat checkout from `develop`
- [x] Confirmed I can submit a dataset, and that it gets indexed.
2. Obtain test certificates
- [x] Confirm matching default local metacat instance (`urn:node:METACAT1`)
- [x] Place both into `/var/metacat/certs`
    - Placed DataONE Test Intermediate CA `d1-test-ca-token`
    - Placed Prod CN`prod-cn-token`
3. Obtain DATAONE Test CA and Prod CA .crt chains
- [x] Placed into `/var/metacat/certs`

**Certificate Loading Test Cases**

1. No properties key, no errors
    - No errors
    - Successful grep for `[INFO]: Successfully added cert from CN server`

2. Key without value; no errors
    - No errors
    - Successful grep for `[INFO]: Successfully added cert from CN server`

3. One local cert
    - Successful grep for `[INFO]: Successfully added cert from CN server`
    - Successful grep for `[INFO]: Successfully added cert: /var/metacat/certs/DataONETestCAChain.crt`

4. Two local certs
    - Successful grep for `[INFO]: Successfully added cert from CN server`
    - Successful grep for `[INFO]: Successfully added cert: /var/metacat/certs/DataONETestCAChain.crt`
    - Successful grep for `[INFO]: Successfully added cert: /var/metacat/certs/DataONEProdCAChain.crt`

5. Indexer does NOT have a token
    - Config:
        - [x] Default value `dataone.nodeToken.file=/var/metacat/certs/token` has not been overwritten in site properties
        - [x] No token at file path `var/metacat/certs/token`
    - I see the expected indexing errors, the dataset is not found in `metacatui/data`

6. Indexer has CN token
    - Config
        - [x] Site properties override value `dataone.nodeToken.file=/var/metacat/certs/prod-cn-token`
     - Confirming private dataset has been indexed (present in my datasets with a lock icon)
     - However, I do see some exceptions being thrown, not sure if this is expected or not:
      ```metacat 20240319-15:49:10: [INFO]: D1HttpRequest.getPathInfo - the new pathInfo which comes from requestURI is: /meta/resource_map_urn%3Auuid%3A6769fcf7-a6db-4ca9-95d8-6a6333b74d22 [edu.ucsb.nceas.metacat.restservice.D1HttpRequest:getPathInfo:73]
      metacat 20240319-15:49:10: [INFO]: MNResourceHandler.handle - V2 handling verb 1 request with resource 'meta/resource_map_urn%3Auuid%3A6769fcf7-a6db-4ca9-95d8-6a6333b74d22' [edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler:handle:216]
      metacat 20240319-15:49:10: [WARN]: [LDAP: error code 32 - No Such Object] [org.dataone.portal.TokenGenerator:getSession:326]
      org.dataone.service.exceptions.NotFound: [LDAP: error code 32 - No Such Object]
              at org.dataone.service.util.ExceptionHandler.deserializeXml(ExceptionHandler.java:629) ~[d1_common_java-2.3.0.jar:?]
              at org.dataone.service.util.ExceptionHandler.deserializeXmlAndThrowException(ExceptionHandler.java:517) ~[d1_common_java-2.3.0.jar:?]
              at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:363) ~[d1_common_java-2.3.0.jar:?]
              at org.dataone.service.util.ExceptionHandler.deserializeAndThrowException(ExceptionHandler.java:313) ~[d1_common_java-2.3.0.jar:?]
              at org.dataone.service.util.ExceptionHandler.filterErrors(ExceptionHandler.java:107) ~[d1_common_java-2.3.0.jar:?]
              at org.dataone.client.rest.HttpMultipartRestClient.doGetRequest(HttpMultipartRestClient.java:343) ~[d1_libclient_java-2.3.1.jar:?]
              at org.dataone.client.rest.HttpMultipartRestClient.doGetRequest(HttpMultipartRestClient.java:328) ~[d1_libclient_java-2.3.1.jar:?]
              at org.dataone.client.v1.impl.MultipartCNode.getSubjectInfo(MultipartCNode.java:1481) ~[d1_libclient_java-2.3.1.jar:?]
              at org.dataone.client.v1.impl.MultipartCNode.getSubjectInfo(MultipartCNode.java:1462) ~[d1_libclient_java-2.3.1.jar:?]
              at org.dataone.portal.TokenGenerator.getSession(TokenGenerator.java:324) [d1_portal-2.3.3.jar:?]
              at org.dataone.portal.PortalCertificateManager.getSession(PortalCertificateManager.java:299) [d1_portal-2.3.3.jar:?]
              at edu.ucsb.nceas.metacat.restservice.D1ResourceHandler.handle(D1ResourceHandler.java:162) [metacat.jar:?]
              at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.handle(MNResourceHandler.java:193) [metacat.jar:?]
              at edu.ucsb.nceas.metacat.restservice.D1RestServlet.doGet(D1RestServlet.java:95) [metacat.jar:?]
      ```
        
7. Indexer has D1 Test CA token
    - Config
        - [x] Site properties override value `dataone.nodeToken.file=/var/metacat/certs/d1-test-ca-token`
     - Confirming private dataset has been indexed (present in my datasets with a lock icon)

**Comment by artntek** [comment]
Thank you so much, @doulikecookiedough!

The stacktrace above is not critical. It's generated by the call to `D1Client.getCN().getSubjectInfo(subject);` in [this code snippet](https://github.com/DataONEorg/d1_portal/blob/bc17681b8e24758720f38feed685160f10c0290b/src/main/java/org/dataone/portal/TokenGenerator.java#L317):

```java
            SubjectInfo subjectInfo = null;
            try {
                subjectInfo = D1Client.getCN().getSubjectInfo(subject);
            } catch (Exception be) {
                log.warn(be.getMessage(), be);
            }

            // TODO: fill in more subject info if we didn't retrieve it
            if (subjectInfo == null) {

            // [...etc]

```

i.e. the code tries to get the subjectInfo, expects that call to possibly fail and logs a warning if it does, then tries a different method

**Comment by mbjones** [comment]
In general, can we avoid stack traces in the log unless the are associated with an error? Seems like an informative warning message with appropriate details should be sufficient and will be less alarming in the logs. I always feel like stack traces in the logs represent bugs we need to track down.

**Comment by artntek** [comment]
No objections from me

**Comment by artntek** [comment]
fixed in [indexer PR # 10](https://github.com/DataONEorg/d1_portal/pull/10)

**Comment by taojing2002** [comment]
@doulikecookiedough Did you test to index a private package?

**Comment by doulikecookiedough** [comment]
@taojing2002 Yes, it was working. The private datasets appeared in the portal with a lock icon beside the name.

**Comment by taojing2002** [comment]
@doulikecookiedough Thanks!
