### ISSUE TITLE
Do we change the delimiter for auth.allowedSubmitters?

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1843]
In previous versions, both `auth.allowedSubmitters` and `auth.administrators` used `:` as the delimiter. We changed the delimiter to `;` for `auth.administrators` since they use orchid (which contains `:`) now. Do we change the delimiter for `auth.allowedSubmitters` as well? Those two are main fields have multiple values,  which users will input. It may break current backup values in Metacat. But now is good time to make not-backward compatible change.

**Comment by taojing2002** [comment]
We use a public variable `AuthUtil.DELIMITER` to control the value of the delimiter. Its current value is `:`.  Besides `auth.allowedSubmitters`, `auth.deniedSubmitters` and `auth.moderators`, this delimiter also are used by `event.log.blacklist.ipaddress` and `event.log.blacklist.subject`.  Do we really want to change the behavior of the last two properties? The reason I asked the question is how we can let user know to change them since admin ui don't have fields for them. In README file?

**Comment by taojing2002** [comment]
Talked with Matthew and we decided `event.log.blacklist.ipaddress` and `event.log.blacklist.subject` should use the new delimiter as well since 3.0.0 is breaking stuff :) 
If I remember correctly, ESS-DIVE is the only group who use this feature.

**Comment by mbjones** [comment]
If you are changing the behavior of those two fields, could you rename them as well to use allow and deny terminology, rather than whitelist/blacklist? So, new property names might be `event.log.deny.ipaddress` and `event.log.deny.subject`, or something along those lines?

**Comment by taojing2002** [comment]
@mbjones Sure.
