### ISSUE TITLE
Give users a warning to choose a new solr-home for 3.0.0

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1847]
We decided we need to indexing all objects after users upgrade their Metacat to 3.0.0 since the compatibility issues. So users have to choose a new solr-home during the configuration. 
We should give warnings to users in the property and solr admin to choose a new solr home. Also ask them to reindex all objects after the configuration.

**Comment by doulikecookiedough** [comment]
I discussed with @taojing2002, and we came to the conclusion that users can use their existing solr-home when upgrading to Metacat 3.0.0 **_if_**:
- the current solr-home directory is empty.

So we will add a note in the global properties to remind operators regarding this Metacat 3.0.0 requirement.

**Comment by doulikecookiedough** [comment]
This has been completed via [Feature-1847: Solr Reminder when Upgrading to Metacat 3.0.0](https://github.com/NCEAS/metacat/pull/1877)
