### ISSUE TITLE
mn-sandbox-ucsb-2 doesn't like two administrators

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1856]
In the auth configuration page, it complains the two administrators don't match the orcid pattern. But it came from the backup value and it worked before. Actually `mn-sandbox-ucsb-1` does work with two administrator. Just `mn-sandbox-ucsb-2`. 
Here is the output:
```
****** START REQUEST PARAMETERS **********************
auth.administrators:
    http://orcid.org/0000-0002-1209-5268;http://orcid.org/0000-000D-1472-913X;
configureType:
    auth;
processForm:
    true;
```
If I deleted the second one, it worked. Here is the log:
```
auth.administrators:
    http://orcid.org/0000-0002-1209-5268;
configureType:
    configure;
    auth;
processForm:
    false;
    true;
```

**Comment by artntek** [comment]
closing - behaves as expected. There was a typo in the test input:

http://orcid.org/0000-000`D`-1472-913X;
