### ISSUE TITLE
Metacat can't build the user doc

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1871]
Here are commands I did:
```
cd docs/user/metacat
make html
```
And I got:
```
Theme error:
An error happened in rendering the page authinterface.
Reason: UndefinedError("'styles' is undefined")
make: *** [Makefile:42: html] Error 2
```

**Comment by taojing2002** [comment]
It works on my mac. But it doesn't work on ubuntu 22.04.

**Comment by taojing2002** [comment]
Mac version:
```
valley:metacat tao$ sphinx-build --version
sphinx-build 6.2.1
```
Ubuntu version:
```
tao@mn-stage-ucsb-2:~/projects/metacat/docs/user/metacat$ sphinx-build --version
sphinx-build 4.3.2
```
Ubuntu has an old version. But it is the newest one from its repository.

**Comment by doulikecookiedough** [comment]
Thank you for the additional context! I'm testing in `knbvm` and I see the issues now.

**Comment by doulikecookiedough** [comment]
This has been completed via [Bug-1871: Sphinx Autodocs Compilation Failure](https://github.com/NCEAS/metacat/pull/1872)
