### ISSUE TITLE
upgrade datacite metadata to v4.5

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1949]
This EZID/DataCiteservice update has several implications for our use of EZID in metacat repositories, and essentially forces a migration to DataCite v4.x for all of our metadata, and encourages v4.5. In particular:

- Creating and updating DOIs in schema versions older than 4.0 will no longer be supported in January of 2025
- Creating new DataCite metadata in 4.x will continue to be supported
- Moving to 4.5 allows us to add a ROR for publisher
 
 Let's discuss a path forward.

> From: Adam Buttrick <Adam.Buttrick@ucop.edu>
> Date: Thu, Jul 11, 2024 at 8:55 AM
> Subject: [EZID] New DataCite metadata/schema available in EZID
> To: <EZID-L@listserv.ucop.edu>
> 
> 
> Note: The following announcement pertains to EZID DataCite DOI users only. If you are not using EZID for DOIs, you can disregard this message. 
> 
> Hello, EZID users, 
> 
> EZID has recently been updated to support the latest version (4.5) of the DataCite metadata schema for DOIs. This means that EZID DataCite DOIs can take advantage of additional metadata fields to enhance the description and discoverability of the works they are associated with. For example:
> 
>     Users can now make use of two new resource type values: Instrument and StudyRegistration
>     The publisher property now supports use of a publisher identifier, such as a [ROR ID](https://ror.org/)[.](https://ror.org/)
> 
> This change affects EZID DataCite DOI users only. This change does not impact:
> 
>     Users who create and manage Crossref DOIs in EZID. If you are unsure as to whether you are using Crossref DOIs or DataCite DOIs, please contact [ezid@cdlib.org](mailto:ezid@cdlib.org).  
>     ARK services  
> 
> 
> You can read more about the DataCite schema [here](https://schema.datacite.org/meta/kernel-4.5/). While 4.5 is now the default schema for DOIs, prior iterations of schema version 4 will also still be supported. EZID will continue to support the following schema versions until January 2025, at which point they will have reached their end of life:
> 
>     3.x
>     2.x (note that this version is no longer supported by DataCite)
> 
> 
> As we get closer to this end of life date, we will notify any users with DOIs registered using the deprecated schema versions about the need to update their metadata. Barring correction, these records may be subsequently updated on said users behalf to ensure the continued functioning of the service. Beginning in January of 2025, registering DOIs in versions of the schema prior to 4.x will no longer be supported. Please see the DataCite documentation [here](https://datacite.org/blog/deprecating-schema-3/) for additional details about this change.
> 
> What this means for you:
> 
> If you register a new DOI:
> 
>     Via the EZID API: Make sure your XML header specifies version 4.5 (this will automatically support all metadata fields available in all minor schema versions associated with version 4.x.) and you can include all of the fields available as of [version 4.5](https://schema.datacite.org/meta/kernel-4.5/) to enrich the metadata for the DOIs you register.
>     Via the EZID UI registration form (“create IDs”): New DOIs registered via the form will have version 4.5 applied.
> 
> 
> If you have existing DOIs in EZID that use schema version 4.x:
> 
>     When you update your DOIs via the UI registration form, the latest schema version will automatically be applied. 
>     When you update your DOIs via the API with the default “datacite” profile as specified in the [EZID API documentation](https://ezid.cdlib.org/doc/apidoc.html), the latest schema version will automatically be applied. If the entire XML document is bound to the request, you will need to specify the updated version to take advantage of the new schema.
> 
> 
> If you have existing DOIs in EZID that use schema versions older than 4.0:
> 
>     We encourage you to update these DOIs at your earliest convenience so you can take advantage of the new metadata fields available and so you can avoid incompatibility issues later on.
>     You will need to specify schema version 4.5 in the header of your bound XML object if you are updating the DOIs via the API.
>     The latest schema version will automatically be applied if you update your DOIs via the UI. 
>     Creating and updating DOIs in schema versions older than 4.0 will no longer be supported in January of 2025.
> 
> 
> If you currently use EZID for DataCite DOIs and have questions about what these changes mean, please reach out and we’ll be happy to provide additional guidance. 
> 
> All the best,
> Adam
> ---
> Adam Buttrick, EZID Service Manager
> University of California Curation Center (UC3)
> California Digital Library
> University of California Office of the President

**Comment by taojing2002** [comment]
It is duplicated to https://github.com/NCEAS/metacat/issues/2003
