### ISSUE TITLE
The dataone admin page could not go through when upgraded Metacat to 3.1.0

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#1968]
When I upgraded `mn-sandbox-ucsb-1` to 3.1.0, the DataONE admin page couldn't go through and the error message says `can't register a new member node` even though the page shows the `update` button. I have to click the `bypass` button to finish the configuration.

**Comment by taojing2002** [comment]
When I upgraded the host of `dev.nceas.ucsb.edu`,  I didn't see this issue.

**Comment by artntek** [comment]
Was there anything in the logs that indicated why `mn-sandbox-ucsb-1` failed?

**Comment by taojing2002** [comment]
Hi Matthew:

Thank you for offering help when you are on vacation! Yeah, there was an
error message there indicating the certificate expired. I asked Dave to
generate a new one yesterday. Thank you for your help!

Regards,

Jing

**Comment by taojing2002** [comment]
Matthew generated the tokens for both `mn-sandbox-ucsb-1` and `mn-sandbox-ucsb-2`.
