### ISSUE TITLE
Document quickest way to dump the checksum table and load it again

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1991]
[See Matt's notes here in Issue #1984](https://github.com/NCEAS/metacat/issues/1984#issuecomment-2420645504)

Ideally, we need a checklist of commands to run, or a script that will do it for us, since this needs to be done quickly, to minimize downtime.

**Comment by taojing2002** [comment]
I added to two script files to backup/restore the checksums table. The usage is documented in the readme in the directory `metacat/src/scripts/sql/backup-restore-checksums-table`.
It uses the copy command as Matt suggested. It also drops the indexes, constrains and defaults before copy back. After copy, those dropped things are restored as well.

**Comment by artntek** [comment]
see PR #2000

**Comment by taojing2002** [comment]
Thank you for pointing out this issue. I modified the code to use heredoc and tested it to roll back successfully.
```
psql -d "$databaseName" <<EOF
BEGIN;
ALTER TABLE checksums ALTER COLUMN checksum_id DROP DEFAULT;
DROP INDEX IF EXISTS checksums_guid;
DROP INDEX IF EXISTS checksums_checksum_algorithm;
DROP INDEX IF EXISTS checksums_checksum;
ALTER TABLE checksums DROP CONSTRAINT IF EXISTS checksums_fk;
\COPY checksums FROM '$backupFilePath';
ALTER TABLE checksums ALTER COLUMN checksum_id SET DEFAULT nextval('checksums_id_seq');
SELECT setval('checksums_id_seq', (SELECT max(checksum_id) FROM checksums));
CREATE INDEX IF NOT EXISTS checksums_guid ON checksums(guid);
CREATE INDEX IF NOT EXISTS checksums_checksum_algorithm ON checksums(checksum_algorithm);
CREATE INDEX IF NOT EXISTS checksums_checksum ON checksums(checksum);
ALTER TABLE checksums ADD CONSTRAINT checksums_fk FOREIGN KEY (guid) REFERENCES systemMetadata DEFERRABLE;
COMMIT;
EOF
```

**Comment by artntek** [comment]
@taojing2002 made the above modification in PR #2006. @artntek added code to initialize required parameters form k8s environment.
