### ISSUE TITLE
Hashstore Conversion Changes

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#2013]
(discussion arising from errors seen during hashstore conversion of the ADC corpus)

During hashstore conversion, for cases where the calculated checksum does not match the checksum that's in system metadata:

- [x] Do not fail conversion.
- [x] Add the object to hashstore
- [x] Update the checksum in the system metadata (postgres and hashstore), so that it is correct for the actual object.
- [x] change the logging, so that `/var/metacat/.metacat/nonMatchingChecksum_{date}.txt` includes more information. Suggested additions:
  - [x] the GUID/PID (already logged)
  - [x] the checksum algorithm
  - [x] the old (incorrect) checksum
  - [x] new checksum
  - [ ] the docid and rev
  - [x] the relevant filepaths to the original files in the metacat `/data` and `/documents` directories
- [x] Jing will manually edit the CN entries to update the checksums that have changed (since the CN API considers checksums to be immutable)
* This approach means that all the data that was available before hashstore conversion will continue to be available after conversion, and the operator then has a reference list that enables them to resolve these checksum issues without holding up the conversion.
* We will adopt this approach as standard, for all conversions (not just ADC etc). For non-NCEAS-managed repos, we'll ask operators to first investigate and resolve any checksum discrepancies, and then send us a list of changes so we can update the CN on their behalf

**Comment by taojing2002** [comment]
The the relevant filepaths to the original files in the metacat /data and /documents directories contains the docid and rev. So the last two items needed to log seems redundant.

**Comment by mbjones** [comment]
@taojing2002 for most paths that makes sense, but the reason I thought we should include it is to deal with docids with illegal filename characters that get replaced by metacat with allowable characters. Maybe that algorithm is predictable enough that we don't need the path and can just reconstruct the path from the docid. But given that I think that algorithm was removed from the code in the 3.0.0 release when the MetacatAPi was removed, do we know how to construct the file paths for historical docids?

**Comment by taojing2002** [comment]
I forgot this point. I can't remember how we built them now.

**Comment by taojing2002** [comment]
I looked at the 2.9.0 branch and found we just use docid as the file name:
```
String newFileName = dataDirectory + File.separator + docid;
documentPath = documentDir + FileUtil.getFS() + accNumber;
```
So it seems if the docid has some non-allowable characters, Metacat will reject it.

**Comment by artntek** [comment]
To wrap this up - Jing and I discussed. The operator needs to know how to find the file in question, and since Jing already has the full file path in the code, he can log that.

In other words, since he is not inferring the path directly from the docid, then it doesn't really matter if metacat has sanitized any characters from the original docid/rev to create the filename in the first place.

We're therefore omitting the docid & rev from the log message (unless we're missing something?)
