### ISSUE TITLE
Allowed submitters list fails with groups

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacat#3]
As mentioned by @vchendrix, both the `auth.allowedSubmitters` and the `auth.administrators` properties need to allow for local authFile, local LDAP, and DataONE LDAP groups.  My thought is that we are not expanding all groups properly when comparing `Subject` strings in these lists.  For instance, when `auth.submitters` contains a value of `CN=ess-dive-users,DC=dataone,DC=org`, the members of this list need to be retrieved and compared to the group members for the authenticated user.

**Comment by taojing2002** [comment]
In order to to make dataone operations like replication work, I think we need to add CN and MN (itself) subjects as the default members of the `auth.allowedSubmitter` list.
