### ISSUE TITLE
Remove redundant test properties from metacat.properties 

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacat#32]
In the test part of metacat.properties, it has some redundant properties:

test.metacatUrl=http://localhost:8080/metacat/metacat
test.contextUrl=http://localhost:8080/metacat
test.workflowSchedulerUrl=http://localhost:8080/workflowscheduler/scheduler
test.metacatDeployDir=/opt/local/share/java/tomcat7/webapps/metacat

Those values are available in other properties. So we can remove them to simplify the test process.

**Comment by amoeba** [comment]
Hey @taojing2002, is this all done?
