### ISSUE TITLE
Feature request: Indexing status page

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#34]
I know at least I've been wanting this for a while. What if Metacat provided an easy way to see the status of the index? By status, I mean how many Objects are in the queue, and potentially, which Objects are in the queue. This would be helpful for us devs and data team members to know if we're overloading the index. It'd also be useful for users who have create/update(d) an Object but are waiting for it to index. If the index queue is empty and they don't see their Object in the index, they can assume indexing failed which is super useful as a first step in debugging indexing issues.

Couple of questions:

- Should this be public or admin-only? If it were public, the data team would be able to use this and they'd probably like this. I'd vote for public access for this reason.
- What information should it show?
  - Index queue size
  - Index queue members
  - Your amazing idea here

What do others think about this?

**Comment by mbjones** [comment]
Absolutely. I've wanted this for a while too.  And not just for indexing. It's good to see the state of all of our async jobs.

That said, I'm not sure we should invest in our current index code unless it's fast to pull off.  Peter is looking at RabbitMQ queues for metadig, and they should give us good APIs for queue size. Not so clear about queue contents. Let's discuss.

**Comment by laurenwalker** [comment]
This feature would be so helpful!

**Comment by amoeba** [comment]
Just thought of this yesterday while debugging queue issues: It'd be great to know the `submitter` (in d1 parlance) of the objects in the queue.

**Comment by jagoldstein** [comment]
Data team agrees that this would be a huge help for us if it were publicly accessible. 
Thanks @gothub for alerting us to this already existent issue.

Right now, metacat is essentially a black box for us in that we can't see what's going on in there.
It would be **super** helpful for us to have a tool to check the status of a `PID` in the indexing queue.

We often wonder if a `PID` has finished indexing or not, and if not, will it? If it will, when will this happen (how long will it take?)? (I believe that the number of objects ahead of it in the queue is likely our best proxy for **when** a `PID` will be done indexing.)

It would also be great to know if indexing failed, and if so, **why** it failed (what was the error?).


There are a number of things that occasionally go wrong, whether our fault or a failure of our systems, that influence our need for this. We have tried using `show_indexing_status` (from `arcticdatautils`) to get this info, but it does not provide the level of detail we usually want. This function only returns `0%` or `100%` indexed, but we have seen landing pages update well after getting the `100%` output.

**Comment by jagoldstein** [comment]
@csjx 's Slack message from #datateam on July 11, 2018:

"maybe we just need to have Metacat spit out an XML or JSON report that could be read into an R library or web view"

**Comment by laurenwalker** [comment]
Totally agree with @csjx. 

This feature would definitely be used by the new editor when there are indexing delays with resource maps.

**Comment by jagoldstein** [comment]
I'm glad to see this has been assigned to an upcoming Milestone. This would be **super** helpful to the support team (for arcticdata.io, in particular). Thanks devs.

**Comment by jeanetteclark** [comment]
Yup I agree - I'm reading this issue in between page-reloads to see if my resource map has been indexed...

**Comment by dmullen17** [comment]
This would be really useful for the upcoming metadata quality updates we'll need to do before NCEI replication.

**Comment by laurenwalker** [comment]
It would be great if we could support programatic access to the index queue so that MetacatUI can look up an object in the queue and display that information to the user. 

It's been an issue in the past when a new package has been submitted via the UI editor and the package gets put in the index queue. If you or someone else tries to access that package in the editor while it's still in the queue, the editor can't find the information necessary to load the package, so further edits break the package obsolescence chain. See https://github.com/NCEAS/metacatui/issues/610

Also, the package contents table shown on the MetadataView will not display correctly when the package isn't indexed yet.

**Comment by taojing2002** [comment]
First round, I will implement a` method /monitor/status`. This method will display the size of the index queue.

**Comment by taojing2002** [comment]
d731e5fc7d8c6e8ac974261ed5dbbb4634044a40

**Comment by laurenwalker** [comment]
This is great! For the second round, could we display the identifiers of each object in the queue?

**Comment by taojing2002** [comment]
Sure. I was thinking about the list of the identifiers as well. But it can get big and we may need to page it. So i delay it.
