### ISSUE TITLE
Public Read Access Policy Causes weird download behavior

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacat#4]
**Metacat Version**: 2.8.5

Metacat has some weird behavior when downloading datasets when the `accessPolicy` contains `public`,`read`.  

* `/v2/object/<id>`:  The behavior should download the entire package but instead only the Resource Map file is downloaded.  
* if `/v2/packages/application%2Fbagit-097/<id>` is accessed the name of the Zip file should be `<Dataset Title>.zip` but instead it is `urn_uuid_<id>.zip`. While this is not a show stopper it is not very user friendly.

**Examples**
The download link in the Metacat UI uses `/v2/object<id>`.  See a public example https://data-dev.ess-dive.lbl.gov/catalog/d1/mn/v2/object/ess-dive.1.rdf

This one will name the zip file `zip.zip` https://data-dev.ess-dive.lbl.gov/catalog/d1/mn/v2/packages/application%2Fbagit-097/ess-dive.1.rdf

I have demonstrated on my local environment that if `public read` access policy is removed the behavior is to download `<Datset title>.zip`. WRT `/v2/object/<id>` if the object does not contain `public read` the behavior is to download the entire package as if the packages API was requested.

**Comment by taojing2002** [comment]
Hi Val:

The url /v2/object/<id> will only download the object itself specified 
by the id, not the entire package even though the id is a resource map 
file. So Metacat's behavior is correct.

About the name of the package zip file, I can see the benefit by using 
the package title. We may pursue this way. However, sometimes it is hard 
to get the title since the diversity of the metadata standards.

Thanks,
Jing

**Comment by vchendrix** [comment]
On Mon, Jan 29, 2018 at 11:34 AM, taojing2002 <notifications@github.com>
wrote:

> Hi Val:
>
> The url /v2/object/<id> will only download the object itself specified
> by the id, not the entire package even though the id is a resource map
> file. So Metacat's behavior is correct.
>
Interesting that is not the behavior I see in my deployed instance of
Metacat. Could it be that the Metacat UI is doing some majic behind the
scene?

**Comment by taojing2002** [comment]
If MetacatUI is calling the comand /v2/object/<id>, it shouldn't change 
the behavior. Would you please give an example?

**Comment by vchendrix** [comment]
## From our dev site
1. Go to https://data-dev.ess-dive.lbl.gov.  
2. Make sure you are logged in with your Orcid.  
3. Click the first private dataset download link.  Notice that the zip file is downloaded
4. Click the first public dataset download link. Notice that the resource map file is downloaded

### Reference datasets from above
**Public Dataset:** https://data-dev.ess-dive.lbl.gov/#view/ess-dive.1
**Private Dataset:** https://data-dev.ess-dive.lbl.gov/#view/urn:uuid:02fb7537-e0af-4ea9-be82-5d1843b767d6

## From my development box
Notice that the url `v2/object<id>`. clicking this results in the zip file
being downloaded

![screen shot 2018-01-29 at 11 47 20 am](https://user-images.githubusercontent.com/1558129/35530989-9065cd18-04ea-11e8-94c4-54dd63aa645a.png)

**Comment by taojing2002** [comment]
I can't be allowed to read the private the package :(

I think you are talking about the "Download All" button, right? When you 
hover your mouth over the button, what does the url show up? I can see 
the public one shows ".../v2/packages/.....".

**Comment by vchendrix** [comment]
Oh right.    That is private to me.  No I am talking about the download link on the search results.  See the screenshot above.

**Comment by taojing2002** [comment]
If you click the download button on the search result of the private object,  you will download a rdf object, right? Since the call is ".../v2/object/...". So the behavior is correct.

I just clicked download button on search result page for the public readable object ess-dive.1 and the behavior is the same - downloaded a rdf object -ess-div.1.rdf. From the attached picture, you can see the command to download the public readable object is "../v2/object/.." as well.

So both private and public "../v2/object/.." have the same behavior -downloaded a single object.
![screen shot 2018-01-29 at 1 09 47 pm](https://user-images.githubusercontent.com/8062988/35534859-9fc550c4-04f6-11e8-9d20-4229228f2db2.png)

**Comment by vchendrix** [comment]
Those are both public datasets.  Let me see if I can give you access to the
private data set so you can see the difference in behavior.

**Comment by taojing2002** [comment]
You can search a private set, then hover the mouse over the button and 
let me know the download url.

**Comment by vchendrix** [comment]
I just set the access policy for the private dataset to AuthenticatedUser.
You should be able to view a data set name "A Private Dataset" now. Notice
when you click the download link on the search results page that the zip
file is downloaded.

**Comment by amoeba** [comment]
If it helps with debugging, I noticed that the cloud icon shows a `href` or `.../object/...` but the request MetacatUI actually sends is to `../packages/..`. This may be the source of confusion. AFAICT this is a bug in MetacatUI that could be fixed.

**Comment by vchendrix** [comment]
Ah.  Ok.  Makes sense. Thanks for ferreting this out!

**Comment by taojing2002** [comment]
Yeah, I opened the developer window on Chrome and saw the problem. So I 
will close the bug. Val, would you mind filing a ticket on MetacatUI 
project? I am going to close this one.

Thanks!

**Comment by vchendrix** [comment]
Got it thanks!

**Comment by taojing2002** [comment]
Thanks, Val!

**Comment by taojing2002** [comment]
This is a MetacatUI bug. Val will create a ticket there. Close it.
