### ISSUE TITLE
Confusion on how Metcat searches a string which is differnet than Google

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#532]
---

Author Name: **Callie Bowdish** (Callie Bowdish)
Original Redmine Issue: 3435, https://projects.ecoinformatics.org/ecoinfo/issues/3435
Original Date: 2008-06-26
Original Assignee: Jing Tao

---

Some users expect Metacat searches to work like Google.  Google works as if there is a boolean "and" between each word in a string.

If a user is looking for a title such as, Kruger National Park river flow data, and types in, Kruger river he will not bring up a data set. This is confusing to some users because currently Google adds (behind the scenes) the "and" between each word in a string. The user is unaware of the "and" being added. In Google if you want a phrase you add the Quotes.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:23:25Z

---

Original Bugzilla ID was 3435

**Comment by taojing2002** [comment]
Search part is moved to MetacatUI
