### ISSUE TITLE
Update sitemap generation and registration

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#563]
---

Author Name: **Michael Daigle** (Michael Daigle)
Original Redmine Issue: 3592, https://projects.ecoinformatics.org/ecoinfo/issues/3592
Original Date: 2008-11-04
Original Assignee: Michael Daigle

---

Update web search sitemap functionality so that:

-- the sitemap generation is done at a scheduled time.
-- the sitemaps will be registered if they have changed.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Michael Daigle** (Michael Daigle)
Original Date: 2008-11-04T21:41:36Z

---

From Matt:

Google sitemaps support the idea of a Sitemap_index.xml that lists all of your sitemaps.  We should probably enter a new bug RFE to support generation of a sitemap index file along with the metacatN.xml sitemap files so that people only have to register with google once.  After that, metacat would keep the index file updated as new sitemap files are generated.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:23:55Z

---

Original Bugzilla ID was 3592

**Comment by amoeba** [comment]
Closing in favor of #1263
