### ISSUE TITLE
Convert eml beta4 and beta6 documents to eml 210 in knb production server

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#566]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 3619, https://projects.ecoinformatics.org/ecoinfo/issues/3619
Original Date: 2008-11-10
Original Assignee: Jing Tao

---

We still have some old eml beta4 and beta6 documents at knb production server:
Here is the search result on 11/10/2008:
<matt> -//ecoinformatics.org//eml-access-2.0.0beta4//EN         |   250
<matt>  -//ecoinformatics.org//eml-access-2.0.0beta6//EN         |   454
<matt>  -//ecoinformatics.org//eml-attribute-2.0.0beta4//EN      |    16
<matt>  -//ecoinformatics.org//eml-attribute-2.0.0beta6//EN      |   659
<matt>  -//ecoinformatics.org//eml-constraint-2.0.0beta6//EN     |     1
<matt>  -//ecoinformatics.org//eml-dataset-2.0.0beta4//EN        |    24
<matt>  -//ecoinformatics.org//eml-dataset-2.0.0beta6//EN        |   281
<matt>  -//ecoinformatics.org//eml-entity-2.0.0beta4//EN         |    15
<matt>  -//ecoinformatics.org//eml-entity-2.0.0beta6//EN         |   632
<matt>  -//ecoinformatics.org//eml-literature-2.0.0beta6//EN     |     7
<matt>  -//ecoinformatics.org//eml-physical-2.0.0beta4//EN       |     1
<matt>  -//ecoinformatics.org//eml-physical-2.0.0beta6//EN       |   661
<matt>  -//ecoinformatics.org//eml-project-2.0.0beta6//EN        |    74
<matt>  -//ecoinformatics.org//eml-protocol-2.0.0beta6//EN       |    27
<matt>  -//ecoinformatics.org//eml-software-2.0.0beta6//EN       |     2

We decided not to support them anymore. So we should transform them into eml 210.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:24:00Z

---

Original Bugzilla ID was 3619

**Comment by taojing2002** [comment]
The tasks have been done.
