### ISSUE TITLE
Add the ability to modify multi-line properties

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#643]
---

Author Name: **Michael Daigle** (Michael Daigle)
Original Redmine Issue: 3830, https://projects.ecoinformatics.org/ecoinfo/issues/3830
Original Date: 2009-02-18
Original Assignee: Michael Daigle

---

Right now, SortedProperties will read a multi-line property, but not modify one.  It should be able to modify a multi-line property and maintain format.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:24:41Z

---

Original Bugzilla ID was 3830

**Comment by artntek** [comment]
No longer needed, given the move to the new properties overlay system (see Epic #1611). Java Properties framework does not support writing to props files in a specific formatted way.
