### ISSUE TITLE
Enable TLS for all LDAP functions

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#706]
---

Author Name: **Michael Daigle** (Michael Daigle)
Original Redmine Issue: 4602, https://projects.ecoinformatics.org/ecoinfo/issues/4602
Original Date: 2009-12-04
Original Assignee: ben leinfelder

---

Currently TLS is only enabled for authentication in LDAP.  Secure systems like the PARC LDAP need TLS for all appropriate functions.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:27:26Z

---

Original Bugzilla ID was 4602

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **ben leinfelder** (ben leinfelder)
Original Date: 2013-04-08T20:36:56Z

---

This should be considered with our InCommon application.

**Comment by taojing2002** [comment]
The issue has been fixed.
