### ISSUE TITLE
The 611 CDR documents replicated to KNB need to be repaired by fixing their inline data.

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#797]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 5535, https://projects.ecoinformatics.org/ecoinfo/issues/5535
Original Date: 2011-11-09
Original Assignee: ben leinfelder

---

This bug is the section 4 of the ongoing concerns:
http://bugzilla.ecoinformatics.org/show_bug.cgi?id=3296

During the replication, the "&amp;" and "&lt;" in the inline data section of the 611 CDR document in LTER were changed to "&" and "<" in knb site.

We need to fix it. Duane proposed a solution on the bug 3296.

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:30:48Z

---

Original Bugzilla ID was 5535

**Comment by taojing2002** [comment]
The task has been done.
