### ISSUE TITLE
Replace COS Mime multipart library

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#804]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 5548, https://projects.ecoinformatics.org/ecoinfo/issues/5548
Original Date: 2011-11-21
Original Assignee: ben leinfelder

---

Here is a comment from Matt in bug 5543:

The COS Mime multipart library is incredibly old, and we should
seriously consider replacing it.  On the client side for DataONE, we've
switched to using the nicely maintained Apache HttpComponents implementation,
particularly the MIME MultipartEntity class for representing our mime messages
(http://hc.apache.org/httpcomponents-client-ga/httpmime/apidocs/org/apache/http/entity/mime/MultipartEntity.html).

**Comment by mbjones** [comment]
---

Original Redmine Comment
Author Name: **Redmine Admin** (Redmine Admin)
Original Date: 2013-03-27T21:30:51Z

---

Original Bugzilla ID was 5548

**Comment by taojing2002** [comment]
It is done.
