### ISSUE TITLE
In the systemmetadata table on the dev2 machine, some guids have archvied=false and obsoleted_by= null, but the guids are the values of obsoletes of the other rows.

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#924]
---

Author Name: **Jing Tao** (Jing Tao)
Original Redmine Issue: 6038, https://projects.ecoinformatics.org/ecoinfo/issues/6038
Original Date: 2013-07-19

---

knb=> select archived, obsoleted_by from systemmetadata where guid='nikkis.27.1';
 archived | obsoleted_by 
----------+--------------
 f        | 
(1 row)

This means the guid nikkis.27.1 is not archived.

However,

knb=> select guid, obsoletes from systemmetadata where obsoletes='nikkis.27.1';
    guid     |  obsoletes  
-------------+-------------
 nikkis.27.5 | nikkis.27.1
(1 row)

This means that the nikkis.27.1 is archived.

Those guids with the issues are:
peggym.36.15
judithk.1014.1
judithk.1018.2
judithk.1000.10
peggym.82.4
peggym.1048.6
nikkis.7.2
judithk.1034.1
nikkis.169.2
judithk.332.1
nikkis.27.1

In them n-demo-4, there are three ids with the issue:
doi:10.5072/FK2/LTER/knb-lter-gce.333.5
doi:10.5072/FK2/LTER/knb-lter-gce.331.12
doi:10.5072/FK2/LTER/knb-lter-gce.335.6

We need to figure out why this happened.

**Comment by taojing2002** [comment]
Dev2 machine doesn't exist anymore and the issue is not important since it is a test machine.
